### ISSUE TITLE
documentation as agreed

### ISSUE THREAD

**Issue by cordoval** [goaop/framework#106]
since the 9th we will start bootstrapping docu, with Gush of course

please @lisachenko assign me :baby:

**Comment by lisachenko** [comment]
Great issue, let's prepare for it! I have added you as collaborator to the repo. Do you have any suggestions for keeping/generating docs?
Currently, all docs are under Jekul and are hosted under gh-pages from the repo [lisachenko/go.aopphp.com](https://github.com/lisachenko/go.aopphp.com)

**Comment by cordoval** [comment]
could be nice to switch them to sculpin since that is fully php and nice
gush documentation is using sculpin although i have not finished

**Comment by lisachenko** [comment]
Don't know about sculpin. However, it doesn't matter which generator will be used, only requirement is markdown :)

**Comment by lisachenko** [comment]
Let's continue with octopress for now, this should be easiest way to contribute without big changes. I will ping you after holiday in the skype and we will discuss the process.
I'm very happy to see positive changes in the documentation :) Hope, that you help will give more attention to the AOP and documentation will be useful for developers.

**Comment by mnapoli** [comment]
Hi guys, I was reading through all the issues and can't help but suggest [Couscous](http://mnapoli.fr/Couscous/) for generating the docs if you are looking for something simple.

Cheers, keep the good stuff coming

**Comment by lisachenko** [comment]
@mnapoli thank you for your suggestion, but I think that octopress is more attractive now, because there are a lot of plugins for it.

**Comment by mnapoli** [comment]
@lisachenko no problem :)

**Comment by lisachenko** [comment]
At the moment, I haven't a free time to write a good documentation, so this task is closed.

For future readers: if you have a wish to help me with documentation about AOP and want to earn some money - just ping me by email or by task. I can pay for good articles.
