### ISSUE TITLE
Bug with cache

### ISSUE THREAD

**Issue by forx** [goaop/framework#107]
Hi.
When I try to transform some classes that are higher than rootPath, I have problems with cache, because in method "transform" of "CachingTransformer" class $originalUri and $cacheUri are the same. And so it use original source and don`t transfom it.

It can be solved by adding this code 

``` php
if ($cacheUri == $originalUri) {
    $this->processTransformers($metadata);
    return;
} 
```

before      

``` php
// TODO: add more accurate cache invalidation, like in Symfony2
```

Or it can be cached another way.

**Comment by lisachenko** [comment]
Thank you for the report.

I think that AOP should not transform classes that are higher than `rootPath` because this can lead to incorrect transforming of global dependencies and will result in incorrect behaviour. AOP should transform only source files of application and these files are typically below `rootPath`.

Could you please describe your use case with global files?

**Comment by forx** [comment]
But if I don't using cache it transform it perfectly.
I have several projects and one framework for it and structure like:
-project1
-project2
-project3
-framework
And I use phpunit with aspectmock library witch use AOP. I want transform some methods from framework for testing projects functionality.
Also I try to use symbolic links, but it doesn't work with cache too.

**Comment by lisachenko** [comment]
Could you try to point `rootPath` higher? So, all directories (project1, project2, project3 and framework) will be under the `rootPath`? I used this technique with Yii

**Comment by lisachenko** [comment]
Is this issue still actual? Ping.

**Comment by forx** [comment]
With point rootPath higher it works.
If you think this isn`t a bug, i can close issue.

**Comment by lisachenko** [comment]
Ok, thank your for feedback. I think that it isn't a real issue, because it's a special logic to prevent some global changes/transformations. Will close this issue.
