### ISSUE TITLE
AopComposerLoader is inited when should not

### ISSUE THREAD

**Issue by TrustNik** [goaop/framework#111]
I am using this lib together with AspectMock and there is one issue I've found.
In the AopComposerLoader.php you call AopComposerLoader::init(); at the bottom of the file. This initialization overrides default compouser autoloader. Because of you have:

"autoload": {
         ...
        "files": ["src/Go/Instrument/ClassLoading/AopComposerLoader.php"]
},

this file is loaded via require at every start of the app, even if we completly dont need your lib. 
And this issue makes it even worse because since we override the autoloader, php 5.5 opcache stop caching loading files.

**Comment by lisachenko** [comment]
Thank you for the bug report. I will look into this issue asap. However, it's not clear, why opcache is not working for you. Could you please provide more details to show that opcache is not working?

**Comment by TrustNik** [comment]
This is strange. I have investigate opcache problem and found out, that without using your autoloader xhprof says that:

Function                                                      |Call Count|  Exclusive 
Composer\Autoload\ClassLoader::loadClass    |  144        |          6,207 µs

so we have 6ms of loading classes. And if I turn on your loader I have:

Function                                                                                    |Call Count   |Exclusive 
Go\Instrument\ClassLoading\AopComposerLoader::loadClass |144        |      89,618 µs

89ms(!) of loading.

I have opcache turned on in this tests. The best solution here is not to init your aoutoloader automaticly, and use it only where it needed. For my case it needed in tests, so I dont really care about perfomance since it is not production.

**Comment by lisachenko** [comment]
@TrustNik could you attach profiles? I created a patch, could you switch require-dev to this branch in your composer.json?

**Comment by TrustNik** [comment]
@lisachenko I've swiched and run tests again - now everything is great.
Couldn't really attach profiles, but I think it's not smth special in my code. Just run tests at any medium/large app with lots of loading files.

**Comment by lisachenko** [comment]
Merged. Potentially there will be edge cases when AOP won't be able to start correctly now, but faster initialization is more important.

**Comment by TrustNik** [comment]
Thanks!
