### ISSUE TITLE
When i use the pattern that selects multiple values, all method are starting by one of values are matched

### ISSUE THREAD

**Issue by jbrenaudin** [goaop/framework#115]
When i use the pattern that selects multiple values, all method are starting by "get" are matched.

/**
- @Before("execution(public *_\Controller\_Controller->get|getList|create|update|delete(*))")
  */

However, when i use the simple pattern, only "get" method is matched.

/**
- @Before("execution(public *_\Controller\_Controller->get(*))")
  */

I think the matching must be strict !!!

**Comment by lisachenko** [comment]
Oh, yeap! :) Thank you, occasionally introduced this bug in #113 implementation. Will fix it soon
