### ISSUE TITLE
Is there a design by contract class?

### ISSUE THREAD

**Issue by letharion** [goaop/framework#125]
Figured I'd ask, so I can avoid duplicating effort.

When developing, it would be really cool to use GAP to check if the inputs and return value correspond to what the function docs say.

Has anyone already implemented that? Otherwise I'm gonna consider doing it. :)

**Comment by lisachenko** [comment]
Heh, I have a good answer for this issue: https://github.com/lisachenko/php-deal. There is a support for pre-conditions (Verify), post-conditions (Ensure), access to the private and protected properties of object from contracts. For post-conditions, it's also possible to verify result by using `$__result` variable and `$__old` variable with clone of object.

**Comment by lisachenko** [comment]
Invariants will be implemented soon, they require some functionality from Go! framework to work ideally.

**Comment by lisachenko** [comment]
For any questions, please open an issue on [PhpDeal framework](https://github.com/lisachenko/php-deal)
