### ISSUE TITLE
Annotation use docs

### ISSUE THREAD

**Issue by ShurikAg** [goaop/framework#126]
Hi all, 

We are currently investigating your awesome library for our project, and thank you for very much for this project.

I was trying to find any documentation about use of annotations except the examples.
Is there any docs about how to use all types of annotation (except the examples)?

Thanks,

**Comment by lisachenko** [comment]
Hello! Thank you for feedback.

Unfortunately, documentation is not full now, but I hope that somebody will be able to help me with it, because my English is not very good. You can start by reading a documentation about AOP for [Spring](http://docs.spring.io/spring/docs/2.0.x/reference/aop.html) or [AspectJ](http://www.eclipse.org/aspectj/doc/next/progguide/language.html) frameworks to learn some basic pointcuts and terminology and then have a look at [tests](https://github.com/lisachenko/go-aop-php/blob/master/tests/Go/Aop/Pointcut/PointcutParserTest.php#L55-L99).

There is also small part of [information about pointcuts](http://go.aopphp.com/docs/pointcuts-and-advices/) on official site.

**Comment by ShurikAg** [comment]
Well, I would love to help :)

However, I need the syntaxes for the annotations.
For example, I am trying to intercept ALL methods an all classes by doing this:

```
/**
     * Method that will be called before real method
     *
     * @param MethodInvocation $invocation Invocation
     * @Before("execution(**\*->*(*))")
     */
    public function beforeMethodExecution(MethodInvocation $invocation)
```

It actually causes fatal error in Parser.

**Comment by lisachenko** [comment]
You missed visibility modifier in the pointcut expression. It should be something like this: `@Before("execution(pubilc|protected **->*(*))")`

**Comment by ShurikAg** [comment]
Thank you sir!

As for the docs. Do you have a repo I can fork from?

**Comment by ShurikAg** [comment]
I am getting this:

```
PHP Fatal error:  Uncaught exception 'Dissect\Parser\Exception\UnexpectedTokenException' with message 'Unexpected | at line 1.

Expected one of ::, ->, NsSeparator, *, NamePart, (, ), +.' in /var/www/quickstart/vendor/jakubledl/dissect/src/Dissect/Parser/LALR1/Parser.php:60
Stack trace:
#0 /var/www/quickstart/vendor/lisachenko/go-aop-php/src/Go/Core/AbstractAspectLoaderExtension.php(95): Dissect\Parser\LALR1\Parser->parse(Object(Dissect\Lexer\TokenStream\ArrayTokenStream))
#1 /var/www/quickstart/vendor/lisachenko/go-aop-php/src/Go/Core/AbstractAspectLoaderExtension.php(40): Go\Core\AbstractAspectLoaderExtension->parseTokenStream(Object(Go\Core\GoAspectContainer), Object(ReflectionMethod), Object(Go\Lang\Annotation\Before), Object(Dissect\Lexer\TokenStream\ArrayTokenStream))
#2 /var/www/quickstart/vendor/lisachenko/go-aop-php/src/Go/Core/GeneralAspectLoaderExtension.php(79): Go\Core\AbstractAspectLoaderExtension->parsePointcut(Object(Go\Core\GoAspectContainer), Object(aop\Aspect\FunctionCallAuditAspect), Object(ReflectionMethod in /var/www/quickstart/vendor/lisachenko/go-aop-php/src/Go/Core/AbstractAspectLoaderExtension.php on line 114
[06-Feb-2014 16:00:34 America/New_York] PHP Fatal error:  Uncaught exception 'Dissect\Parser\Exception\UnexpectedTokenException' with message 'Unexpected | at line 1.

Expected one of ::, ->, NsSeparator, *, NamePart, (, ), +.' in /var/www/quickstart/vendor/jakubledl/dissect/src/Dissect/Parser/LALR1/Parser.php:60
Stack trace:
#0 /var/www/quickstart/vendor/lisachenko/go-aop-php/src/Go/Core/AbstractAspectLoaderExtension.php(95): Dissect\Parser\LALR1\Parser->parse(Object(Dissect\Lexer\TokenStream\ArrayTokenStream))
#1 /var/www/quickstart/vendor/lisachenko/go-aop-php/src/Go/Core/AbstractAspectLoaderExtension.php(40): Go\Core\AbstractAspectLoaderExtension->parseTokenStream(Object(Go\Core\GoAspectContainer), Object(ReflectionMethod), Object(Go\Lang\Annotation\Before), Object(Dissect\Lexer\TokenStream\ArrayTokenStream))
#2 /var/www/quickstart/vendor/lisachenko/go-aop-php/src/Go/Core/GeneralAspectLoaderExtension.php(79): Go\Core\AbstractAspectLoaderExtension->parsePointcut(Object(Go\Core\GoAspectContainer), Object(aop\Aspect\FunctionCallAuditAspect), Object(ReflectionMethod in /var/www/quickstart/vendor/lisachenko/go-aop-php/src/Go/Core/AbstractAspectLoaderExtension.php on line 114
```

**Comment by lisachenko** [comment]
> As for the docs. Do you have a repo I can fork from?

Yes, sure: https://github.com/lisachenko/go.aopphp.com - it's simple octopress site with markdown syntax.

> `PHP Fatal error:  Uncaught exception 'Dissect\Parser\Exception\UnexpectedTokenException'

It looks like you have an old verision of framework. Could you please give me your current version of framework and please attach an exact copy of bad pointcut expression. For old version you can also try to use "public" instead of "public|protected"

**Comment by ShurikAg** [comment]
Sorry for the delay.

composer.json

```
...
"lisachenko/go-aop-php": "0.4.3"
...
```

FunctionCallAuditAspect.php

```
<?php
namespace aop\Aspect;

use Go\Aop\Aspect;
use Go\Aop\Intercept\FieldAccess;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\After;
use Go\Lang\Annotation\Before;
use Go\Lang\Annotation\Around;
use Go\Lang\Annotation\Pointcut;
/**
 * This aspect is build to log ALL function calls in the system
 *
 * @author: Alex Agulyansky <alex.agulyansky@quickmobile.com>
 * @Date Created: Feb 6, 2014
 * @copyright 2014 Quickmobile Inc.
 */
class FunctionCallAuditAspect implements Aspect
{

    /**
     * Method that will be called before real method
     *
     * @param MethodInvocation $invocation Invocation
     * @Before("execution(public|protected **\*(*))")
     */
    public function beforeMethodExecution(MethodInvocation $invocation)
    {
        $obj = $invocation->getThis();
        $logMsg = 'Calling Before Interceptor for method: '.
                    is_object($obj) ? get_class($obj) : $obj.
                    $invocation->getMethod()->isStatic() ? '::' : '->'.
                    $invocation->getMethod()->getName().
                    '()'. ' with arguments: '. json_encode($invocation->getArguments()).
                    "\n";

        file_put_contents('/var/log/quickstart/methodaudit.log', $logMsg, FILE_APPEND);
    }
}
```

I also tried this: 

```
@Before("execution(public|protected **->*(*))")
```

**Comment by lisachenko** [comment]
`@Before("execution(public|protected **->*(*))")` is correct version. `@Before("execution(public|protected **\*(*))")` is incorrect.

Syntax of execution pointcut is folloiwing:
`execution( {MemberModifiers} {ClassFilter}{MethodCall}{NamePattern}(*) )` for matching methods.

`{MethodCall}` is "->" for dynamic methods and "::" for static methods.
`{MemberModifiers}` is "*" or non-empty list of modifiers [public, protected, final?] separated by vertical line, eg: "protected", "public|protected" or "*"
`{NamePattern}` is pattern for name, can contain "*" and "?" for glob pattern, eg: "testConcreteMethod", "set*", etc

Please, check that debug mode for kernel is activated, because for production mode annotations are cached, so you can make changes in the pointcut, but this modifications are not visible in production mode for the kernel.

**Comment by ShurikAg** [comment]
hmmm...
This is strange. The fist time I run it it works, but any consecutive execution simply ignored.

**Comment by lisachenko** [comment]
Do you use opcode cachers/zend extensions? Probably, this is the same with https://github.com/lisachenko/go-aop-php/issues/59#issuecomment-19688066

**Comment by ShurikAg** [comment]
Does not look like it, I have APC and memcache. Tried killing both of them. Didn't change anything. And I don't have any zend ones.

**Comment by lisachenko** [comment]
So, let's have a look at your kernel and AOP initialization (where you make an include for AOP?). Hope, that I will be able to understand what is wrong remotely :)

**Comment by lisachenko** [comment]
And one more question is for `apc.canonicalize`. Is it enabled or not? This flag should be disabled for debug mode and can be enabled for production mode.

This table can help you:

| Application mode | AOP debug flag | apc.canonicalize |
| --- | --- | --- |
| Debug | true | false |
| Production | false | true/false |

**Comment by ShurikAg** [comment]
php -i | grep apc.canonicalize
apc.canonicalize => Off => Off

**Comment by ShurikAg** [comment]
initialization:

```
/**
 * This hook initializes AOP
 */
use aop\ApplicationAspectKernel;

function setupAop()
{
    $applicationAspectKernel = ApplicationAspectKernel::getInstance();
    $applicationAspectKernel->init(array(
        'debug' => true,  // Use 'false' for production mode
        // Cache directory
        'cacheDir' => QSROOT . '/cache/',  // Adjust this path if needed
        // Include paths restricts the directories where aspects should be applied, or empty for all source files
        'includePaths' => array(
            QSPATH
        )
    ));
}
```

Kernel:

```
namespace aop;

use aop\Aspect\FunctionCallAuditAspect;

use Go\Core\AspectContainer;
use Go\Core\AspectKernel;
/**
 * AOP Kernel calss
 *
 * @author: Alex Agulyansky <alex.agulyansky@quickmobile.com>
 * @Date Created: Feb 5, 2014
 * @copyright 2014 Quickmobile Inc.
 */
class ApplicationAspectKernel extends AspectKernel
{

    /**
     * Configure an AspectContainer with advisors, aspects and pointcuts
     *
     * @param AspectContainer $container
     *
     * @return void
     */
    protected function configureAop(AspectContainer $container)
    {
        $container->registerAspect(new FunctionCallAuditAspect());
    }
}
```

Aspect:

```
namespace aop\Aspect;

use Go\Aop\Aspect;
use Go\Aop\Intercept\FieldAccess;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\After;
use Go\Lang\Annotation\Before;
use Go\Lang\Annotation\Around;
use Go\Lang\Annotation\Pointcut;

class FunctionCallAuditAspect implements Aspect
{

    /**
     * Method that will be called before real method
     *
     * @param MethodInvocation $invocation Invocation
     * @Before("execution(public **->*(*))") 
     */
    public function beforeMethodExecution(MethodInvocation $invocation)
    {
        $obj = $invocation->getThis();
        $logMsg = 'Calling Before Interceptor for method: '.
                    (is_object($obj) ? get_class($obj) : $obj).
                    ($invocation->getMethod()->isStatic() ? '::' : '->').
                    $invocation->getMethod()->getName().
                    '()'. ' with arguments: '. json_encode($invocation->getArguments()).
                    "\n";

        file_put_contents('/var/log/quickstart/methodaudit.log', $logMsg, FILE_APPEND);
    }
}
```

**Comment by lisachenko** [comment]
Hm...everything looks good.

Do you call `setupAop()` function immediately after including of composer loader in bootstrap? Are there AOP files in the cache directory? Try to clean cache and run your script one more time. Is cache filled?

**Comment by ShurikAg** [comment]
Nope, cache folder is clean. setupAop() is pretty much one of the first things that called.

**Comment by lisachenko** [comment]
Try to remove the last slash for cache directory :) Stupid bug, I fixed it for newer version

**Comment by ShurikAg** [comment]
Nothing... and cache is clean.

**Comment by lisachenko** [comment]
Try to point web server root directory to the `demos` directory of framework and run it in the browser. It should work. If it's not working, then somethig is bad with your environment.

**Comment by ShurikAg** [comment]
At some point it was outputting this into the log:

```
[root@localhost quickstart]# tail -f /var/log/quickstart/methodaudit.log
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by ShurikAg** [comment]
What is demos directory?

**Comment by lisachenko** [comment]
> What is demos directory?

Directory inside go-aop-framework: https://github.com/lisachenko/go-aop-php/tree/master/demos

**Comment by ShurikAg** [comment]
By the way, what about non namespaced classes?
Because, on one of the pages it did generate the cache for one of my vendor libraries.

**Comment by ShurikAg** [comment]
hmmm... interesting, any code that is not mine the cache get's generated.

**Comment by ShurikAg** [comment]
Hi, 

I an trying to debug it now. Can you explain how the parsing is called? All we do is just initializing the container, right? How does PHP know that executed file/class/method needs to be intercepted?

**Comment by lisachenko** [comment]
Hi, framework intercepts all calls to the include/require operators and modifies the source code according to the defined aspects. Source code is then analyzed before PHP can execute it and static reflection is used (tokenizer) to build new classes.

**Comment by ShurikAg** [comment]
Can you point me where it does it?

**Comment by lisachenko** [comment]
Yes, just have a look into https://github.com/lisachenko/go-aop-php/blob/master/src/Go/Instrument/ClassLoading/SourceTransformingLoader.php and list of transformers in https://github.com/lisachenko/go-aop-php/tree/master/src/Go/Instrument/Transformer

**Comment by ShurikAg** [comment]
OK, I think I found the problem: I am using symfony class loader first, so Go! does not pick it up.
Here is my loader config:

```
$loader = new UniversalClassLoader();
    $loader->register();

    $appPath = realpath(substr(QSPATH, 0, -1));
    $loader->registerNamespaces(array(
        'libraries' => $appPath,
        'forms' => $appPath,
        'models' => $appPath,
        'sync' => $appPath,
        'core' => $appPath,
        'component' => $appPath,
        'controllers' => $appPath,
        'aop' => $appPath
    ));
```

What would be the right way to merge the two loaders?

**Comment by lisachenko** [comment]
Oh, I can suggest to extend UniversalClassLoader class and override `loadClass()` method like here https://github.com/lisachenko/go-aop-php/blob/master/src/Go/Instrument/ClassLoading/AopComposerLoader.php#L89-L102, but this can lead to some errors during class loading process...

**Comment by lisachenko** [comment]
Why do you still use class loader? How did you install dependencies for go-aop-php? By hand or with composer?

**Comment by ShurikAg** [comment]
I was using both loaders.
OK, now I converted everything to use Composer's loader.
Still does not help ...

**Comment by lisachenko** [comment]
It's pity because I can not reproduce this bug locally and can not help you, only debugging can help you. Probably, it will be better to start with demos and to play with pointcuts to look at some working examples

**Comment by ShurikAg** [comment]
Well, at least I now getting the cache generated. Similar to this:

```
<?php
namespace libraries\entity\manager;

use libraries\CommonManager;
use libraries\cache\CacheDriverFactory;

include_once \Go\Instrument\Transformer\FilterInjectorTransformer::rewrite( (QSPATH . 'libraries/entity/manager/EntityManagerInterface.php'), '/var/www/quickstart/application/libraries/entity/manager');

/**
 * This class manages locale logic
 *
 * @author: Lei Zhang <lei.zhang@quickmobile.com>
 * @Date Created: Dec 12, 2012
 * @copyright Quickmobile Inc. 2012
 */
class LocaleManager extends CommonManager implements \EntityManagerInterface
{
...
```

Is this by design?

**Comment by ShurikAg** [comment]
I think I am getting closer, now I am getting a fatal error: 

```
 Fatal error: Cannot redeclare class TokenReflection\Broker\Backend\Memory in /var/www/quickstart/vendor/andrewsville/php-token-reflection/TokenReflection/Broker/Backend/Memory.php on line 26
```

<a href="http://tinypic.com?ref=21mhq85" target="_blank"><img src="http://i61.tinypic.com/21mhq85.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ShurikAg** [comment]
Here is some more information:

```
AopComposerLoader->loadClass($class)   line 97
```

EVERY time for any class in case that the class needs to be rewritten, I am getting the error above.

**Comment by lisachenko** [comment]
Hi! Sorry for the delay, I was busy on weekends. This fatal error is due to the logic of class rewriting, when framework tries to rewrite its own classes. To fix this fatal error, you should add an extra check for internal classes to prevent them from being processed, see [part 1](https://github.com/lisachenko/go-aop-php/blob/master/src/Go/Instrument/ClassLoading/AopComposerLoader.php#L38-L43) and [part 2](https://github.com/lisachenko/go-aop-php/blob/master/src/Go/Instrument/ClassLoading/AopComposerLoader.php#L92-L98)

**Comment by ShurikAg** [comment]
So I have the ones that specified in Part 1. Is there any more that i have to add?

**Comment by lisachenko** [comment]
> Is there any more that i have to add?

No, this should be enough for correct running.
I have also noticed, that you use CodeIgniter and initialization of AOP is not at the early beginning of script execution, so part of files are already loaded into memory. Aspects can not be woven into these classes, so be careful.

**Comment by ShurikAg** [comment]
OK, something strange: it just started to work....

However in one of the pages I have this error:

```
A PHP Error was encountered

Severity: Warning

Message: assert(): Assertion "count($namespaces) < 2; /* Only one namespace per file is supported */" failed

Filename: Transformer/WeavingTransformer.php

Line Number: 96
```

What couple be the reason for this one?

**Comment by ShurikAg** [comment]
OK, I figured it out. I had one of the classes with the wrong definition of use statement. It was before the namespace statement.

**Comment by ShurikAg** [comment]
Now, this is working pretty well now for namespaced classes. What about the non namespaced ones, that don't use the loader?

**Comment by lisachenko** [comment]
> Now, this is working pretty well now for namespaced classes.

Great news! :)

>  What about the non namespaced ones, that don't use the loader?

Framework is able to work with non-namespaced files too. Just pay an attention to all places with `include` or `require` operators and ensure that they are processed by framework (it's done recursively). So if some file is loaded by framework and it has an include operator in it, then it will be rewritten by framework to work correctly with AOP. No extra changes are needed.

**Comment by ShurikAg** [comment]
Hopefully, one of the last questions (in this round):
Where the framework caches the classes? In a lot of cases, I am deleting the entire cache folder, but it still serves the old file.

**Comment by lisachenko** [comment]
Framework caches the classes only in the cache directory. But if you use an opcode cacher without file modification check (this is typically true for production environment) then classes can be cached in the shared memory.

PS. There is also one rare mystery bug, that can not be reproduced easily. Framework can rewrite original files with transformed version.

**Comment by ShurikAg** [comment]
At this point, it seems like my files are locked in one state. Does not matter what I do, the change is not picked up. Restarted everything, deleted cache folder. nothing helps. Any thought?

**Comment by lisachenko** [comment]
Just WTF! :) Please, check everything carefully. I think that you missed something or not synchronized.

**Comment by ShurikAg** [comment]
This one is a real WTF!!!! I've restarted the VM. Killed all the caches, killed tmp folder... nothing.

**Comment by lisachenko** [comment]
I know that AOP is magic tool :)) but it's not so magic to work after killing the cache, just try to disable kernel initialization to see that AOP is disabled.

**Comment by ShurikAg** [comment]
I think I know what the problem is. It seem like, in my flow, the app does not save a some record correctly and eventually goes different route. However, the reason it does it is that at some point it throws an exception:

```
Given object is not an instance of the class this method was declared in
```

**Comment by ShurikAg** [comment]
OK, it's been resolved. There was a problem with my code.
Thanks.

**Comment by lisachenko** [comment]
@ShurikAg glad, that it's been resolved! you are welcome )
