### ISSUE TITLE
What works / does not work with PHP 5.3

### ISSUE THREAD

**Issue by bgaillard** [goaop/framework#135]
Hi, we would like to use Go AOP in one of our project which is using PHP 5.3. 

The documentation says the framework works "partially" with PHP 5.3. 

I think it would be cool to have more details about what are the specific features which does not work. 

In our case we only want to create an advice to manage transactions. 

``` php

class TransactionAspect implements Aspect {

    /**
     * Method called around service functions which have to be transactional.
     *
     * @param \Go\Aop\Intercept\MethodInvocation $methodInvocation an object which represents the service method which
     *        is called.
     *
     * @Around("execution(public Application\Service\Impl\*->save*|update*)")
     */
    public function around(MethodInvocation $methodInvocation) {

        ... 

    }

}
```

Can we encounter problems with this simple aspect / advice ? 

Thanks.

**Comment by lisachenko** [comment]
Hello, AOP should working with 5.3. So you shouldn't expect any issues except one: Late Static Binding (aka LSB) will not work in the intercepted methods.

For your example, if methods `saveXXX` or `updateXXX` inside `Application\Service\Impl` namespace are containing expressions like this: `new static()`, `static::executeMethod()` then you will definitely face some issues.

However, AOP is easy to try, so you can make a test branch, enable AOP in it and then just try to use it ) This will give you single positive or negative result.

Good luck with AOP!
