### ISSUE TITLE
Interception of internal functions doesn't work if no cacheDir

### ISSUE THREAD

**Issue by hax** [goaop/framework#136]
Seems a limitation of current implementation.

**Comment by lisachenko** [comment]
You are right, it's impossible to intercept internal functions without an ability to redefine them in a file. There is only one workaround for that is to utilize `php://memory` stream, but I haven't time to check this.

**Comment by sagikazarmark** [comment]
Any update on this?

**Comment by lisachenko** [comment]
Unfortunately, no, because I'm working on [goaop/parser-reflection](https://github.com/goaop/parser-reflection) library now to enable support for PHP5.6 and PHP7 syntax features.

**Comment by TheCelavi** [comment]
I am not 100% sure, but it seams that current implementation can not work without cache directory and weaving classes/function in proxied files.

On top of that, why should we allow engine to work without cache directory at first place? What would be benefits of that?

If there are none, I would modify framework/src/Core/AspectKernel.php, method `normalizeOptions` to insist on cache directory and close this issue.

**Comment by lisachenko** [comment]
Earlier, it was funny to enable AOP without cache dir, it was kind of black magic that was making code working even without cache directory.
Nowadays all parts of framework are optimized for working with cache directory (filemtime checks, opcode cache support, easier debugging of proxies, etc).

We can drop support for empty cache directory, it MUST be present.

@TheCelavi But be aware, that there are read-only filesystems where cache directory is present, but it isn't writable. We should care about this to support modern cloud hostings and read-only file systems.

**Comment by TheCelavi** [comment]
Ok, I will have that in mind when I start on the patch.

**Comment by TheCelavi** [comment]
Cache directory for weaved classes is a "must" for Go! AOP to work. Closing this one on that premise. Changed in https://github.com/goaop/framework/pull/359.
