### ISSUE TITLE
Running on WordPress doesn't seem to work

### ISSUE THREAD

**Issue by mustela** [goaop/framework#138]
Hey there! I'm trying to use the framework to create a plugin for wordpress, it would be really useful for debugging specially. But I can't make it works. 

I've created a WP plugin with the framework, and it seems to be loading all the classes and configuring the aspects, but the methods isn't being intercepted. I've tried with my custom classes and your examples, but neither of them work. 

So a few question: 

1 - Is there any issue you know related to order executing ?
2 - Where can I see the debug information when I configure the kernel using "debug"= true ? I can't see it on /cache, or php error log, and I can't find anything in the documentation. 

Here you can see what I'm doing (it's really alpha code :) ) 
https://github.com/mustela/maven-debug/blob/master/maven-debug.php

Any doc/info would be great!

**Comment by lisachenko** [comment]
Hi! Framework is not magic, so when you include/require a file by hand, AOP won't be applied. So issue is in 

``` php
require_once 'vendor/lisachenko/go-aop-php/demos/Demo/Example/General.php';
```

To fix it, just delegate autoloading of Demo files to composer and remove explicit requires:

``` php
require_once __DIR__ . '/vendor/autoload.php'; // use composer
$loader->add('Demo', __DIR__ .'/vendor/lisachenko/go-aop-php/demos/');
```

**Comment by mustela** [comment]
Oh :), thanks I'll try that!

**Comment by mustela** [comment]
I can't make it work :(, I've tried moving things from one place to another, re-coded everything but something is not right with the autoloading feature. 

Here you can see my updated code 
https://github.com/mustela/maven-debug

I've moved all the code into /App 
https://github.com/mustela/maven-debug/tree/master/App

Here you can see how I'm using composer to load the file 
https://github.com/mustela/maven-debug/blob/master/App/init.php

But when the execution reach these lines 

$general = new App\General('Hola!!');
$general->publicHello();

I'm just getting a file not found error. App\General can't be found. 

I'm not sure what else to try, so if you have a minute would be really appreciate your feedback. 

Thanks

**Comment by lisachenko** [comment]
You have simple misconfiguration for the namespace :) To fix that error, just point `App` namespace to the root directory, because `App` folder should be matched:

``` php

// Composer autoloading
if (file_exists(__DIR__ . '/../vendor/autoload.php')) {

    /** @var Composer\Autoload\ClassLoader $loader */
    $loader = ( include __DIR__ . '/../vendor/autoload.php');
    $loader->add('App', dirname(__DIR__)); // <== namespace will be matched with directory
}
```

``` bash
php App/init.php
# Hello, you have a public message: Hola!!<br>
```

**Comment by mustela** [comment]
Love you man! :P Working perfectly! 

Thanks a lot!

**Comment by mustela** [comment]
Sorry, I have to re-open the issue :(

Now everthing is being loaded by composer, but I can't make the aspect work on a class outside the "App". 

As you can see here https://github.com/mustela/maven-debug/blob/master/composer.json, I've added the classmap directive to generate the maps of my other app.  

Now I have a new file /composer/autoload_classmap.php with things like: 
![screenshot 2014-03-26 15 38 11](https://f.cloud.github.com/assets/325222/2529251/b0259f1e-b518-11e3-8e17-d99bdc885a14.png)

And all those clases are being loaded correctly. But (yes, sorry), the aspect isn't been executed. 

This one, works great

```
* @Pointcut("execution(public App\General->*(*))")
```

But this one don't (or any other class under "Maven")

```
* @Pointcut("execution(public Maven\Core\Cart->*(*))")
```

Any idea?

**Comment by lisachenko** [comment]
@mustela you should make two changes: the first one is to change the pointcut to match your methods and the second change is to specify `appDir` option for the AspectKernel. `appDir` should point to the root directory of your application (./plugins/maven-common directory should be below `appDir`)

AOP is applied only to the application files that are under `appDir`, all other files are loaded as-is.

**Comment by mustela** [comment]
Working now, thanks for your help and patience !

**Comment by lisachenko** [comment]
@mustela That's really nothing! It was a pleasure for me to help you )
