### ISSUE TITLE
[Q] Determine caller

### ISSUE THREAD

**Issue by rixbeck** [goaop/framework#149]
Which is the suggested practice to control which object can call a method in an advice? I'm trying to access somehow the caller object in a interception.
Thanks for the project, I'm just begin to play with... :)

**Comment by lisachenko** [comment]
Hi, could you provide more details about what you want to do?
If you want to access a target object instance (which is executed now), you can invoke `$invocation->getThis()`. For static method invocations this method will return class name as string.

**Comment by rixbeck** [comment]
I'm finding a way to restrict some objects to call target objects' methods. Because I can't imagine yet it can be described by annotations I think I have to make a decision in the body of advice (intercepting) method. (If I use the terminology right...)
For a bird view it is a modular project where submodules would be better to accessed via services and direct object instantiation would be better to denied across submodules.

**Comment by rixbeck** [comment]
Is that maybe the `within` pointcut element is the right tool?

**Comment by lisachenko** [comment]
ok, understood ) It seems, that you want to use dynamic pointcut (it can match method if some dynamic conditions is satisfied). Unfortunately, this is very expensive pointcut. For more details you could look for `cflow` and `cflowbelow` pointcuts in AspectJ. Go! AOP supports dynamic pointcuts, but this is experimental feature. `cflow` pointcut matches any method if there is specific call in the stach trace. I know, it's not so easy to understand :))

**Comment by rixbeck** [comment]
Yepp! To train the brain is highly suggested here! :)
Thanks anyway!
