### ISSUE TITLE
[Bug] Multiple dynamic pointcuts combined with logical operator won't work

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#159]
During implementation of #158, I noticed a bug when multiple dynamic pointcuts won't work.

Example: 
`dynamic(public Demo\Example\DynamicMethodsDemo::find*(*)) || dynamic(public Demo\Example\DynamicMethodsDemo->save*(*))`

This is due to wrapping of dynamic pointcut into or-ed pointcut and this part of code: https://github.com/lisachenko/go-aop-php/blob/ffb46fd31b7a0b1f0597ea7dd515a7c3a922aa01/src/Go/Core/GeneralAspectLoaderExtension.php#L96-L100

``` php
if ($pointcut instanceof Support\DynamicMethodMatcher) {
    $advice = new Framework\DynamicMethodMatcherInterceptor(
        $pointcut,
        $advice
    );
}
```

To fix this bug a bitwise check of pointcut kind should be used instead. Also all logic pointcuts such as `OrPointcut`, etc, should handle multiple arguments for method `matches()`

**Comment by daniel-sc** [comment]
This still occurs with version 0.6.1! (even though this contains the fix..)

**Comment by lisachenko** [comment]
@daniel-sc could you please, post your example of pointcut? Or even better, a broking test for this?

**Comment by daniel-sc** [comment]
Hi @lisachenko : I created a little example: https://github.com/daniel-sc/aop-dynamic-disjunction-example after installing (`composer install`) in the unit test under `test` the test `testDynamicConjugationPointcut`fails (whereas the other two tests succeed).

**Comment by lisachenko** [comment]
@daniel-sc thanks! I'll check it
