### ISSUE TITLE
filemtime(): stat failed in Caching Transformer

### ISSUE THREAD

**Issue by markNZed** [goaop/framework#171]
Getting the error:

filemtime(): stat failed for php://filter/read=go.source.transforming.loader/resource=/Applications/....

What is the prefix: php://filter/read=go.source.transforming.loader/resource= and why would that be in the path for filemtime ?

**Comment by markNZed** [comment]
Unfortunately this is turning into a major issue. We can sort of work around it by disabling debug mode then loading a page then re-enabling debug mode. But it is not a reliable workaround. Somehow the  $originalUri used in public function transform(StreamMetaData $metadata) is betting the string php://filter/read=go.source.transforming.loader/resource= prepended. Very weird.

**Comment by markNZed** [comment]
This seems a terrible hack but got past some issues:

```
        use Go\Instrument\PathResolver;
         ....

        $originalUri = $metadata->uri;
        if (preg_match('/resource=(.+)$/', $originalUri, $matches)) {
            $originalUri = PathResolver::realpath($matches[1]);
        }
```

**Comment by lisachenko** [comment]
Hello! Sorry for the delay, I'm on vacation now and haven't a good Internet here, in Kazakhstan :) 

filemtime issue is typically appears only when you are trying to include non-existent file. I hadn't put an extra-check with `if (!file_exist($fileName))` to improve the performance of library.

Extra string `php://filter/read=go.source.transforming.loader/resource=` is an internal engine of framework to perform weaving of advices into the source code. Framework heavily uses stream-filter http://php.net/manual/en/stream.filters.php for doing its job.

**Comment by lisachenko** [comment]
One more reason for your issue is an usage of non-standard extensions for PHP, like eAccelerator, ionCube, ZendProtect, etc. Do you have one of them? Or use vanilla PHP?

**Comment by markNZed** [comment]
Hi Alexander,

We are using Laravel with the Cartalyst Platform 2.0 extension. I think this is relatively standard PHP code.

The files so exist but for some reason Go! is prepending the string "php://filter/read=go.source.transforming.loader/resource=" I guess the transforms are not in the right order, the caching should be last so should never see the filter prefix ?

Enjoy the vacation!

Cheers,
  Mark

**Comment by lisachenko** [comment]
> The files so exist but for some reason Go! is prepending the string "php://filter/read=go.source.transforming.loader/resource=" I guess the transforms are not in the right order, the caching should be last so should never see the filter prefix ?

Framework uses caching even for debug mode ) but rechecks file modification time of aspects and original file. Filter prefix is valid and `CachingTransformer` should return a file from the cache immediately as a result of stream filter.

Could you clear the cache directory and give me a snippet of source code where this error occurs? Without this information it can be harder to understand the root cause.

**Comment by markNZed** [comment]
Really had dot do that. I've now patched the CachingTransformer so it strips off php://filter/read=go.source.transforming.loader/resource= if it is prefixed to $originalUri

Do you agree that $metadata->uri should not have the prefix "php://filter/read=go.source.transforming.loader/resource=" in the CachingTransformer  ?

**Comment by lisachenko** [comment]
You are right that `$metadata->uri` should always point to the concrete file without filter. Probably, there is an issue with `PathResolver` class. Look at https://github.com/lisachenko/go-aop-php/blob/master/src/Instrument/Transformer/StreamMetaData.php#L52

Could you make a breakpoint there and give me a value that can not be parsed by `PathResolver`? Strange case...

**Comment by markNZed** [comment]
Not so easy to reproduce all the time. The regex I'm using in the fix it identical to PathResolver class:

'''
if (preg_match('/resource=(.+)$/', $originalUri, $matches)) {
'''

So that looks like it might not be in PathResolver ?

**Comment by lisachenko** [comment]
Unfortunately, you provide not so much details, so I can not help you right now. I need a reproduceable case with backtrace and values for methods.

**Comment by kbanman** [comment]
I'm running into this issue as well. For me, it runs fine on my virtual machine, but fails when running it on another machine, so it looks like it could be an environment issue.

**Comment by lisachenko** [comment]
@kbanman could you please add some details about environment where issue is appearing? 
- OS: `uname -svm`
- PHP version: `php -v`
- PHP extensions: `php -m`

Or maybe you can debug it on failing environment?

**Comment by lisachenko** [comment]
Ping.

**Comment by kbanman** [comment]
This error ended up being misleading for me. Just got into some odd state
with caching.

**Comment by lisachenko** [comment]
Yeah, invalid cache for production mode can result in this issue. So confirmed to be not a bug?

**Comment by kbanman** [comment]
For myself, yes.

**Comment by lisachenko** [comment]
@kbanman thank you for confirmation, I will wait for @markNZed response. Or close it after inactivity...

**Comment by crisp-github** [comment]
Hi Alexander, we just got a first release out yesterday. I've not enabled the logging sine we had the problems. if I'm lucky we'll get some time to investigate in the next month. It is on the list... But you could close this and I'll let you know if I can reproduce it.

**Comment by lisachenko** [comment]
@crisp-github ok, great ) Congrats with your release! I wish you less bugs and more profit!

Feel free to reopen this issue or create a new one if needed.

**Comment by itcreator** [comment]
It's now reproduced
Go\Instrument\Transformer\CachingTransformer:92:transform()

```
$lastModified  = filemtime($originalUri);
```

**Comment by lisachenko** [comment]
@itcreator could you provide more details? All previous messages don't contain any interesting parts to reproduce this issue myself...

**Comment by lisachenko** [comment]
Closed, because there were no details and reproducible cases. Reopen if needed.
