### ISSUE TITLE
Traits causing errors

### ISSUE THREAD

**Issue by markNZed** [goaop/framework#172]
Line 71 of TraitProxy.php 

$filledAdvices[] = $accessor->$advisorName;

But accessor can be null ?

I've added a conditional to test for $accessor - seems to avoid the error:

Trying to get property of non-object

**Comment by lisachenko** [comment]
I looked into the code, `$accessor` can't be null for normal flow...even this flow is not straightforward. However, there is an extra check for not empty `invocationClassMap`, I will remove it.

How you received a notice about "trying to get property of non-object"? Do you trying to intercept methods in traits? What is the version of PHP and version of goaop itself?

**Comment by lisachenko** [comment]
Ping!

**Comment by crisp-github** [comment]
We ar just using AOP for logging at the moment: @Around("within(PureSeo\Crisp**)")

We are sung the Bitnami stack PHP 5.4.32 

Running goaop through composer: "lisachenko/go-aop-php": "0.6.*@dev",

**Comment by lisachenko** [comment]
@crisp-github thank you, could you please put a breakpoint in TraitProxy to check if `$accessor` variable is empty and `self::$invocationClassMap` is empty or not?

**Comment by lisachenko** [comment]
@crisp-github please, attach also an output for `php -m` to list all installed extensions. I want to verify, that you don't have any extra modules enabled that can cause strange issues with stream filters and optimizators/opcode cachers.

**Comment by crisp-github** [comment]
[PHP Modules]
apc
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mcrypt
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]

**Comment by lisachenko** [comment]
ok, there aren't any extra extensions (goaop works normally with APC in debug and production mode). only `apc.canonicalize` can break it for debug mode.

What about my previous question and value of `self::$invocationClassMap` in the TraitProxy during debug?

**Comment by lisachenko** [comment]
Any news here? Or I can close this issue?

**Comment by lisachenko** [comment]
Bug confirmed and fixed in the master branch. Thank you for reporting!

**Comment by crisp-github** [comment]
Hi, sorry for my slow reply. We are in the middle of dev and I turned off the logging with Go AOP because  we just did not have time to debug AOP. I hope to turn it back on when our own code base stabilises a bit.

**Comment by lisachenko** [comment]
@crisp-github it's ok ) Good luck with development!
