### ISSUE TITLE
Getting a "File not processed yet" from the php-token-reflection library

### ISSUE THREAD

**Issue by xavier-cousin** [goaop/framework#187]
Hi, I'm getting this error on the new 0.5.0 (everything worked fine on 0.4.3)

PHP Fatal error:  Uncaught exception 'TokenReflection\Exception\BrokerException' with message 'File "/pathtofile/file1.php" was not processed yet.' in /vendor/andrewsville/php-token-reflection/TokenReflection/Broker/Backend/Memory.php on line 452

Trying to debug a bit, in the Memory.php class, I added some debug code to output what the filename looked for is and what the array keys are in the class' tokenStreams attribute.
What I found is the following:

/pathtofile/file1.php
Array
(
    [0] => /pathtofile/file1.php
)
/pathtofile/file3.php
Array
(
    [0] => /pathtofile/file2.php
    [1] => /pathtofile/file3.php
)
/pathtofile/file4.php
Array
(
    [0] => /pathtofile/file2.php
    [1] => /pathtofile/file3.php
    [2] => /pathtofile/file4.php
)
/pathtofile/file5.php
Array
(
    [0] => /pathtofile/file2.php
    [1] => /pathtofile/file3.php
    [2] => /pathtofile/file4.php
    [3] => /pathtofile/file5.php
)
/pathtofile/file1.php
Array
(
    [0] => /pathtofile/file2.php
    [1] => /pathtofile/file3.php
    [2] => /pathtofile/file4.php
    [3] => /pathtofile/file5.php
)

So it looks like the first time it looks for the file, it has everything it needs to work properly but when the second file is looked for, the Memory class' tokenStreams attribute does not contain the first file anymore like if it had been reset which does not happen for the following files until the first file is processed again at which point it is still not in the array which throws the Exception.

I there anything you can think of why this would happen on the new version that did not happen on the previous one?

Thanks

**Comment by lisachenko** [comment]
Hello, sorry for the delay, was at SymfonyCon conference in Mardid) 

I have a guess, that this bug can be related to the recursive class-loading analysis, that I do for classes to build an hierarchy. Cleaning of `tokenStreams` is needed to bypass memory overflows. But it works normally for me, even for complex hierarchy.

Can you give me a trace or reproducible test case?

**Comment by xavier-cousin** [comment]
No worries, We actually changed in the meantime the "includePaths" when we setup aop and restrained it to a much smaller folder where the only classes using aop are (we previously had as include path a huge folder with almost 900 classes so that was probably the source of the problem).

With that change on the include path, I can't reproduce the problem anymore so I don't think it's worth more investigating. Thanks for your help on it!

**Comment by lisachenko** [comment]
@xavier-cousin you are welcome!
