### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by blanchonvincent** [goaop/framework#19]
hi,

Go! look nice, but i have not found the unit tests. Where are the unit tests ?
Framework is stable ?

Thx.

**Comment by lisachenko** [comment]
Hello! Thanks for the issue )

Library is under development now, so it's not stable enough, however interfaces are stable. My first goal is to achieve the realization of AOP in pure PHP without runkit, evals, etc... Initially I did not believe that I'll be able to create this library, so tests haven't been added.

But now I want to cover it with unit tests and write the [documentation](https://github.com/lisachenko/go-aop-php/wiki) for it. Any help will be appreciated )

**Comment by blanchonvincent** [comment]
@lisachenko thx, i will help you when i have time.
Very nice work, congrats !

**Comment by lisachenko** [comment]
Relates to #12
