### ISSUE TITLE
Go AOP saves files as nobody user with low permissions

### ISSUE THREAD

**Issue by archer247** [goaop/framework#208]
@lisachenko Can you please add to every mkdir call  umask? so at least the file would have the permissions to be modified as we want, http://php.net/manual/en/function.umask.php, please we need that so then we can call to scripts to erase it or do something!

**Comment by lisachenko** [comment]
Hello, @archer247!

I think it isn't good idea to modify umask during the execution of `mkdir`. Reason is described in the manual:

> Avoid using this function (umask) in multithreaded webservers. It is better to change the file permissions with chmod() after creating the file. Using umask() can lead to unexpected behavior of concurrently running scripts and the webserver itself because they all use the same umask. 

It's only your responsibility to adjust umask in the php configuration or to put a call with `umask(xxx)` at your bootstrap file in case of you haven't access to the php.ini.

**Comment by archer247** [comment]
@lisachenko so youre saying to fix my problem i can either modify my php.ini file or boostrap file??

**Comment by lisachenko** [comment]
@archer247 I was wrong with php.ini, this should be configured for Apache/FPM. Or in bootstrap file, see [How to set default permissions for new files created with php](http://stackoverflow.com/questions/16672429/how-to-set-default-permissions-for-new-files-created-with-php) or [How do I set default umask in apache on debian?](http://serverfault.com/questions/383734/how-do-i-set-default-umask-in-apache-on-debian/384922#384922)

**Comment by lisachenko** [comment]
@archer247 master now contains #209 and there is special option for cache file mode now. See: https://github.com/lisachenko/go-aop-php/blob/master/src/Core/AspectKernel.php#L180

**Comment by archer247** [comment]
@lisachenko  Great! ill check it right away! I have to analyze  this code so i can use it properly, but it looks awesome!

**Comment by archer247** [comment]
@lisachenko and which values does cacheFileMode support?

**Comment by lisachenko** [comment]
@archer247 any valid for [chmod()](http://php.net/manual/en/function.chmod.php), preferably to use an octal form for declaring mode, for example, 0777, 0660, etc...

**Comment by dmachehin** [comment]
Not work: `'cacheFileMode' => 0777`
Part of files is not have read perms for "Others"

**Comment by lisachenko** [comment]
Should be solved by https://github.com/goaop/framework/commit/3079dcaef87e35aeac99946d7176838846a77e84
