### ISSUE TITLE
Replace non-supported Php-Token-Reflection

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#210]
Definitely framework should go away from Php-Token-Reflection library because it isn't supported now and doesn't contain important fixes for upcoming PHP5.6 and PHP7. 

Possible ways:
- Make a fork for Php-Token-Reflection and support it as a component for framework
- Switch to [ApiGen/ElementReflection](https://github.com/ApiGen/ElementReflection) which is developed now by @TomasVotruba as fork of Php-Token-Reflection
- Directly use [nikic/PHP-Parser](https://github.com/nikic/PHP-Parser) as a reliable AST parser.

I like the first approach as fast (because framework almost don't care about PHP expressions inside method body) and the last approach as reliable, but more slow.

**Comment by k-meister** [comment]
First way seems the cheapest to go by, giving immediate value (we can fix known issues easily) and keeping the possibility to implement any of the other two, if needed. Considering the risks, the first way seems the least error-prone, almost guaranteeing to keep Go behaviour as it is.

**Comment by lisachenko** [comment]
Thank you for your opinion! But if I chose the first way, it brings a lot of pain with detecting `include`/`require` constructions, as well, as `->getFileName()` for reflection class and magic `__DIR__`, `__FILE__` constants.

If I switch to the php-parser, It can be implemented as a reliable node visitor without an additional hacks like [this](https://github.com/lisachenko/go-aop-php/blob/master/src/Instrument/Transformer/MagicConstantTransformer.php#L77-L80).

But I'm not sure what will be performance lost for the cache generation, is it important for you? Or it doesn't matter?

**Comment by k-meister** [comment]
Didn't you resolve all that pain currently? :)
Well, it's a matter of vision, and you surely have a deeper insight in what would be better for your project to do a better job.

As for me, I'm incorporating aop into a big framework on a high-loaded project. So, it would be a matter of seconds for us to warm up caches (and there's a pre-load warmer-up shipped with Go), so it's not a concern for me to generate the cache quickly - it's more essential to make it work fast when caches are hot.

And, personally, second point that's important (in view of putting Go in production on a project with an old non-composer framework), I will probably have to make a good deal of twitches and patches to framework itself, so it's plain better for me to have just one fork (and of well-maintained library, Go), as in variants 1 and 3, than to have multiple forks, multiple pains and keeping track of version compatibility of them.

**Comment by lisachenko** [comment]
@k-meister I'm trying to create a library that emulates reflection with nikic/PHP-Parser (point number 3). Things looks good, I can even use some parts of code directly from PHP-Token-Refletion, adopting them for communication with parser library. I have a feeling, that state machine in the PHP-Parser can be very efficient, but some functionality can't be implemented quickly (for example, resolving values for constants, with magic __FILE__, class::static, __LINE__, expressions in PHP7), PHP-Parser just returns a valid nodes for that, but not the values.

I'll publish it when it will be ready to handle all the cases, required by Go! AOP engine.

**Comment by k-meister** [comment]
@lisachenko, okay then, looking forward for newer and more stable and powerful Go :)

I'll be trying to fire aop using my forks of Go and Php-token-reflection for now, see if there are other issues that should be accounted for

**Comment by lisachenko** [comment]
WIP: [goaop/parser-reflection](https://github.com/goaop/parser-reflection)

**Comment by lisachenko** [comment]
Just did it, resolved by #240.
