### ISSUE TITLE
Possible to use with sub-classes?

### ISSUE THREAD

**Issue by andreyvk** [goaop/framework#213]
Hi,

Is it possible to somehow add an aspect to a class and all its sub-classes? Say we have parent class A and B as its child. I'd like to add smth like this:

``` php
/**
* @Before("execution(public A+->*(*))")
*/
```

and, if B->method1() is executed, then it is also affected.

I know that there's a way do this with interfaces, but I am looking for this particular solution.

I am using Go AOP version 0.6.0.

**Comment by lisachenko** [comment]
Hello!

You can build this pointcut like this:

```
execution(public **->*(*)) && within(A+)
```

Here we describe the execution of public methods in all classes that sub-classes of `A` class.

**Comment by andreyvk** [comment]
Hi there,

It's not working very well and actually behaves strangely. Basically, I added the following pointcut expression into an **existing** aspect class (i.e. I created that aspect before and used it for testing):

```
@Before("execution(public **->*(*)) && within(app\common\controllers\CommonController+)")
```

None of the sub-classes seem to be hooked in, **except** for the one that was previously defined in the aspect. Basically, it's as if the pointcut is cached. I tried therefore clearing cache directory, but that did not help. 

I've also tried a simpler approach by creating a new class and changing pointcut expression to match only that class, but it still seems to be cached:

```
@Before("execution(public app\app_sample\controllers\TestController->*(*))")
```

Do u have any idea about what's happening?

**Comment by lisachenko** [comment]
I noticed your message in my incoming emails on this topic, but there is no message on github. So, is it ok now? Looks like you configured `debug=false` option for the kernel.

**Comment by andreyvk** [comment]
Im sorry, I posted my question before investigating all the options. I'll let u know :)

**Comment by andreyvk** [comment]
Hi,

Before moving onto trying your initial suggestion on subclasses, I am stuck with trying to make something else work. Basically I have an aspect with pointcut expression:

``` php
/**
 * @Before("execution(public app\app_sample\controllers\DefaultController->handle_*(*))")
 */
```

which does things properly with DefaultController. However, once I change this expression to 

``` php
/**
 * @Before("execution(public app\app_sample\controllers\TestController->handle_*(*))")
 */
```

DefaultController is no longer handled (as expected), but neither is TestController (not as expected). Do you have any idea why?

For that matter, the whole subclass pointcut didn't work as well and gave similar results. My `debug` is set to `true` for now as in the initial example and I didnt touch it since then. I do not get any errors or warnings from Go AOP as well.

**Comment by andreyvk** [comment]
Hi @lisachenko. Is there anything else you need to figure out what might've gone wrong?

**Comment by lisachenko** [comment]
Hi, sorry for the delay, was busy yesterday. 
From your message I can't found anything wrong with pointcuts, did you clear the cache by hand? Not sure, but this can help in rare conditions. Also, I want to ask, which config is used for `opcache` extension. Maybe, some files are outdated in the cache, hence the problem.

I tried to reproduce this case with `master` branch - everything is ok. So, I'm expect that this inheritance pointcut should work. 
However, could your open a file from `_proxies` directory in the cache, related to the `app\app_sample\controllers\TestController` and look at end, what do you see there?

**Comment by andreyvk** [comment]
Hi,

I never touched `opcache`. My installation is fresh so all of those settings are defaults.

I did clear cache by hand (basically went and `rm -rf *` in the directory). I've also done it just now and tried calling one of `TestController`'s handler methods. Nothing happened and cache dir remained empty. Then I triggered one of `DefaultController`'s handler methods and cache was generated. `DefaultController.php` is in the cache dir now alongside with it's parent controller class,
 alongside with it's parent controller class, but there's no `TestController.php`. Also, there's nothing at the end of the file (`_proxies/app/.../DefaultController.php`). Files looks "as is".

Here's my kernel config just in case:

``` php
$applicationAspectKernel = ApplicationAspectKernel::getInstance();
$applicationAspectKernel->init(array(
            'debug' => true, // Use 'false' for production mode
            // Cache directory
            'cacheDir' => ROOT_PATH . '/tmp', // Adjust this path if needed
            // Include paths restricts the directories where aspects should be applied, or empty for all source files
            'includePaths' => array(
                APP_PATH . '/controllers',
                COMMON_PATH . '/controllers',
                BASE_PATH . '/controllers'
            )
));
```

Should I, maybe, move to using master branch?

**Comment by lisachenko** [comment]
Very strange. From what I see, pointcut doesn't match your class (probably, you mistyped somewhere or write an incorrect namespace). Or this is really new bug :) 

So, let's check this from the beginning to the end one more time:
1. You have a class `DefaultController`, which is located in the `app\app_sample\controllers` namespace. Probably, in the file `APP_PATH . '/controllers/app/app_sample/controllers/DefaultController.php'`
2. `DefaultController` class has a public methods, called `handle_****()`, for example, `handle_request()`.
3. You have a class `TestController` in **the same** namespace and directory as `DefaultController` class.
4. `TestController` class **extends** `DefaultController` and probably _don't have_ any `handle_***()` methods defined explicitly, but only has them via inheritance from `DefaultController` class.
5. Check more general pointcut for this case: `execution(public **\controllers\*Controller->handle_*(*))`. Is anything changed or not?

**Comment by andreyvk** [comment]
1. Actually the path to the controller is: `APP_PATH . '/controllers/*Controller.php'`, where `APP_PATH`  is the path to the app itself. There's also `COMMON_PATH` and `BASE_PATH`, which point to common and base directories. So, there's also `COMMON_PATH . '/controllers/*Controller.php'` and `BASE_PATH . '/controllers/*Controller.php'`.
2. True
3. True
4. `TestController` and `DefaultController` now extend `ApplicationController` and they are all in the same namespace and directory. `TestController` does have a `handle_*` method which I was testing on and it did not work. I was also testing on a method inherited from it's parents and that didn't work either. If you like I can draw a class tree that I have here.
5. I tried the expression. Funny enough the expression selectively works on `DefaultController` and a bunch of others, but ignores `TestController` and a few more. It's just strange.

**Comment by lisachenko** [comment]
Well, nothing wrong...

Let's check, maybe someone is loaded your file before AOP, put a `debug_print_backtrace(); die;` into the beginning of `TestController.php` file. And show me the trace.

Also you can try to remove the cache and put a breakpoint into the `WeavingTransformer->processSingleClass()` method after `$advices = $this->adviceMatcher->getAdvicesForClass($class);` line. Then check that there is a call for `TestController` class here, but for some reason `$advices` variable is empty and class is skipped.

**Comment by andreyvk** [comment]
Here's the trace, when a `handle_GetTest` method is called in `TestController` (this method isnt inherited):

```
#0 app\app_sample\controllers\TestController->handle_GetTest(Array ()) called at [/home/ubuntu/shared/www/app/base/controllers/BaseApplication.php:389] 
#1 app\base\controllers\BaseApplication->loadController(Array ([name] => /test,[class] => \app\app_sample\controllers\TestController,[handlerName] => test,[handlerMethod] => handle_GetTest,[urlData] => Array ())) called at [/home/ubuntu/shared/www/app/base/controllers/BaseApplication.php:202] 
#2 app\base\controllers\BaseApplication->processRequest() called at [/home/ubuntu/shared/www/app/base/controllers/BaseApplication.php:57] 
#3 app\base\controllers\BaseApplication->start() called at [/home/ubuntu/shared/www/app/app_sample/index.php:14] 
```

I've also checked if `TestController` is somehow loaded before the autoloader, but that's not the case:

Here's a part of my autoload file which handles class loading:

``` php
if(strpos($file, '/controllers/') !== false) { //controllers are the only ones for now that need AOP
    error_log('WITH AOP: '.$file);
    require_once \Go\Instrument\Transformer\FilterInjectorTransformer::rewrite($file);
}
else {
    error_log('WITHOUT AOP: '.$file);
    require_once($file);
}
```

The error log output from the autoloader was:

```
WITH AOP: /home/ubuntu/shared/www/app/app_sample/controllers/Application.php
WITH AOP: /home/ubuntu/shared/www/app/base/controllers/BaseApplication.php
WITHOUT AOP: /home/ubuntu/shared/www/app/base/classes/Log.php
WITHOUT AOP: /home/ubuntu/shared/www/app/base/classes/BaseStaticClass.php
WITHOUT AOP: /home/ubuntu/shared/www/app/base/models/BaseModel.php
WITH AOP: /home/ubuntu/shared/www/app/app_sample/controllers/TestController.php
WITH AOP: /home/ubuntu/shared/www/app/app_sample/controllers/ApplicationController.php
WITH AOP: /home/ubuntu/shared/www/app/common/controllers/CommonController.php
WITH AOP: /home/ubuntu/shared/www/app/base/controllers/BaseController.php
WITHOUT AOP: /home/ubuntu/shared/www/app/app_sample/classes/aop/ApplicationAspectKernel.php
WITHOUT AOP: /home/ubuntu/shared/www/app/app_sample/classes/aop/aspects/SessionAspect.php
WITHOUT AOP: /home/ubuntu/shared/www/app/common/models/I18NModel.php
WITHOUT AOP: /home/ubuntu/shared/www/app/base/models/I18NModel.php
WITHOUT AOP: /home/ubuntu/shared/www/app/base/classes/Request.php
```

So all looks ok. I'll try to triple check the code again. 

Will also try the breakpoint suggestion in a bit.

**Comment by lisachenko** [comment]
Please, add the first line into the `TestController.php` with `debug_print_backtrace();die;` this will show the full trace, where this file was loaded from. This information can give us a little light on this issue. (not the trace of method call, that you provided in previous post)

**Comment by andreyvk** [comment]
Sorry for the wrong trace. Here's the update:

```
#0 require_once() called at [/home/ubuntu/shared/www/app/base/config/autoload.php:39] 
#1 __mi_9a16dea_autoload(app\app_sample\controllers\TestController) 
#2 spl_autoload_call(app\app_sample\controllers\TestController) 
#3 class_exists(\app\app_sample\controllers\TestController) called at [/home/ubuntu/shared/www/app/base/controllers/BaseApplication.php:320] 
#4 app\base\controllers\BaseApplication->resolveController(Array ([0] => test,[1] => test)) called at [/home/ubuntu/shared/www/app/base/controllers/BaseApplication.php:199] 
#5 app\base\controllers\BaseApplication->processRequest() called at [/home/ubuntu/shared/www/app/base/controllers/BaseApplication.php:57] 
#6 app\base\controllers\BaseApplication->start() called at [/home/ubuntu/shared/www/app/app_sample/index.php:14] 
```

Line 39 of autoload.php reads:

``` php
require_once \Go\Instrument\Transformer\FilterInjectorTransformer::rewrite($file);
```

Also, I can't really breakpoint things with my current setup, so I tried to just output something after the `$advices = $this->adviceMatcher->getAdvicesForClass($class);` line as you suggested. Nothing happened. So it's as if `TestController` is overlooked by the AOP.

**Comment by lisachenko** [comment]
Crazy puzzle... so, there is only one way now to find out, why it doesn't match this class - debug it. I don't want you to spend your time, but I'm not able to help you remotely (

Need to look into this code with debugger to check, why a regular expression of pointcut doesn't match this methods (it should).

And I want to put a line into the AOP kernel initialization to point `appDir` option directly to the  `/home/ubuntu/shared/www` or `/home/ubuntu/shared/www/app`. However, this shouldn't help at all because `DefaultController` works well with AOP. Just magic...

**Comment by andreyvk** [comment]
You'll have to walk me through on how to debug it. Where's the piece of code that does matching? 

And you are right, there's no point in setting the directory. It looks like it's working fine.

**Comment by lisachenko** [comment]
Ok, our target is `AdviceMatcher->getAdvicesForClass()` method. 
1. Clean the cache
2. Put a breakpoint in this method at line [120](https://github.com/lisachenko/go-aop-php/blob/master/src/Core/AdviceMatcher.php#L120) (`$pointcut = $advisor->getPointcut();`)
3. Skip all irrelevant classes until your `TestController` class is loaded (look at property `$class->name` in the `$class` variable or just add it into the watch list.
4. Try to step out next line with check of class name. If it fails and leave this condition block - then make a stop and restart a debug, and then we will debug class matching further.
5. Otherwise, we will be at line 122 of `AdviceMatcher` and we should step into the `getAdvicesFromAdvisor()` method.

**Comment by andreyvk** [comment]
It looks like `AdviceMatcher->getAdvicesForClass()` never gets fired for **any class**, when `TestController->handle_*` is called. So, for instance, when `DefaultController->handle_*` is called, then a bunch of other classes are matched. Im picking up the following log, which i added after line 120:

```
[Mon Apr 06 02:22:26.515780 2015] [:error] [pid 8128] [client 192.168.1.100:51065] app\\base\\controllers\\BaseController
[Mon Apr 06 02:22:26.517555 2015] [:error] [pid 8128] [client 192.168.1.100:51065] app\\common\\controllers\\CommonController
[Mon Apr 06 02:22:26.517998 2015] [:error] [pid 8128] [client 192.168.1.100:51065] app\\app_sample\\controllers\\ApplicationController
[Mon Apr 06 02:22:26.524444 2015] [:error] [pid 8128] [client 192.168.1.100:51065] app\\app_sample\\controllers\\DefaultController
[Mon Apr 06 02:22:26.532053 2015] [:error] [pid 8128] [client 192.168.1.100:51065] AOP WORKED!!!!!!!!!!!!!!!! - app\\app_sample\\controllers\\DefaultController - handle_GetTabs
```

But when Im calling `TestController`, my log output is blank. I've also created another controller and called it `MyOwnController.php` (same namespace as `TestController` of course), but results are the same. Can we go somewhere earlier in the Go AOP code and see what is being picked up there?

**Comment by andreyvk** [comment]
I got to the point of debugging `SourceTransformingLoader->filter()`. During a call to `TestController`'s methods nothing was happening there. It's as if `TestController` does not exist and is not being matched at all. Is there any place else I can look into?

**Comment by lisachenko** [comment]
Ok, maybe we have an error in the tokenization process...

Let's check this fact: open a `WeavingTransformer` class and put a breakpoint at line 73, after catch section: 

```
        } catch (FileProcessingException $e) {
            CleanableMemory::leaveProcessing();

            return;
        }
```

**Comment by lisachenko** [comment]
This really can be the matter, because I decided to silently ignore this exceptions to prevent normal execution of this process ))

**Comment by andreyvk** [comment]
It's not gonna work because `transform()` is never even called for `TestController`. It just doesn't get to that point. Nevertheless, I have tried to output some log in the `catch` block and (alas!) nothing came out :) Im really puzzled.

Btw, the `catch` block is on line 92 in my copy of `WeavingTransformer`.

**Comment by lisachenko** [comment]
Hello! ) Any news here? Or you give up this magic?

Was method `FilterInjectorTransformer::rewrite()` called for the `TestController`? I have a feeling, that this file is loaded directly with `include|require` expressions, not through the AOP loader.

**Comment by andreyvk** [comment]
Hi there :)

Cant give up on this! Need AOP badly, but it doesn't work yet. I was a bit busy with other stuff today though, but Im gonna come back to debugging this soon.

From the logs that I've sent earlier, you can see that `TestController` is loaded with the help of `FilterInjectorTransformer`.

```
...
WITH AOP: /home/ubuntu/shared/www/app/app_sample/controllers/TestController.php
...
```

But from overall behavior it does look like as if `TestController` is loaded outside of AOP loader scope... I've just realized I should be debugging `FilterInjectorTransformer::rewrite()`. Maybe answer lies there.

I'll keep you posted.

**Comment by lisachenko** [comment]
Thanks, will wait for further information from your! Hope that cause for this issue will be located.

**Comment by andreyvk** [comment]
Hooray! The issue is resolved. I was my mistake all along. Although I put AOP kernel initialization code before the controller was loaded, for some reason some controllers were affected and some weren't. I dont know why and I frankly speaking dont want to spend more time on this. So I moved kernel initialization code even further 'up', before request processing even took place and, voila, everything's working well.

Thank you very much @lisachenko for your support on this one! Hope I'd never have to come back with anything like that to you ever again :)

**Comment by lisachenko** [comment]
Great! :+1:

I'm glad to hear, that you managed to make it working ) I know, that configuration can be cumbersome, but this is due to the nature of PHP engine and tricks. Hope, next version 1.0.0 will be much more transparent and easier to use.

I wish you good luck! If you'll have any questions, just open an issue here and I'll do my best to help you.
