### ISSUE TITLE
Conceptual: Generic or specific advices?

### ISSUE THREAD

**Issue by ghost** [goaop/framework#215]
Is a good practise to define generic advices regarding to performance and maintainabilty?

**Comment by lisachenko** [comment]
This question is not clear enough. Could you please elaborate more about what your want to clarify? What do you mean by "generic advices"?

Performance of framework is quite good for production mode (`'debug' => false`) and enabled opcache or APC with `apc.stat=off`. So you shouldn't worry about this. All annotations and runtimes checks are performed only once when cache is generated, then this code just executing.

Regarding maintainability, I think that clear aspect class with simple advices is easy to maintain. And if you use AOP with markers (like interfaces for class, or annotations for method/property/class) then you can keep your code clean as well as readable code of aspects.

**Comment by ghost** [comment]
By generic advices I mean hooking in all e.g. public methods to log exceptions. By specific I mean hooking into e.g. methodThatThrowsExecption(). But yeah you just answered my question. The markers are what I was looking for as it keeps the freedom of renaming method and class identifiers. 

Thanks a lot :)

**Comment by lisachenko** [comment]
Welcome )
