### ISSUE TITLE
1.0.0 Alpha Tag

### ISSUE THREAD

**Issue by jg-development** [goaop/framework#223]
Hi,
I know it sounds weird, but is it possible to tag a alpha version 1.0.0.
This is much better than a dev-master dependency in composer.json.
I don't want to fork a repo for a tag ;-)

Greetings Jan

**Comment by lisachenko** [comment]
Yes, alpha-tag is possible ) Done! But I want to mention, that lisachenko/go-aop-php package will be secondary from the version 1.0.0. 

I want to move it to the organization, so it will be called https://github.com/goaop/framework with package name `goaop/framework`.

**Comment by jg-development** [comment]
Thanks
