### ISSUE TITLE
Performance PHP Laravel

### ISSUE THREAD

**Issue by newtonianb** [goaop/framework#225]
I just got this setup on Laravel 5 and using 'DebugBar' plugin I see right the response time and after setting go-aop-php (and without using any aspects on any methods) my response time (in debug mode) goes from 80-180ms to 500-1000ms seconds per request.

That's quite a bit performance hit, is this normal? I only told it to include 4 paths that don't have more than 15 files each.

**Comment by lisachenko** [comment]
Hello, probable this is just misconfiguration of your aspect kernel, or just a first run, when the cache is warming. 

Small snaphsot of your kernel initialization can be helpful for me to give your a correct answer. You can also try a 1.0.0-alpha version of framework that should be more faster and stable.

**Comment by newtonianb** [comment]
Thanks, I ran some more tests so when I disable debug naturally its alot more responsive. Below are my latest tests

**NO GO-AOP / NO DEBUG** average =`184 ms`
188 ms
183 ms
183 ms
181 ms
186 ms
best response time achieved on fast refresh: `42 ms`

**NO GO-AOP / DEBUG** = `188.4 ms`
197 ms
189 ms
186 ms
188 ms
182 ms
best response time achieved on fast refresh: `44 ms`

**GO-AOP / NO DEBUG** average = `256 ms`
202 ms
274 ms
273 ms
263 ms
271 ms
best response time achieved on fast refresh: `97 ms`

**GO-AOP / DEBUG** average = `537 ms`
568 ms
535 ms
529 ms
538 ms
518 ms
best response time achieved on fast refresh: `333 ms`

I don't understand why sometimes it responds so much faster if I do fast repeat refresh, in the best case I can get 40 ms with no go-aop and no debug! But if between refresh I wait 5 seconds or more then the time is never below the average (this seems nothing to do with go-aop since it happens in either case).

I have a very simple configuration

```
        $applicationAspectKernel = ApplicationAspectKernel::getInstance();

        $applicationAspectKernel->init([
            'cacheDir' => storage_path('aop'),
            'debug' => true
        ]);
```

I put this in laravel 5 in app/Providers/AppServiceProvider.php inside the boot() method.
To run these tests I had a dummy method it is one line running rand().

**Comment by newtonianb** [comment]
Also I tried to setup the alpha but could not get passed the install stage.
I got this error at the end 

```
$ composer require 'lisachenko/go-aop-php:1.0.0-alpha.1'
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing lisachenko/go-aop-php (0.6.0)
  - Installing lisachenko/go-aop-php (1.0.0-alpha.1)
    Downloading: 100%

Writing lock file
Generating autoload files
Script php artisan clear-compiled handling the post-update-cmd event returned with an error



  [RuntimeException]
  Error Output:

```

**Comment by lisachenko** [comment]
According to your benchmark, AOP in production mode adds about 80ms, it's strange. Expected value is something like 20ms (this is AOP initialization time plus several extra calls to advices). There will be penalty for file checks, so it's important to have an enabled `opcache` extension for production mode with disabled filetime checks, this will boost the performance.

Additional questions:
Is your pointcut affects a lot of methods in your application or just several? Is intercepted method executed only once during the request or it's executed many times?

**Comment by lisachenko** [comment]
Ping @newtonianb

**Comment by newtonianb** [comment]
Hi lisachenko unfortunately we decided last minute that performance was currently of higher importance to us than code quality so we have temporarily halted deployment of goaop so we could use HHVM. We will definitely use go aop on our sister server that has less loads however currently i have not been able to run more test. Should we close it until I get more data?

To answer your questions the usage of aop was quite minimal at that stage. But the intercepted method was executed many times since we yes it for caching. The number of methods affected was small around 5 or so using the caching annotation.

**Comment by lisachenko** [comment]
Ok, thank you for the information ) I wish you good luck with your projects. Unfortunately, goaop is not working on HHVM now, but I like the fact, that PHP7 has almost the same speed as HHVM and can run goaop framework without any limitations from the core.

It can be interesting to debug, what was the reason for performance penalty in your configuration, looks like misconfiguration or some issues with class autoloading (it's possible in some rare cases).

I think, that we can close this issue now, feel free to reopen it when needed.

**Comment by newtonianb** [comment]
Ah this I great to hear looking forward to it because goaop is quite an irreplaceable feature we would love to have it.
