### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by neeravbm** [goaop/framework#228]
@lisachenko I believe I might be able to use this framework for eliminating redundant test assertions but am not sure how to implement it so want your advice. Here is how the current code works:

`\RedTest_TestCase_Framework` extends `\PHPUnit_TestCase_Framework` with some default methods. For testing the application, users will need to extends `\RedTest_TestCase_Framework`. Currently here is how a very simple test is implemented:

```
$articleForm = new ArticleForm();
$this->assertTrue($articleForm->isSuccess(), $articleForm->getErrors());

list($success, $fields, $msg) = $articleForm->fillRandomValues();
$this->assertTrue($success, $msg);

list($success, $articleObject, $msg) = $articleForm->submit();
$this->assertTrue($success, $msg);

list($success, $msg) = $articleObject->checkValues($fields);
$this->assertTrue($success, $msg);`
```

I would like to convert the same to the following with assertions happening in the background automatically:

```
$articleForm = new ArticleForm();
$fields = $articleForm->fillRandomValues();
$articleObject = $articleForm->submit();
$articleObject->checkValues($fields);
```

Here is what I am thinking. Using your framework, I should be able to use Around invocation to first call the appropriate function and then check whether `$success` is `TRUE` or not. If it is, then just return `$var`. If it is not, then make the test fail. In other words, here is how it will look:

```
function aroundMethodExecution(MethodInvocation $invocation) {
  list($success, $var, $msg) = $invocation->proceed();
  // This is where it becomes problematic.
  // I want to implement the following here:
  if (method_exists($myTest, 'assertTrue') {
    $myTest->assertTrue($success, $msg);
    return $var;
  }
  return array($success, $var, $msg);
}        
```

I have two questions:

1) Is this an appropriate use of your framework? If not, what would you recommend?
2) If yes, then how will I get `$myTest` class in `aroundMethodExecution()` function?

Thank you!

**Comment by lisachenko** [comment]
Ok, looks like the `AspectMock` framework can give your a working solution (it's based on top of goaop).

However, I don't recommend you to use AOP techniques for optimizing such small parts of code, especially for testing, as this can lead to worse readability and bad maintenance of tests.

You can also try to simplify your tests code by using just `Test Spy` (http://css.dzone.com/books/practical-php-testing/practical-php-testing-patterns-38) pattern an put all logic for checking into your methods, instead of repeating them in every test.

**Comment by lisachenko** [comment]
Ok, looks like this issue can be closed as well. 

I'm happy that you can chose now the right way for making your code cleaner and transparent. Feel free to ask me anything if needed.
