### ISSUE TITLE
"this" Pointcut

### ISSUE THREAD

**Issue by neeravbm** [goaop/framework#229]
It seems "AspectJ" has "this" pointcut which can filter join points based on the class from where the method is called. I tried the GO AOP framework and it seems that "this" point cut is not implemented. Is that correct? Is there a plan to implement it in near future?

**Comment by lisachenko** [comment]
Hello, sorry for the delay, was on vacation )

You are right, that `this` pointcut type is not supported by goaop framework. However, I can think about it, if you really needed it. Probably, a little example with `this` pointcut related to the php source code can be the best way.

**Comment by neeravbm** [comment]
Based on your answer to issue #228 I have decided not to use this framework so I will not require `this` pointcut. Thanks for your help! :)

**Comment by lisachenko** [comment]
Ok, you are welcome )
