### ISSUE TITLE
GO AOP with Codeigniter

### ISSUE THREAD

**Issue by johnlhon21** [goaop/framework#231]
How to apply GO AOP in Codeigniter 2 ..Is there someone else who already been tried to?..

**Comment by lisachenko** [comment]
Hello!

Looks like there is no any bridges for now, applying goaop shouldn't be the issue if composer is used in the CI2. Just require a framework and configure the kernel

**Comment by johnlhon21** [comment]
Do you have any steps on how to intrgrate it with CI?..I saw all of the examples of working GOAOP but I can't find one working it in CI.

**Comment by lisachenko** [comment]
Unfortunately, I can't help you with CI2 and goaop integration because of lack of free time. You can look into existing bridges to have an example of "howto".
