### ISSUE TITLE
Pointcut to base class

### ISSUE THREAD

**Issue by danslo** [goaop/framework#233]
Just doing some experiments, if this is a stupid question please let me know.

Is there a way to specify a pointcut that not only matches a base class, but also any child classes that extend from it - basically an instanceof check? I feel I have to be way too specific in what I'm matching.

edit:
On further investigation, this already works for methods that only exist in the base class, but if you define a method in child class it will not match for something like `execution(public BaseClass->*(*))`.

**Comment by lisachenko** [comment]
Hello, @danslo!

You need a `within(Some\ClassOrInterface+) && execution(public **->*(*))` pointcut. First part is matching any class, that extends or implements `Some\ClassOrInterface` and second part is just restrict pointuct only to the public methods execution.

**Comment by danslo** [comment]
That makes sense, thank you.
