### ISSUE TITLE
Cache bug (poor performance if used cacheDir)

### ISSUE THREAD

**Issue by dmachehin** [goaop/framework#235]
I used simple (example) for test speed... but if i used cache is get very poor perfomance.

Without cache (delete cache dir):
`first name = John
last name = Smith
Ttl is: 10
Take 0.071ms to call method AuthApp\Person:setFirstName
first name = Jim
last name = Smith`

With cache (first, second, 3,.... run... after delete cache dir)
`first name = John
last name = Smith
Ttl is: 10
Take 1.149ms to call method AuthApp\Person:setFirstName
first name = Jim
last name = Smith`

PHP Version 5.6.10

**Comment by lisachenko** [comment]
Hello! Technically, there shouldn't be any difference between timings for execution of method, it's a constant time for invocation. Moreover, production environment typically use opcache with disabled file checks, so all code is executed from memory directly.

Source code for method invocation doesn't depend on presence of cache directory, so I think that your measurement was not correct, could you please recheck this one more time?

I've just tested your example and have an equal timing for both cases.
