### ISSUE TITLE
Overriding \DateTime object ?

### ISSUE THREAD

**Issue by gmorel** [goaop/framework#238]
Hi

First of all,  thanks for this amazing work. Your framework looks very promising.

We are trying to use GO-AOP in order to allow us [injecting Time at runtime](https://github.com/rezzza/TimeTraveler/pull/22).

Aim being to be able to change the PHP time during our test suits (Unit and Functional). Consequently allowing us to reflect a real use case involving time (booking concurrency, time interval, time travelling, etc..).

For this we need to be able to override native PHP functions behaviour such as `time()`. And to override native PHP objects such as `\DateTime`.

The former is working [very well](http://go.aopphp.com/blog/2013/08/24/intercepting-execution-of-system-functions-in-php/). However we can't manage to override `\DateTime`.

We might are doing it wrong. But first is that possible to intercept `\DateTime` ? 

Keep up the good work !

**Comment by lisachenko** [comment]
Hello, thank you for your interest in #goaop framework. I'm checked your issue on github and have a bad news for your: internal classes can't be intercepted in the code (right now). 
Reason is very simple: class is already exists in the memory and it isn't possible to replace it with proxied class.

However, there were some thoughts, how to make this possible:
- Analyse `use DateTime` strings and transform them into `use DateTime__Aop_Proxied as DateTime`
- Analyse the source code of file and replace all FQN `DateTime` to the `DateTime__Aop_Proxied`.

This is require a lot of code scanning and code transformation, but theoretically it can be implemented...

**Comment by adri** [comment]
At php-vcr we [transform `\SoapClient`](https://github.com/php-vcr/php-vcr/blob/master/src/VCR/CodeTransform/SoapCodeTransform.php) like @lisachenko described using code transformation. It is a [stream wrapper](https://github.com/php-vcr/php-vcr/blob/master/src/VCR/Util/StreamProcessor.php#L76) and [stream filter](https://github.com/php-vcr/php-vcr/blob/master/src/VCR/CodeTransform/AbstractCodeTransform.php#L29). Every PHP file that is included (and not blacklisted) will be running through this code transformer.

The idea is taken from [patchwork](http://antecedent.github.io/patchwork/), specifically [this bit](https://github.com/antecedent/patchwork/blob/master/src/Preprocessor/Stream.php).

Could this technique be used in go-aop?

**Comment by lisachenko** [comment]
@adri, yes sure, just implement custom [SourceTransformer](https://github.com/goaop/framework/blob/master/src/Instrument/Transformer/SourceTransformer.php) class and register it in the kernel via [AspectKernel::registerTransformers() method](https://github.com/goaop/framework/blob/master/src/Core/AspectKernel.php#L242) in the concrete kernel implementation

**Comment by adri** [comment]
Sweet, thanks @lisachenko. So that could be something similar to the [MagicConstantTransformer](https://github.com/goaop/framework/blob/master/src/Instrument/Transformer/MagicConstantTransformer.php), but then using regular expressions like in [SoapCodeTransform](https://github.com/php-vcr/php-vcr/blob/master/src/VCR/CodeTransform/SoapCodeTransform.php). What do you think, @gmorel?

**Comment by gmorel** [comment]
Thanks for your replies.

We might have some issues with Doctrine not liking `DateTime__Aop_Proxied` class name.

But, let's try your idea @adri

**Comment by lisachenko** [comment]
@gmorel what is the current state of this issue? Should I keep it open?

**Comment by gmorel** [comment]
Unfortunately I didn't manage to get something satisfying regarding our constraints. 
So I dropped it, sorry.

You can close the issue.

Keep up the good work !

**Comment by lisachenko** [comment]
Ok, thank you for the response, hope that I will be able to implement this feature someday...
