### ISSUE TITLE
[Question] Debug mode purpose

### ISSUE THREAD

**Issue by andreyvk** [goaop/framework#241]
Hi @lisachenko,

What does actually `debug` flag do in the aspect kernel configuration? My main concern is: will AOP proxies be still generated on demand if i set it to `false` ?

**Comment by lisachenko** [comment]
Hello!

`debug` flag influences on many things, related to the performance and debugging. Here are the full list of changes, affecting by this flag:
1. Most important one is when `debug` is set to `true`, you can still put a breakpoints in your original classes and files, they will work for you. This gives natural control over debugging of methods and aspects.
2. Next one feature is checking of file modification time. In the debug mode kernel rechecks every file and every aspect for every request, so you can easily change your class or an aspect and in the debug mode AOP proxies will be recreated every time when original file is changed. For `debug` equals to `false`, proxies will be created on demand, but only once, no filemtime checks in runtime.
3. Opcache-friendly mode. With `debug` equals to the `false`, kernel returns a paths for files that effectively cached by opcache, so all transformed files will be served directly from the opcache, allowing nice performance for production mode.

**Comment by andreyvk** [comment]
@lisachenko So, as i understand, it would always be nice to clear my aop/ dir after updating my classes and then safely go with `debug=false`. This is great! Thanks for the update ))

**Comment by lisachenko** [comment]
@andreyvk you are welcome!
