### ISSUE TITLE
[Insight] Deprecated class usage found - in src/Core/GoAspectContainer.php, line 91

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#245]
**[in src/Core/GoAspectContainer.php, line 91](https://github.com/goaop/framework/blob/6c875ffcb4043ccb3f92d384c5e8bc1a21fd5b27/src/Core/GoAspectContainer.php#L91)**

> The `Doctrine\Common\Annotations\FileCacheReader` class has been deprecated in Doctrine Annotations 1.2.3. Use the `Doctrine\Common\Annotations\CachedReader` class instead.

``` php

        $this->share('aspect.annotation.reader', function (Container $container) {
            $options = $container->get('kernel.options');
            $reader  = new AnnotationReader();
            if (!empty($options['cacheDir'])) {
                $reader  = new FileCacheReader(
                    $reader,
                    $options['cacheDir'] . DIRECTORY_SEPARATOR . '_annotations' . DIRECTORY_SEPARATOR,
                    $options['debug']
                );
            }
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/5998393e-29ea-48f8-8e7e-b19e86daa2db/analyses/72)_

**Comment by lisachenko** [comment]
This issue now results in bug with read-only filesystems and attempts to access annotations, see #358

**Comment by TheCelavi** [comment]
Fixed in https://github.com/goaop/framework/pull/359.
