### ISSUE TITLE
1.0.1 - something has gone terribly wrong

### ISSUE THREAD

**Issue by infabo** [goaop/framework#259]
I have updated from 1.0.0 to 1.0.1 and now I recognized a huge performance drop.
Seems like something got terribly slow since 1.0.0 (caching?).
I cannot say what it is - sry.

**Comment by lisachenko** [comment]
This is probably related to https://github.com/danslo/Danslo_Aop/issues/1

**Comment by lisachenko** [comment]
Copy of my response from https://github.com/danslo/Danslo_Aop/issues/1#issuecomment-192228712

> Hello, It's very strange, actually 1.0.0..1.0.1 of goaop/framework doesn't contain any significant changes. There are many changes for 2.x-dev branch that can slow down the first analysis of code (due to the switch to nikic/PHP-Parser library), but there are no stable releases for that.
> 
> If var/cache/aop/_transformation.cache is updated every time, then something go wrong in initialization/configuration of AOP and kernel tries to process several files one more time instead of using just cached version of source code. Could you please, put a breakpoint in the \Go\Instrument\ClassLoading\CachePathManager::flushCacheState method and dump the variable $this->newCacheState (please skip a first request and show the result for second page refresh)

**Comment by lisachenko** [comment]
@danslo researched this issue in https://github.com/danslo/Danslo_Aop/issues/1#issuecomment-193295628. So this should be fixed.

**Comment by lisachenko** [comment]
Fixed in #260

**Comment by lisachenko** [comment]
Released patch 1.0.2
