### ISSUE TITLE
Lazy method jointpoint injection?

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [goaop/framework#265]
I see that when Go! AOP (1.0.2) generates class proxies, it uses `\Go\Proxy\ClassProxy::injectJoinPoints` at the end of proxy files. Wouldn't it be better from the point of performance to inject the points lazily?
I mean that Go! AOP could generate proxy methods something like this:

``` php
public function postInvitationInfo(\SessionContext $sessionContext, array $invitations)
{
    if (!isset(self::$__joinPoints['method:postInvitationInfo'])) {
        $advices = [
            'method' => [
               0 => 'advisor.Aspects\\StopwatchAspect->aroundStopwatchable',
               1 => 'advisor.Aspects\\ApiLoggingAspect->aroundLogged',
            ]
        ];
        $jointPoint = static::wrapWithJoinPoint(
            $advices,
            "... static parent class name without using reflections ..."
        );
        self::$__joinPoints['method:postInvitationInfo'] = $jointPoint;
    }
    return self::$__joinPoints['method:postInvitationInfo']->__invoke($this, [$sessionContext, $invitations]);
}
```

Do you think this could be useful, especially in big projects?

PS: Do you have any idea how to benchmark Go! AOP?

**Comment by lisachenko** [comment]
Hello, thank you for choosing `goaop/framework`!

Your proposed variant of lazy joinpoints injection actually can be worse from the performance point of view for the methods that executed many times. I want each method to contain only direct method invocation to reduce the size of opcodes, needed to perform the invocation of method. If method is executed many times, then each call will include extra-time for checking `isset()`. Of course, this check is very efficient and fast, but it's still a runtime check, that will decrease speed a little bit.

One more reason to keep all things in one global injection - special kind of joinpoints, such as `staticinitialization`, which is invoked after the class is loaded into the memory, or property joinpoints `get`/`set` that intercept an execution to object fields. For that joinpoints we couldn't use lazy scheme.

Actually, I'm using your scheme for preparing lazy initialization of joinpoints for traits and functions, just try to intercept methods from the trait and look at generated trait proxy class.

**Comment by lisachenko** [comment]
One more reason, not to keep logic in the each methods: easy debugging, because code of each method is clear and doesn't contain any spaghetti code.

Less code == less opcodes  == better L1 CPU cache usage == faster execution

**Comment by AlexeyKupershtokh** [comment]
That's why I definitely think that benchmarks are needed. Without them everyone thinks of different parts as of bottlenecks. I'm not an exclusion: I don't think that either `isset` or code volume are very significant :)

Regarding the code volume - it can be reduced with something like the original `injectJoinPoints` method. Not a big deal.

``` php
public function postInvitationInfo(\SessionContext $sessionContext, array $invitations)
{
    if (!isset(self::$__joinPoints['method:postInvitationInfo'])) {
        self::$__joinPoints['method:postInvitationInfo'] = \Go\Proxy\ClassProxy::createJoinPoint([
           0 => 'advisor.Aspects\\StopwatchAspect->aroundStopwatchable',
           1 => 'advisor.Aspects\\ApiLoggingAspect->aroundLogged',
        ]);
    }
    return self::$__joinPoints['method:postInvitationInfo']->__invoke($this, [$sessionContext, $invitations]);
}
```

What about `staticinitialization` - it can be still handled "traditionally" if it does present.

**Comment by AlexeyKupershtokh** [comment]
So I have to return to my "PS:".
Could you think out some examples that could fit benchmarking purposes. E.g. how many classes do we need? How many classes/methods should be covered by pointcuts? What functionality do you expect from aspects? How many aspect runs should be during an average request?

**Comment by lisachenko** [comment]
Generally if we talk about real-live examples, your system will have several aspects (from 1 to 10). Standard joinpoints for caching, logging, transaction control and authorization can cover up to 50% of top-level methods in your application. But all of this top-level methods typically called only once per request.

This means, that each web request will hit only several joinpoints for top-level methods. Overhead for using AOP in your application can be calculated as following:
- AOP bootstrap, takes 5-10ms for PHP7 and 5-20ms for PHP5.x
- Joinpoints injection, once per class - 1-2ms
- Overhead for each method invocation with joinpoints < 1ms

You can notice, there aren't any runtime checks here, code is cached with AOP and just used, allowing for small extra-resource usage.

So, for a big project in AOP production mode, fine-tuned opcache without filemtime checks I'm expect only 5-50ms of extra timing, depending of advice number and joinpoints. If combine switching to AOP with moving from 5.6 to PHP7, you won't see any difference in production, but will get a nice tool to control all cross-cutting concerns in your application.

**Comment by lisachenko** [comment]
I can share a several links with blackfire.io comparison (old ones on heroku)

Caching without AOP (emulates 100ms method call): https://blackfire.io/profiles/57ec1530-098d-483f-829c-b03e7773eed5/graph

Caching with AOP: https://blackfire.io/profiles/5ef05d5e-0ebc-4850-a818-8d8ad5442809/graph

Delta: https://blackfire.io/profiles/compare/53b5b6c2-fd2f-4c03-9d8c-17dd13aecac6/graph

**Comment by AlexeyKupershtokh** [comment]
JFYI I've started dirty experimenting with the described optimization here:
https://github.com/AlexeyKupershtokh/goaop-benchmark
https://github.com/AlexeyKupershtokh/framework/tree/issue-265
It's in a very early stage but If you want to play with this too, git checkout the benchmark, optionally remove sudo from clear.sh, run clear.sh, then hit index.php via web-server.

The results I've got so far aren't impressive at all.

PS: it seems that Go! AOP framework doesn't work with the LazyApcClassLoader I tried to use. I'll post some details on this later.

**Comment by lisachenko** [comment]
> The results I've got so far aren't impressive at all.

Is this for your implementation, or for original one? It would be nice to publish a gist with timing results:
- Time to load code without AOP (baseline)
- Time to load code with AOP and no aspects (pure initialization delay, should be const)
- Time to load classes without AOP (this should be a hard to extract time, need to measure delay only for the first call to `new SomeAdvisedClass()`). This metric will be a baseline for class initialization delay
- Time to load classes with AOP and no advices with hot cache (again, only the first call to `new SomeAdvisedClass()`). This will show the overhead, added by `AopComposerLoader` for loading classes.
- Time to execute a method that accepts a number of ms to sleep (increment for each run from 1ms to 101ms with 10ms step) and then just sleeps. Try to run for many iterations to gather reliable metrics. 
- Previous method, but add a call to a method with empty body (imagine, that we put all our advice logic into the method body)
- Same method, but with applied empty advice body. Subtract previous timing to get a raw delta for calling an advice.

**Comment by lisachenko** [comment]
One more advice: do not use APC for class-loading, starting from PHP5.5 and opcache. This can bring serious issues with APC memory fragmentation, slow class loading and even 502 on a high load. Use composer+opcache+disable filemtime checks.

**Comment by lisachenko** [comment]
@AlexeyKupershtokh any news on this?

**Comment by lisachenko** [comment]
No results, closed by inactivity
