### ISSUE TITLE
Support type hint and return type hint for php 7?

### ISSUE THREAD

**Issue by Shahelm** [goaop/framework#267]
PHP Fatal error:  Uncaught exception 'TokenReflection\Exception\ParseException' with message 'Unexpected token found.' in /**/vendor/andrewsville/php-token-reflection/TokenReflection/ReflectionFunctionBase.php on line 435
Thrown when working with file "/**/AbstractWriterType.php" token stream.
The cause of the exception was the : token (line 176) in following part of **\AbstractWriterType::getHeaders() source code:

 173:     /**
 174:      \* @return array
 175:      */
*176:     public static function getHeaders(): array
 177:     {
 178:         return static::$headers;
 179:     }

**Comment by lisachenko** [comment]
Hello, versions 1.x of framework don't support PHP5.6 and PHP7 features. Please, switch to the 2.0alpha (dev-master)

**Comment by Shahelm** [comment]
Thanks, I'll try.
