### ISSUE TITLE
If any predictions at the expense of stable 2.0?

### ISSUE THREAD

**Issue by Shahelm** [goaop/framework#269]
Would you recommend 2.0.0-alpha.1 for production?

**Comment by lisachenko** [comment]
Hi, core of framework is stable enough, so it should work on 1.x and 2.x branches, but 2.x branch contains new reflection engine, which can be slower during cache warming. You can test 2.0.0-alpha.1tag somewhere and if everything is ok, then you can push it to production.

So, I'm expecting that everything will be ok.

**Comment by Shahelm** [comment]
Thank you!
