### ISSUE TITLE
Changing the type of exception in AfterThrowing

### ISSUE THREAD

**Issue by Shahelm** [goaop/framework#270]
Why with AfterThrowing not possible to change the type of exception?

**Comment by lisachenko** [comment]
Hi, this join point was developed to catch an exceptions, but not to change them. So, if you need to wrap an exception into another one, then use `Around` type of advice, it will give you full control over the method invocation.

Advice should look like this:

``` php
try {
    $result = $joinpoint->proceed();
} catch (\Exception $e) {
    throw new MySpecificException();
}

return $result;
```

**Comment by Shahelm** [comment]
I understand, but in Spring this type Aspect lets you change the type of exception.

**Comment by lisachenko** [comment]
Can you give me a case where this is needed for PHP? Java is strictly typed language, so try..catching exceptions and changing exception types here is logical. But for PHP I haven't see a valid reason to do this, and `Around` type can solve this perfectly.

**Comment by Shahelm** [comment]
In the case of external dependency, I would like to wrap an exception to one of their own.
It seemed to me that AfterThrowing designed specifically for this.

```

try {
    $externalDependency->execute();
} catch (\Exception $e) {
    throw new MyException($e->getMessage(), $e->getCode(), $e);
}

```

**Comment by lisachenko** [comment]
I think this case is covered with Around type of advice. I don't want to add additional methods into Invocation interface, in PHP it will be better to use language features to wrap an exceptions into another one.

**Comment by Shahelm** [comment]
I've done what you suggested. The resulting proxy does not contain a constructor.

**Comment by lisachenko** [comment]
Closed, no real need in API changes for PHP version of `AfterThrowing` advice
