### ISSUE TITLE
Bug with property access

### ISSUE THREAD

**Issue by Shahelm** [goaop/framework#271]
If a class has a constructor that fails:

PHP Notice:  Undefined index: method:__construct in ...
Uncaught Error: Call to a member function __invoke() on null in 

Code from proxy:

```
 68     /**
 69      * TestHandler constructor.
 70      * @param \Zend_Log $logger
 71      */
 72     public function __construct()
 73     {
 74         $this->__properties = array(
 75             'logger' => $this->logger
 76         );
 77         unset(
 78             $this->logger
 79         );
 80         return self::$__joinPoints['method:__construct']->__invoke($this);
 81     }
```

**Comment by lisachenko** [comment]
Could you tell me if the original class has a constructor? And one more question: are there any additional advices that can intercept the execution of `__construct()` method in this class?

**Comment by Shahelm** [comment]
Yes, the original class have a constructor.
There are Around, for one method.

**Comment by lisachenko** [comment]
Is this Around advice matches __construct or not? Easiest way to check this - temporary disable property access interceptor and then look one more time at generated proxy class and verify if joinpoint is present

**Comment by Shahelm** [comment]
I've done what you suggested. The resulting proxy does not contain a constructor.

**Comment by lisachenko** [comment]
Ok, then I should check the code for properties interceptor.

PS. Actually, I don't like property interception, because it's not so popular like method interception ) Thus, property interception can be buggy, be aware!

**Comment by Shahelm** [comment]
Thank you!
