### ISSUE TITLE
Annotation advice is executed multiple times

### ISSUE THREAD

**Issue by schlessera** [goaop/framework#272]
### Problem

I have an logging aspect that attaches its advice through an annotation pointcut. I want to use this for general-purpose logging, and have built it so that I can configure the logging message with annotation properties.

However, when I use this on an object hierarchy, the aspect gets executed multiple times, once for each level of inheritance.

Is this a bug, a limitation, or am I doing something wrong?
### Example

Consider the following hierarchy:

```
User
   Better_User extends User
      Best_User extends Better_User
```

When I have a `Best_User` object, and call the `User::get_data()` method, the advice is executed 3x, once for each level of inheritance.

If I call `Better_User::other_method()`, it gets executed 2x, and so on...
### Current Code

``` PHP
/**
 * Advice around the pointcut.
 *
 * @since 1.0.0
 *
 * @Around("@execution(DT\Membership\Annotation\Loggable)")
 *
 * @param MethodInvocation $invocation The method that was invoked.
 * @throws Exception To forward the exception that was caught.
 * @return mixed
 */
public function aroundLoggable( MethodInvocation $invocation ) {

    $method = $invocation->getMethod()->name;

    $object   = $invocation->getThis();
    $loggable = $invocation->getMethod()->getAnnotation( Loggable::class );
    $message  = $loggable->getString( $object );
    $level    = $loggable->getLevel();

    // Enter method.
    $this->logger->$level(
        $message,
        (array) $invocation->getArguments()
    );

    try {
        // Execute the invoked method.
        $result = $invocation->proceed();

        // Success.
        $this->logger->$level(
            sprintf( __(
                '%1$s - SUCCESS.',
                'dt-membership' ),
                $message
            ),
            (array) $result
        );
    } catch ( Exception $e ) {

        // Failure.
        $this->logger->$level(
            sprintf( __(
                '%1$s - ERROR: %2$s.',
                'dt-membership' ),
                $message,
                $e->getMessage()
            )
        );
        throw $e;
    }

    return $result;
}
```

**Comment by lisachenko** [comment]
Hi, I know what happens here. Method with annotation is present in the parent class, but it also matched with children classes as well, so method is intercepted 3 times in all hierarchy. You need somehow to restrict matching of this method in children classes. 

This feature was requested previously and was implemented in the engine level to intercept all parent methods and properties as well.

Unfortunately, there is no easy way to add this check into the engine, but you can try to check the declaringClassName from reflection with get_class($instance) to bypass your logging and proceed the execution.

**Comment by schlessera** [comment]
I've done some snooping around. The pattern I see is that I would only want to log when the `$invocation->getMethod()->class` is a proxied class (`<class>__AopProxied`). The cases where there is a superfluous logging, `$invocation->getMethod()->class` returns a real class instead of a proxy.

Does that make sense and is this the right way to filter? I hesitate to depend on the name of your proxy suffix...

**Comment by lisachenko** [comment]
Yes, depending on the suffix name smells bad :)  Interesting, how AspectJ solves this problem, this will give us a key to this issue. Of course, we can filter all children classes by `&& !within(Go\Aop\Proxy)` but this can filter interesting methods too...

Without engine support that kind of check is possible only in runtime with ugly checks of class names

**Comment by schlessera** [comment]
Here's what I've got so far, and it seems to work correctly:

``` PHP
// Bail early if we're not dealing with a proxied class, to avoid
// logging a method defined in a parent class and called through a child
// class multiple times.
$pattern = '|' . self::PROXY_SUFFIX . '$|';
if ( 1 !== preg_match( $pattern, $invocation->getMethod()->class ) ) {
    return $invocation->proceed();
}
```

I don't like that solution at all, though, and would welcome a more elegant approach to this.

**Comment by lisachenko** [comment]
For you solution I'd advise to use `str_pos()` for more faster checks instead of slow regular expression matching. Or you can add /S modifier to your regular expression for studying it, this will increase the matching speed.

**Comment by lisachenko** [comment]
I've created an issue #274 for pointcut matching improvement, looks like this feature should be implemented for pointcut engine.

**Comment by lisachenko** [comment]
To filter members without inheritance, just add `&& !matchInherited()` to the pointcut expression. This will match only own elements for each class.
