### ISSUE TITLE
Annotations need to be imported into extending classes

### ISSUE THREAD

**Issue by schlessera** [goaop/framework#273]
### Problem

When using annotation advice, for example (`@Loggable`), expected behavior is to have an import `use <namespace>\Loggable;` in the class that directly uses the annotation.

However, classes that extend upon this class will also need to import `use <namespace>\Loggable`, even if the extending class does not use this annotation, or else PHP will throw an error.
### Example

Consider the following hierarchy:

```
Post (has method `getTitle()` that uses `@Loggable`)
   SpecificPost extends Post (does not use `@Loggable` in any method)
```

When you call `getTitle()` on an object of type `SpecificPost`, The following exception will be thrown:

```
ERROR: [Semantical Error] The annotation "@Loggable" in method <namespace>\SpecificPost::getTitle() was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

**Comment by schlessera** [comment]
I think this is related to https://github.com/doctrine/annotations/issues/79

**Comment by schlessera** [comment]
Should be resolved by this PR: https://github.com/doctrine/annotations/pull/89

**Comment by lisachenko** [comment]
Just checked this issue on my test case and discovered that it can be a result of using of old version of `goaop/parser-reflection` library. How did you test your case? Installed framework itself via `composer install` and run it or added it into your application?

I tested on LoggingDemo class by creating two parents and added "@Loggable" to parent and grandparent methods. Everything is ok for me. However, method is intercepted several times for children, it's #272

**Comment by schlessera** [comment]
I'll need to revisit that code to test with latest versions. I was pulling GoAOP in as a composer dependency.
I might be able to retest that code during next week, I'll let you know what I find out.

**Comment by lisachenko** [comment]
@schlessera ping

**Comment by schlessera** [comment]
Sorry, haven't yet made any additional tests. Still waiting on the client to take a decision for the project I was using Go AOP for. As it turns out, there are weeks and months of discussions to be had to find out whether an enterprise site really needs logging... ;)

Current status is that I should get a decision in the second half of the month, so if they decide to go with my proposal, I'll be able to do more thorough tests.

**Comment by lisachenko** [comment]
Last ping )

**Comment by lisachenko** [comment]
Closed by inactivity. Feel free to reopen in the case of reproducing with new versions of framework

**Comment by lisachenko** [comment]
Still present in https://github.com/goaop/framework/issues/379
