### ISSUE TITLE
TokenReflection\Broker not found

### ISSUE THREAD

**Issue by scruffycoderofficial** [goaop/framework#277]
I am building a PHP Framework with the adoption of OOP and AOP. I have created an Application class that extends HttpKernel class and implements EventSubscriberInterface from Symfony. This application works perfect whet testing it. I have had an idea of configuring my GO! AOP within the first rpioratised method of my subscriper [https://github.com/Luyanda86/sparkle-php/blob/dev-master/src/Application.php](url), (see onStart() method whic is now empty.) Ideally I would love to add my initialization of AspectKernel instance there.

Unfortunately I havent ben successful in this as I seem to be bumping to "TokenReflection\Broker" not found fatal error. Is there a way you can suggest how best to integrate your library into my framwework?

Also it seems as though the `getApplicationLoaderPath()` is no longer available in your AspectKernel class. Is this the case? Also the 'autoload' key passed together with the options where we can register our namespaces seems to be ineffective if there.

Can you help me figure this one out.

**Comment by lisachenko** [comment]
Hello! Looks like your `includePath` option also includes vendor directory and `TokenReflection` library itself, so please, make sure to exclude framework files from AOP analysing.

**Comment by scruffycoderofficial** [comment]
Thanks for your quick reply. I have also taken labor of checking out your Symfony Bundle and I think I will adopt the same approach but without the use of the DependencyInjection Container as I would love GO! AOP to be the main drive behind initializing my Container implementation of that component.... I will feedback you on this. Thanks.

**Comment by scruffycoderofficial** [comment]
Hello! Again. I think I will need more of your help. Basically herein is my test class [https://github.com/Luyanda86/sparkle-php/blob/dev-master/tests/Sparkle/Aspect/AspectKernelTest.php](url). When I run my test nothing happens.

Below are the related files you may be interested in looking at to see what I am doind wrong:

[https://github.com/Luyanda86/sparkle-php/blob/dev-master/src/Aspect/AspectKernel.php](url)
[https://github.com/Luyanda86/sparkle-php/blob/dev-master/src/Aspect/Service/Facebook.php](url)
[https://github.com/Luyanda86/sparkle-php/blob/dev-master/src/Aspect/Monitor/SocialNetwork.php](url)

Issue I am having is that I am never seeing the SocialNetwork class in action. What is it that I am really missing? PLease help...

**Comment by lisachenko** [comment]
Hello, I can't see your classes, have you solved your issue?

**Comment by scruffycoderofficial** [comment]
@lisachenko I am happy to report that My aspects are working as expected. Below is how I set the library up within an event subscriber.

`$aspectKernel = AspectKernel::getInstance();
        $aspectKernel->init([
           'debug' => true,
           'includePaths' => array(),
           'excludePaths' => array(__DIR__ . '/../../../../vendor'),
           'cacheDir' => __DIR__ . '/../../../../var/cache'
         ]);`

This works.... Thank you for the pointer.... Cheers!!

**Comment by lisachenko** [comment]
Great! Wish you good luck with development )
