### ISSUE TITLE
Docbloc must use static for @return

### ISSUE THREAD

**Issue by VincentClair** [goaop/framework#278]
Hello,

I use PHPStorm as IDE. I think its better for autocompletion for it, and probably for all IDEs, if the docbloc from https://github.com/goaop/framework/blob/master/src/Core/AspectKernel.php#L80 is `@return static`.
As AspectKernel class is abstract, its could better if autocompletion reference to parent class.

**Comment by lisachenko** [comment]
Hello, not a big deal)

I will change this typehint to the `static` during a next change.

**Comment by VincentClair** [comment]
Thank you :)
