### ISSUE TITLE
Pointcut called more than once when using extend for 1.1.0 version

### ISSUE THREAD

**Issue by daseinpwt** [goaop/framework#285]
class A
{
    /**
      \* @myPointCut
      **/
    public function fun() {...}
}

class B extends A
{

}

$b = new B();
b.fun();

---

I saw pointcut was called twice.
'myPointCut' is an annotation pointcut for around advice

**Comment by daseinpwt** [comment]
1. When I edit the class B in B.php(edit anything, I just add a blank line) and save B.php, this problem will not happen. That is to say, every time I delete the cache dir and start the server, fun() will be called twice, but when I edit something in B.php, fun() will be called only once. I think it's related to the AOP file scanning mechanism when creating a new cache dir.
2. when I add following function in my Aspect file and execute it first in each pointcut function, this problem will not happen(It's the best way I find to solve the problem till now):

``` php
    // in Aspect file

    private function inPointcut(MethodInvocation $invocation)
    {
        $methodClassName = $invocation->getMethod()->class;
        return preg_match('/\\S+_AopProxied$/', $methodClassName);
    }
```

``` php
    // in Aspect file
    // pointcut function
    /**
    * @Around("@execution(<Annotation Class Name>)")
    */
    public function RequestWithJson(MethodInvocation $invocation)
    {
       if (!$this->inPointcut($invocation))
            return $invocation->proceed();

        /* deal with pointcut */
        return $invocation->proceed();
    }
```

**Comment by lisachenko** [comment]
Hello! This issue is related to #272 and #274.

I've added special syntax for that, just add `&& !matchInherited()` into the pointcut expression.

**Comment by daseinpwt** [comment]
I'm not clear how to 'add && !matchInherited() into the pointcut expression', could you give me a code sample?

**Comment by lisachenko** [comment]
Yes, sure:
`@Around("@execution(<Annotation Class Name>) && !matchInherited()")`

Assuming that you use one of the latest versions 1.1.0 or 2.0.0.

**Comment by daseinpwt** [comment]
my version is 1.1.0.
when I added the code as you said, PhpStorm(with goapp plugin installed) raise a error: "PointcutTokenType.-> or PointcutTokenType.\ expected, got '(' "

and the function was called twice agian.

**Comment by lisachenko** [comment]
Could you please, clean the cache, then run your code one more time. PhpStorm plugin isn't aware of this new pointcut syntax expression yet, see https://github.com/goaop/idea-plugin/issues/8, so, ignore this error. But framework engine should match annotated method only for class `A`.

**Comment by daseinpwt** [comment]
Unfortunately in my case it still not work.
fun() executed twice when I added '&& !matchInherited()' and not executed when '&& matchInherited()'.

**Comment by lisachenko** [comment]
Confirmed bug, affects 1.x version only. PR will be merged soon and version 1.1.1 will be released.

**Comment by lisachenko** [comment]
Please, try to update to the latest patch version with fix for this issue. Thank you for reporting!

**Comment by daseinpwt** [comment]
nice! now it works!
