### ISSUE TITLE
Accessing an information from an annotation in the advice body

### ISSUE THREAD

**Issue by daseinpwt** [goaop/framework#287]
like this:

/*
   @annotation_pointcut(1, 'pass_string')
*/
public function fun();

**Comment by lisachenko** [comment]
Hello, could you please describe what are you trying to do? Do you want to access an information from an annotation in your advice? Or do you want to intercept a methods by looking at annotation for them?

**Comment by daseinpwt** [comment]
OK. 
For example, I'd like to check the http arguments in my controller method, so I have created an annotation pointcut called 'CheckArguments'.

# 

/\* @CheckArguments('q', 'query required') */
public function MyControllerMethod();

# 

In my case, I need to check the existence of different arguments in different methods.
I think it will be easy for that if I can pass some params to annotation pointcut.

// some pseudocode

```
CheckArguments($arg_name, $error_alert) {
   if (exist($arg_name))
      proceed()
   else
      return $error_alert
}
```

**Comment by lisachenko** [comment]
Ok, probably, I understood what you want to do.

So, first step is to create an annotation class, called `Your\Namespace\CheckArguments`. It should contain properties `argName` and `errorAlert`.
Then, you put this annotation somewhere in your method docBlock.

To access this information, create a pointcut: `@execution(Your\Namespace\CheckArguments)` and in the advice body, just access it:

``` php
    public function aroundDeferred(MethodInvocation $invocation)
    {
        $checkAnnotation = $invocation->getMethod()->getAnnotation(CheckArguments::class);
        echo $checkAnnotation->argName, $checkAnnotation->errorAlert;
    }
```

**Comment by daseinpwt** [comment]
It seems to be close, but how can I pass value to `argName` and `errorAlert` in the docBlock?

**Comment by lisachenko** [comment]
To pass value in annotations, use standard doctrine annotations format:

``` php
use Your\Namespace\CheckArguments; // import the annotation class

/**
 * @CheckArguments(argName="q", errorAlert="query required")
 */
public function MyControllerMethod();
```

**Comment by daseinpwt** [comment]
OK, I made it. Thank you!

**Comment by lisachenko** [comment]
Great! )
