### ISSUE TITLE
PHP Warning:  mkdir(): File exists in /vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php on line 104

### ISSUE THREAD

**Issue by airbone42** [goaop/framework#288]
Hi,

since we upgraded to PHP 5.6.21 we get this error message in goaop which was installed using composer.

Did anyone ever stumble over that and has a hint what the problem could be?

**Comment by lisachenko** [comment]
Hi,

What is your version of framework?

**Comment by airbone42** [comment]
It's 0.6.1

**Comment by lisachenko** [comment]
Version 0.x are not maintained anymore, please upgrade to new versions.

It's also strange, that mkdir tries to create directory, because there is a check:

``` php
            if (!is_dir($parentCacheDir)) {
                mkdir($parentCacheDir, 0770, true);
            }
```

So, the only possible error if `$parentCacheDir` is exists and it is a file.

**Comment by airbone42** [comment]
Thanks an update to 1.1.1 fixed it. Sorry for opening this issue, I was not aware of an update. :(

**Comment by lisachenko** [comment]
It's ok, you are welcome! )
