### ISSUE TITLE
How to add multiple annotation pointcuts and give the order?

### ISSUE THREAD

**Issue by daseinpwt** [goaop/framework#289]
Can I add some annotation pointcuts to one method and let them run in order?

**Comment by lisachenko** [comment]
Hi, yes it's possible to add several annotations to the method and several advices will be applied to the method.

To control the order, just add ordering to the pointcut: @Before(...., order=10)

**Comment by daseinpwt** [comment]
Can I manage the order in doc block? Say, given annotation pointcut A and B, the order of them may be not absolute, in one method A is before B and in another B is before A.

**Comment by lisachenko** [comment]
Could you please add more details why do you need such behavior? It's unclear for me why do you need to have a control over order of advices, applied to the different methods.

**Comment by daseinpwt** [comment]
After a deep think, I have reorganized my code to let the annotation pointcut run without order. Anyway, thanks!
