### ISSUE TITLE
__PHP_Incomplete_Class sometimes instead annotation

### ISSUE THREAD

**Issue by clicman** [goaop/framework#292]
I've trying to deal with annotation values in around aspect and got strange behaviour:
in my aspect :

``` php
<?php

namespace Stom\Api\Util\Aop\Aspect;


use Annotation\Cacheable;
use Go\Aop\Aspect;
use Go\Aop\Intercept\MethodInvocation;
use Stom\Api\Config\Application;
use Exception;
use Go\Lang\Annotation\Around;


/**
 * Caching aspect
 */
class CachingAspect implements Aspect {

    /**
     * This advice intercepts the execution of cacheable methods
     *
     * The logic is pretty simple: we look for the value in the cache and if we have a cache miss
     * we then invoke original method and store its result in the cache.
     * @see Around
     * @param MethodInvocation $invocation Invocation
     *
     * @Around("@execution(Annotation\Cacheable)")
     *
     * @return mixed
     */
    public function aroundCacheable(MethodInvocation $invocation) {
        $cache = null;
        try {
            $cache = Application::getMemCache();
        } catch (Exception $ex) {
            var_dump('NO_CACHE');
        }
        if ($cache !== null) {
            $obj = $invocation->getThis();
            $class = is_object($obj) ? get_class($obj) : $obj;
            $key = $class . ':' . $invocation->getMethod()->name;
            $key .= ':' . serialize($invocation->getArguments());
            $result = $cache->get($key);
            if ($result === false) {
                var_dump($invocation->getMethod()->getAnnotations());
                $time = $invocation->getMethod()->getAnnotation('Annotation\Cacheable');
                $result = $invocation->proceed();
                var_dump($time);
                $cache->set($key, $result);
                echo('no');
            }
            echo ('cache');
            return $result;
        } else {
            echo ('nullcache');
            return $invocation->proceed();
        }

```

And at first time it dumps as expected, but in another times it's wrapped into __PHP_Incomplete_Class :

``` php
array(1) {
  [0]=>
  object(__PHP_Incomplete_Class)#394 (3) {
    ["__PHP_Incomplete_Class_Name"]=>
    string(20) "Annotation\Cacheable"
    ["time"]=>
    int(10)
    ["value"]=>
    NULL
  }
}
```

Why can it be so?

ubuntu 16.04 x64 PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )

**Comment by lisachenko** [comment]
Hello, try to set unserialize_callback_function setting to your composer class loader callback. In this case, PHP will load missing classes before unserializing data.

**Comment by clicman** [comment]
Thank you for fast reply! But could you provide details please? I do not know about unserialize_callback_function and how I should use it.

**Comment by lisachenko** [comment]
If you use only composer, then add this line somewhere at front-controller/bootstrap file:

``` php
// load default composer loader
$loader = include __DIR__.'/../vendor/autoload.php';
ini_set('unserialize_callback_func', $loader);
```

**Comment by lisachenko** [comment]
Additional information is available on php.net site: http://php.net/manual/en/var.configuration.php#unserialize-callback-func

**Comment by clicman** [comment]
Ok. I'm using composer only. Tried your suggestion and it doesn't help.
Still works first time only. All another times it returnt Incomplete_Class

**Comment by lisachenko** [comment]
Could I ask you to step in into the annotation class loading/unserialization? Is autoloader triggered for you class or not?

**Comment by clicman** [comment]
I found the problem. It was in my project folder structure:
Folder path for annotation was: Stom\Api\Util\Aop\Annotation\Cacheable.php
But I've declared namespace as "Annotation"
After I changet it to "Stom\Api\Util\Aop\Annotation" problem solved.

Is strict following folder structure is mandatory for unserialization?

**Comment by lisachenko** [comment]
Sorry for the late reply.

I think your question isn't related directly to the folder structure and unserialization process, it's more related to the class loading, so if a class could not be loaded, then it will be replaced by incomplete class. That's it )

Anyway, I'm glad that this issue is solved.
