### ISSUE TITLE
[Proxy] add declare(strict_types=1) into the generated code

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#299]
For PHP>=7.0 generated proxies should contain strict mode enabled if the original file has the same option.

**Comment by jcchavezs** [comment]
@lisachenko, can you please explain the consequences of not having this?

**Comment by lisachenko** [comment]
@jcchavezs please see https://3v4l.org/Bf33R#v700 and https://3v4l.org/e4g9t#vhhvm-3120 for the difference.

If an original source code uses strict mode, then we can't call method with wrong arguments and exception will be thrown. When we create a proxy with non-strict mode, then caller can pass weaker arguments, eg. integer instead of string and proxy will happily accept it as valid value, see https://wiki.php.net/rfc/scalar_type_hints_v5 for additional information about the difference.

**Comment by icanhazstring** [comment]
@lisachenko is this still a valid issue?
If so, could you point me into a direction where to implement this? Would like to take this one ;)

**Comment by lisachenko** [comment]
@icanhazstring great ) It should be done in the `WeaverTransformer` class where file content is generated. And `ReflectionFile->isStrictMode()` method should be checked for the original file to enable strict types for generated content.

**Comment by icanhazstring** [comment]
@lisachenko nice. You can assign it to me then :wink:

**Comment by icanhazstring** [comment]
@lisachenko this could be closed then 😉

**Comment by lisachenko** [comment]
Yes, sure!
