### ISSUE TITLE
Last version of composer breaks the logic of autoloading

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#30]
Composer now prepends itself to the list of autoloaders instead of appending, this breaks the logic of loading classes for internal classes.
Reference to the commit in composer: https://github.com/composer/composer/commit/c80cb76b9b5082ecc3e5b53b1050f76bb27b127b

Need to decide, how to fix the logic of autoloading.

**Comment by lisachenko** [comment]
Relates to the issue https://github.com/composer/composer/issues/1487

**Comment by marcj** [comment]
@lisachenko, have you already fixed that bug? Is it currently possible to use go-aop-php with composer's autoloader used?

**Comment by lisachenko** [comment]
@marcj this issue is still present, however, I found a trick that reduce the probability of reproducing the issue to ~0%. What framework do you use? Are there any additional autoloaders registered with composer?
