### ISSUE TITLE
Pass exception to adviceMethod in AfterThrowingInterceptor

### ISSUE THREAD

**Issue by cocciagialla** [goaop/framework#302]
Hi, it would be nice to have the catched exception instance passed as second argument to the adviceMethod invocation:

```
try {
  $result = $joinpoint->proceed();
} catch (Exception $invocationException) {
  $adviceMethod = $this->adviceMethod;
  $adviceMethod($joinpoint, $invocationException);
  
  throw $invocationException;
}
```
so it's possible to use it, for example, as follow:

```
/**
 * @param MethodInvocation $invocation
 * @param \Exception $ex
 * @AfterThrowing("execution(public **->delete(*))")
*/
public function afterThrowing(MethodInvocation $invocation, \Exception $ex)
{
  $this->logger->error($ex->getMessage() . ' at ' . $ex->getFile() . ':' . $ex->getLine();
}
```

**Comment by lisachenko** [comment]
Hi, for the case when you need to access an instance of exception, you can easily use `Around` method ?

**Comment by cocciagialla** [comment]
Hi, thanks for the reply. Yes, it is certainly an alternative and I will use it for my scenario, but in this case I just have to execute the code proposed above in my advice. Like this:
```
/**
 * @param MethodInvocation $invocation
 * @Around(pointcut="public **->delete(*)")
*/
public function afterThrowing(MethodInvocation $invocation)
{
  try {
    $invocation->proceed();
  } catch (Exception $invocationException) {
    $this->logger->error($ex->getMessage() . ' at ' . $ex->getFile() . ':' . $ex->getLine();
    throw $invocationException;
}
```
Passing exception in AfterThrowing as second parameter will save me to implement the try/catch logic. 

A kind of this feature is also available in AspectJ (http://howtodoinjava.com/spring/spring-aop/aspectj-afterthrowing-annotation-example/) where it is also possible to filter for which kind of exception the advice should be called.

**Comment by lisachenko** [comment]
I think that your feature request can be implemented for `AfterThrowing` type of advice by passing second argument to the invocation body.

**Comment by lisachenko** [comment]
Implemented in the master branch. Thanks for the reporting!
