### ISSUE TITLE
Release schedule for php 7.1

### ISSUE THREAD

**Issue by clicman** [goaop/framework#306]
Hello! Thank you for great framework!
I see what master supports php 7.1. Is any schedule for release?

**Comment by lisachenko** [comment]
Hi! Master branch has limited support for 7.1 features, because of WIP with `goaop/parser-reflection` library. See https://github.com/goaop/parser-reflection/issues/12 for progress tracking. I'm expecting full 7.1 support will be available soon (till the end of this year).

**Comment by clicman** [comment]
Thank you!
