### ISSUE TITLE
Class Proxy contains syntax errors in PHP 7

### ISSUE THREAD

**Issue by jgiacobbi** [goaop/framework#312]
Hello, My project has been working until just recently. We started dependency injecting some things into a particular class and the typehints cause the proxy to have syntax errors.

Here is the constructor declaration:
```php
public function __construct(ClassOne $classOne, Logger $logger = null, System $system = null)
{
	...
}
```

Here is the proxied version:

```php
public function __construct(\Company\Namespace\ClassOne $classOne, ?\Company\Namespace\Logging\Logger $logger = NULL, ?\Company\Namespace\System $system = NULL)
{
    return self::$__joinPoints['method:__construct']->__invoke($this, \array_slice([$classOne, $logger, $system], 0, \func_num_args()));
}
```

And this is the error:

```
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/log/company/project/cache/_proxies/src/API.php on line 30
```

The workaround is just to remove the typehints. Without typehints it works fine.

**Comment by lisachenko** [comment]
Yes, confirmed as a bug in the master branch. I will apply a patch tomorrow.

In case of emergency, you can lock any stable tag (2.0.0) for now instead of dev-version.
