### ISSUE TITLE
Registering multiple aspects on 0.6.0

### ISSUE THREAD

**Issue by andreyvk** [goaop/framework#313]
Hi @lisachenko ,

Happy New Year! Bit late, but better late than never :)

I have a problem registering more than one aspect on a 0.6.0. I know it's a dinosaur, but it's been working super well for which I am truly thankful.

Basically, the code in the kernel is:

```php
 protected function configureAop(AspectContainer $container)
    {
        $container->registerAspect(new ApiAspect());
        $container->registerAspect(new SessionAspect());
    }
```

What happens is that it takes the latter only (`SessionAspect`) and seems to ignore former (`ApiAspect`). Am i doing something wrong or is it a known issue for 0.6?

Would you also suggest moving to 1.x to resolve the issue? Are there any incompatibility issues that might happen?

**Comment by lisachenko** [comment]
Hi! I don't know any issues in 0.x branch with registration of multiple aspects. Engine should apply them all. Therefore, there is one thing to check: do you use "around" type of advice in your aspects? Could you show me your pointcuts and advice's body?

**Comment by andreyvk** [comment]
Hi there,

No I'm using `@Before`. Here're the files: [gist](https://gist.github.com/andreyvk/bf72b3cfd6863904b7f0f1de1b139dc2)

**Comment by lisachenko** [comment]
I couldn't see anything strange in your aspects. Everything looks correct. Could you also look at the cache with generated proxies to see which advices are registered for each method like this:

```php
\Go\Proxy\ClassProxy::injectJoinPoints('Demo\Example\LoggingDemo',array (
  'method' => 
  array (
    'perform' => 
    array (
      0 => 'advisor.Demo\\Aspect\\LoggingAspect->beforeMethodExecution',
    ),
    'execute' => 
    array (
      0 => 'advisor.Demo\\Aspect\\LoggingAspect->beforeMethodExecution',
    ),
  ),
// ....
```

**Comment by andreyvk** [comment]
Hi @lisachenko, 

I found my mistake after looking at the proxies. 

In any case, are is it safe to move to 1.x from 0.6? Any compatibility guides I can look at?

Thank you very much for the help!
