### ISSUE TITLE
Aspect isn't Being Invoked At all

### ISSUE THREAD

**Issue by Samuel-Campbell** [goaop/framework#321]
There is a problem and our aspect invocations aren't working. Here are both files we think there may be errors. We do not have a cache directory. We inserted Error_Logs to check what occurs. 

The error_log("Init"); works from the ApplicationKernel but aspects do not work.

```php
require_once(realpath($_SERVER['DOCUMENT_ROOT']) . '/vendor/autoload.php');


// Initialize an application aspect container

$applicationAspectKernel = ApplicationAspectKernel::getInstance();`

$applicationAspectKernel->init(array(
        'debug' => true, // use 'false' for production mode

        'appDir'   => (realpath($_SERVER['DOCUMENT_ROOT']). '/../'),

        // Cache directory
        'cacheDir' => __DIR__ . '',
        // Include paths restricts the directories where aspects should be applied, or empty for all source files
        'includePaths' => array(
          
        )// If this doesn't work we could try leaving this empty and it should apply to every php class found from the root directory
));
```
```php
    protected function configureAop(AspectContainer $container) {
        $container->registerAspect(new MonitorAspect());
        error_log("Init");
    }

    protected function getApplicationLoaderPath() {
        return __DIR__ . $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
    }
```

**Comment by lisachenko** [comment]
Hi!

Could you please give me resolved values for `appDir`, `cacheDir`? Also, which version of AOP engine and PHP do you use?

The method `getApplicationLoaderPath()` is sooo old and removed in all modern versions of AOP engine. So, I'm expecting that you are using very old version.

**Comment by Samuel-Campbell** [comment]
appDir : /var/www/html/SOEN344Project/
cacheDir: /var/www/html/SOEN344Project/cache

*Note: The cache directory is empty... I'm unsure what to use it for

PHP 7.1.3

Using GOAOP, your latest version downloaded with composer

**Comment by lisachenko** [comment]
Application and cache directories look valid. 

To debug, you could put a breakpoint at Enumerator.php, line 93 and wait for your file and verify that result is `true` for it. If you will get `true` for the `Enumerator` then file is suitable for transformation and following step to check is to look at your pointcut expression in the `MonitorAspect` class (please, post it here).

And could I also ask you to give me a full file name where you expect AOP to be applied.

**Comment by lisachenko** [comment]
Anything new here?

**Comment by lisachenko** [comment]
Closed by inactivity. Try to open `demos/` directoty of framework for testing, if it's working, then there is an issue in your environment or configuration.
