### ISSUE TITLE
How to use Go! AOP PHP without a framework?

### ISSUE THREAD

**Issue by Kwadz** [goaop/framework#323]
Is it possible to use Go! without a framework like Symfony? Let's say a PHP application managed by composer only. If so, how to do it?

**Comment by lisachenko** [comment]
Hi! Yes, it's possible to use AOP without any external frameworks. Just look at `demo` folder and run it in your browser to see working examples.

To have your working example just start from http://go.aopphp.com/docs/installation/ and follow instructions.

**Comment by lisachenko** [comment]
If you will have any questions, just ping me.

**Comment by Kwadz** [comment]
Thanks, I asked the question because [the documentation](http://go.aopphp.com/docs/initial-configuration/) mentions only the way with a front controller.

**Comment by lisachenko** [comment]
@Kwadz if you don't have single front controller, but rely on composer, then you can simply put all AOP initialization logic into the one single PHP file and then add it via `php.ini` [auto_prepend_file](http://php.net/manual/en/ini.core.php#ini.auto-prepend-file) option for your project.
