### ISSUE TITLE
beforeMethodExecution expects 'MethodInvocation' but receives a 'StaticInitializationJoinpoint'

### ISSUE THREAD

**Issue by marleyiam** [goaop/framework#325]
I just have a regular Aspect definition which I got by copy & pasting from docs.
I'm trying to intercept ALL methods from a certain package/namespace doing like this:   @Before("within(AdminModule\Controllers\**)")

After running I'm getting the error below:

Argument 1 passed to Core\Aspects\MyAspect::beforeMethodExecution() must implement interface Go\Aop\Intercept\MethodInvocation, instance of Go\Aop\Framework\StaticInitializationJoinpoint given, called in /var/www/shopping/vendor/goaop/framework/src/Aop/Framework/BeforeInterceptor.php on line 33 and defined.

While debugging I found the Go\Proxy\ClassProxy::injectJoinPoints kinda define it by running AspectContainer::STATIC_INIT_PREFIX . ':root';

This is the farthest I can go for now, maybe I'm misunderstanding some point. Any clues appreciated :)

**Comment by lisachenko** [comment]
Hi! It's called outdated documentation...

Version 0.x uses `within` only for methods, but 0.x was unstable version, so in 1.x I made `within` more closer to Java analog, so it also matches property access, class initialization, static and dynamic method calls.

You can change your typehint temporarily to the `Joinpoint` to see what happens and just echo this parameter.

To intercept only method calls just use `execution(public|protected AdminModule\Controllers\**->*(*))` syntax for versions >=1.x

**Comment by marleyiam** [comment]
Thanks a lot for such quicky answer!
I've tried your sintax suggestion but I got an error. 
In order to make it work I just added an extra backslash before the double star (**), like this:

    @Before("execution(public|protected AdminModule\Controllers\**->*(*))")

Congrats for such awesome job :)

**Comment by lisachenko** [comment]
Hi, @marleyiam!

Ah yes, small typo in my answer, was answering from my iphone )

Thank you for working with Go! AOP! 
PS. If you don't mind just write a twitter message or tell your friends about this framework. Thanks in advance!
