### ISSUE TITLE
Using classes which has unavailable parents in current environment

### ISSUE THREAD

**Issue by TheCelavi** [goaop/framework#329]
I have just stumbled upon this issue - noticed that there are commands for debugging, so I have used those. 

When commands are executed and code is scanned for advices, there has been thrown exception that PhpUnit\TestCase class can not be found. Project uses PHPUnit in form of Phar archive, which is normal. Test classes were scanned. 

I guess that it would be convenient that this exception should be catched, warning fired, and execution should continue with skipping those classes from further introspection.

Or - at least, documentation should be updated with this info -> folders which contains classes that extends other classes from Phar archives should be configured as excluded.

This happened in Symfony project, where bundle is generated in src directory, and by default, it generates Tests directory with some default tests... Now, this was stupid because that is a bad practice, however, PHPUnit is not only lib provided and used as phar....

**Comment by lisachenko** [comment]
I can remember this issue, it can be fixed by adding */Tests/* pattern to `excludePaths` option. Alternatively, for PHP7 we can catch parse exceptions and just skip them during cache warming process.

This should be qualified as a bug, let's see how to catch this.

**Comment by TheCelavi** [comment]
Minimum effort to handle this is to document the issue as known, with the instruction how to handle it. I believe that even if just improve documentation in regards to this subject - that would be just fine.

**Comment by lisachenko** [comment]
I have checked this issue one more time and looks like after addition of
```php
            } catch (\Throwable $e) {
                $displayException($e, $path);
```
into the `CacheWarmer` class it can handle now missing classes and fatals in analysis.

**Comment by TheCelavi** [comment]
Article added to documentation: http://go-aop-php.readthedocs.io/en/dev/articles/limitations_and_known_issues/index.html#weaving-of-classes-functions-from-phar-archive

To be honest - I would rather throw exception explicitly and let the user handle the issue. We had some issues with similar occurrences in Symfony project and it is hard to debug when error is being suppressed (development mode, we don't warmup cache via console to see output). 

At least, exception should be always thrown in debug mode.

**Comment by lisachenko** [comment]
How current issue is related to the phar archives? AFAIK, goaop could work even with read-only filesystems, eg, with `phar` archives, but cache should be compiled into phar archive as well. 

I think that current issue has nothing common with interception of methods from "incomplete" classes - when we couldn't check parent classes. In some cases it's perfectly ok to bypass such files.

What is your position about that? Not sure, that I want always see exception during dev mode if I have optional dependency which is not available at that moment.

**Comment by TheCelavi** [comment]
Phpunit is example. If u run your unit tests by using phpunit.phar, phpunit classes are not autoloadable with composer in production/development environment. Which is normal.

In that case, user should exclude unit tests from weaving (that is, user should exclude from weaving everything that he do not intend to weave).

You are right, exceptions should be suppressed for optional dependencies.

I guess that we should warn users in documentation about this - to check weaving process in console with very verbose if they suspect something is wrong.

**Comment by TheCelavi** [comment]
I would close this issue, there is nothing that we can/should do about this anymore.

**Comment by lisachenko** [comment]
> Phpunit is example. If u run your unit tests by using phpunit.phar, phpunit classes are not autoloadable with composer in production/development environment. Which is normal.

> In that case, user should exclude unit tests from weaving (that is, user should exclude from weaving everything that he do not intend to weave).

> You are right, exceptions should be suppressed for optional dependencies.


Yes, it's ok. Exception during warm up is the best way to work with this. Otherwise, standard PHP exception will be thrown about missing parent class.
