### ISSUE TITLE
[Refactoring] Duplicated code detected - cache warmup

### ISSUE THREAD

**Issue by TheCelavi** [goaop/framework#332]
Found a duplicated code:

1. https://github.com/goaop/framework/blob/master/src/Console/Command/CacheWarmupCommand.php
2. https://github.com/goaop/goaop-symfony-bundle/blob/master/CacheWarmer/AspectCacheWarmer.php
3. https://github.com/goaop/goaop-zf2-module/blob/master/src/Console/Warmup/Zf2WarmupCommand.php

Proposal: created dedicated class which will deal with cache warming up. Stated classes above will use that class.
Benefit: easier testing and code maintenance. Any change now has to be propagated in three different places.

**Comment by lisachenko** [comment]
Fixed in #333
