### ISSUE TITLE
Aspect can not use injected class that should be processed by AOP

### ISSUE THREAD

**Issue by martixy** [goaop/framework#338]
#### Version Details
```PHP 7.1.8-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Aug  3 2017 18:37:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```
```
goaop/framework            2.1.2 Framework for aspect-oriented programming in PHP.
goaop/goaop-symfony-bundle 2.0.1 Integration bridge for Go! AOP framework
goaop/parser-reflection    1.2.1 Provides reflection information, based on raw source
```

I am trying to decouple certain interactions with my persistence layer (Doctrine in this case).

```PHP
<?php

namespace AppBundle\Aspect;


use AppBundle\Services\Persister;
use Doctrine\ORM\EntityManagerInterface;
use Go\Aop\Aspect;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\After;
use Go\Lang\Annotation\Around;

class PersistenceAspect implements Aspect
{
    /**
     * @var Persister
     */
    private $persister;
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    private $currentTransaction = [];

    public function __construct(Persister $persister, EntityManagerInterface $entityManager)
    {
        $this->persister = $persister;
        $this->entityManager = $entityManager;
    }

    /**
     * @Around("@execution(AppBundle\Aspect\Annotation\Persistable)")
     *
     * @param MethodInvocation $invocation
     * @return mixed
     */
    public function persist(MethodInvocation $invocation)
    {
        dump($this->persister->isEnabled());
        // TODO: Check if result is entity(possibly via annotations)
        $entity = $invocation->proceed();
        if ($this->persister->isEnabled()) {
            $this->entityManager->persist($entity);
            $this->currentTransaction[] = $entity;
        }
        dump($this->currentTransaction);
        return $entity;
    }

    /**
     * @After("execution(public Doctrine\ORM\EntityManager->flush(*))")
     *
     * @param MethodInvocation $invocation
     */
    public function flush(MethodInvocation $invocation)
    {
        dump($this->currentTransaction);
        $this->currentTransaction = [];
        $this->persister->disablePersist();
    }

    /**
     * @After("execution(public AppBundle\Services\Persister->abort(*))")
     *
     * @param MethodInvocation $invocation
     */
    public function abort(MethodInvocation $invocation)
    {
        dump($this->currentTransaction);
        foreach ($this->currentTransaction as $entity) {
            $this->entityManager->detach($entity);
        }
        $this->currentTransaction = [];
    }
}
```
Persister is a simple global state disguising as a service:
```PHP
<?php

namespace AppBundle\Services;


class Persister
{
    private $enabled = false;

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function enablePersist()
    {
        $this->enabled = true;
    }

    //These are handled differently by the attached aspect.
    public function disablePersist()
    {
        $this->enabled = false;
    }

    public function abort()
    {
        $this->enabled = false;
    }
}
```
The annotation:
```PHP
<?php

namespace AppBundle\Aspect\Annotation;

/**
 * @Annotation
 * @Target("METHOD")
 */
class Persistable
{
}
```
Here is where I use it:
```PHP
<?php

namespace AppBundle\Manager\Component;

use AppBundle\Aspect\Annotation\Persistable;
use AppBundle\Entity\Component;

class ComponentManager
{
    // ...

    /**
     * @Persistable()
     *
     */
    public function initializeComponent()
    {
        $newComponent = new Component();
        $newComponent->setThis();
        $newComponent->setThat();

        return $newComponent;
    }
    // ...
}
```
It all seems dead simple, but I cannot get the aspect methods(advice, I believe is the proper parlance) to execute. Not the method, not the annotation. For the third-party bundle, I assume I have to explicitly include the directory in my goaop config, right?

And I have aspects working in other parts of the program. I can even see goaop generating proxy classes in my cache dir, but the advice are still never executed).

**Comment by TheCelavi** [comment]
> For the third-party bundle, I assume I have to explicitly include the directory in my goaop config, right?

Yes, if it is not, by default, in src/ directory (talking here about Symfony project).

Your code seams right at the first glance... give us more details...

**Comment by lisachenko** [comment]
Hi, please share your configuration for the goaop bundle itself. 

And yes, as @TheCelavi mentioned you should explicitly add more directories into the `includePaths` option to apply aspects to vendor directories as well.

I can see one more suspect place in your code: you are trying to inject `Persister` service into an aspect that should be processed by AOP itself. All aspects are loaded before weaving, so your class won't be processed. Lazy proxy won't help you too. Only possible solution for this case is to inject container itself and then use it as locator during method invocation for receiving an instance of `Persister` class. At that point AOP will be ready to process your class and will weave advices into it.

**Comment by TheCelavi** [comment]
@lisachenko Good  catch!

@martixy Yes, that is the problem, you have circular references here, so it breaks weaving. It is known issue: https://github.com/goaop/goaop-symfony-bundle/issues/15

Unfortunately, we don't have a way (yet) to detect it automatically and warn the user. We are working on new documentation where this will be explained, and possibly, we will have detection mechanism as well. 

Alexander is correct, injection of Container is only help here, which no one likes. 

Other approach is to redesign your architecture, since, you are using aspect to weave service, and aspect uses that weaved service -> it is kinda fishy... it is really a case "A needs B, but B needs A to work..." 

I am going to close the issue since there is nothing that we can do more to help, this is known limitation of FW.

**Comment by lisachenko** [comment]
I can also link this to known issue #291 when AOP tries to intercept itself.

**Comment by martixy** [comment]
Okay, let us forget the circular reference. I tried with the simplest aspect possible and couldn't get it to execute. At least not consistently.
I disabled XDebug, just in case - after which it worked - once.
After some fiddling around the more complicated aspect also worked - once, in a chopped down version, without the circular reference.
I clear cache between each annotation change, I tried restarting apache a few times.
All in all I got each aspect to execute exactly once.

For the life of me, I cannot figure out under what conditions it fails or works. It's black magic.

I don't even have any idea how to debug.

My config:
```yaml
go_aop:
    cache_warmer: true
    options:
        debug: true #%kernel.debug%
        #app_dir: "%kernel.root_dir%/../src"
        cache_dir: %kernel.cache_dir%/aspect
        #include_paths: []
        #exclude_paths: []
        #container_class: ~
        features: [INTERCEPT_INCLUDES]
```

**Comment by TheCelavi** [comment]
Did you updated bundle/aop framework? Do you know that you have console commands available that you can run to debug/warm cache?

**Comment by martixy** [comment]
The versions are noted in my OP. I believe they are the latest(at least at the time of OP). And yes, I explicitly warm the cache every time.

**Comment by TheCelavi** [comment]
You run one of these commands to debug: https://github.com/goaop/framework/tree/master/src/Console/Command ? debug:advisor, debug:aspect?

**Comment by martixy** [comment]
Okay, thanks for these.

Can't test right now, so will get back to you.
