### ISSUE TITLE
[Support] Getting annotated parameters of method

### ISSUE THREAD

**Issue by Airmanbzh** [goaop/framework#341]
Hello,

Is it possible to get annotated parameters like this :
```
public function exemple(/**@Param("owner") **/ $owner, /** @Param("repo") **/ $repo);
```

It could help to instanciate variables between annotations

Thanks :)

**Comment by Airmanbzh** [comment]
My question is still valid but I found an other way to make it : I can use 
```
$invocation->getMethod()->getParameters()
```

to get "named" parameters and reuse it :)

**Comment by lisachenko** [comment]
Hi, could you please clarify your question? PHP and tools don't have support for annotated parameters (like in Java), so there is no API and pointcut syntax for that.

You could use reflection API for the method to get list of parameters and names. See https://github.com/php-deal/framework/blob/master/src/Aspect/AbstractContractAspect.php#L40-L49 for example

**Comment by lisachenko** [comment]
Ping, @Airmanbzh

**Comment by Airmanbzh** [comment]
Like you said it was to have something like java :)
I managed to do it without it.

Thanks for your help !
