### ISSUE TITLE
[Support] PHP7.1 syntax is unsupported for version 0.6.x of framework

### ISSUE THREAD

**Issue by TuxBoy** [goaop/framework#352]
Hello,

Why I have this error when I use the strict typing of PHP 4.1 (public function test (): array)
`Unexpected token found.`?
It comes from al bookstore php-token-reflection.
Thank you for your reply.

**Comment by lisachenko** [comment]
Hi! Which version of framework do you use?

Currently supported version are 2.x, all 1.x versions are outdated and can not handle PHP5.6 and PHP7 syntax, so you need to upgrade.

`php-token-reflection` library is outdated and isn't supported.

**Comment by TuxBoy** [comment]
Ok thank you, indeed I use version 0.6.1, version 2 is stable, dans le fichier composer, je doit bien remplacer le numéro de version 0.6.1 par "lisachenko/go-aop-php": "2.0-dev" ?

**Comment by lisachenko** [comment]
You should use `goaop/framework: ^2.0` as of now. But migration should be made, because 0.x was working in different way.

Check points:
1) Your application is using only composer for class loading
2) Joinpoints changed, instead of @annotation, you should use @execution. Also syntax `class(Specifc\ClassName)` was also removed
3) Method  `getDefaultFeatures()` was removed from the `AspectKernel`. Do not use it.

All other things should be compatible.

**Comment by TuxBoy** [comment]
Good ! thank you very much, it works, good framework in passing.

**Comment by lisachenko** [comment]
@TuxBoy Superb! You are welcome )

**Comment by lisachenko** [comment]
PS. Don't forget to promote this framework and leave your star for it, this motivates us to make it better ))

**Comment by TuxBoy** [comment]
I will miss it ), just a small question, is it useful to use Middleware when using AOP in our project ?

**Comment by lisachenko** [comment]
Could you elaborate please, what do you mean when asking about Middleware? There are so many different meanings for "middleware" nowadays.

**Comment by TuxBoy** [comment]
Yes, sorry, I mean using the http-middleware which allows to do a processing between the request of the server and the answer, one can do that also with AOP ?

**Comment by lisachenko** [comment]
My opinion about all this "super-puper middleware" is following: https://plus.google.com/+AlexanderLisachenko/posts/h3P97ecnmnx

> Very interesting to see when special terms like "middleware" are used to describe things that are already described earlier in the "Separation of Concerns (SoC) and Aspect-Oriented Programming (AOP)" work by Dijkstra http://users.encs.concordia.ca/~bentahar/COMP348/Part%206%20(Summer%202013)%20Web.pdf

> What is the difference between middleware and AOP? Could you compare them?

> Each middleware == single advice of aspect that holds specific domain logic.
Each argument passed to the concrete middleware == an instance of joinpoint that holds all necessary information about arguments and object instance.


So, middleware is just ugly try to describe AOP, however Djikstra already described it many-many years ago.

**Comment by lisachenko** [comment]
AOP is more general, powerful tool that can replace all Event Dispatchers, Events and Middlewares in your application.

**Comment by TuxBoy** [comment]
Hello,

Ok, thanks, so it makes sense to use both in an application. I find that AOP is not well known in PHP, pity.
