### ISSUE TITLE
[Support] Configuring framework for the Yii2 application 

### ISSUE THREAD

**Issue by erickskrauch** [goaop/framework#365]
Hi.

I'm trying to integrate Go! AOP framework with my Yii2 application, based on the Advanced template. I have found [this repository](https://github.com/lisachenko/yii2-aspect), but it (as I can see) adopted to AOP 0.4.3 or 0.5.0, because last update of this repository was at the same time in 2014.

So... What I'm trying to do:

My `api/web/index.php` looks like that:

```php
<?php

use api\aspects\ApiAspectKernel;
use common\config\ConfigLoader;
use Go\Instrument\Transformer\FilterInjectorTransformer;
use yii\web\Application;

require __DIR__ . '/../../vendor/autoload.php';
require __DIR__ . '/../aspects/ApiAspectKernel.php';

defined('YII_DEBUG') or define('YII_DEBUG', in_array(getenv('YII_DEBUG'), ['false', '1']));
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV'));

// Initialize an application aspect container
$applicationAspectKernel = ApiAspectKernel::getInstance();
$applicationAspectKernel->init([
    'debug' => YII_DEBUG,
    'appDir' => __DIR__ . '/../../',
    'cacheDir' => __DIR__ . '/../runtime/aspect',
    'excludePaths' => [
        __DIR__ . '/../runtime/aspect',
        __DIR__ . '/../../vendor',
    ],
]);

require FilterInjectorTransformer::rewrite(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');
require __DIR__ . '/../../common/config/bootstrap.php';
require __DIR__ . '/../config/bootstrap.php';

$config = ConfigLoader::load('api');

$application = new Application($config);
$application->run();
```

I copied from the examples a test aspect:

```php
// api/aspects/ApiAspectKernel.php
<?php
namespace api\aspects;

use Go\Core\AspectContainer;
use Go\Core\AspectKernel;

// TODO: temp solution. Replace by composer classloader, because Yii2 autoloader is not initialized yet
include __DIR__ . '/TestAspect.php';

class ApiAspectKernel extends AspectKernel {

    protected function configureAop(AspectContainer $container): void {
        $container->registerAspect(new TestAspect());
    }

}
```

and 

```php
// api/aspects/TestAspect.php
<?php
namespace api\aspects;

use Go\Aop\Aspect;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\Before;

class TestAspect implements Aspect {

    /**
     * Method that will be called before real method
     *
     * @param MethodInvocation $invocation Invocation
     * @Before("execution(public api\models\authentication\LoginForm->login(*))")
     */
    public function beforeMethodExecution(MethodInvocation $invocation) {
        $obj = $invocation->getThis();
        echo 'Calling Before Interceptor for method: ',
        is_object($obj) ? get_class($obj) : $obj,
        $invocation->getMethod()->isStatic() ? '::' : '->',
        $invocation->getMethod()->getName(),
        '()',
        ' with arguments: ',
        json_encode($invocation->getArguments()),
        "<br>\n";
        exit(); // To be 100% sure
    }

}
```

and it's not working. 

I think, I'm missing some part due to outdated documentation, or something like that. Can you fix me?

**Comment by lisachenko** [comment]
Hi! You are right that docs about Yii2 are outdated. Things are changed, so it's expected that something is broken.

Unfortunately I haven't time to work on all modules, so concentrate only on framework itself. Regarding Yii2 - it has many custom class loaders, AFAIK. This brings troubles with applying of AOP, because AOP works well only with composer class loading.

I can't promise you that I'll be able to look into this ASAP, but going to leave it open to create Yii2 module for AOP - it should be more natural way to use AOP in applications.

**Comment by erickskrauch** [comment]
I think, it will work in case, if I replace class loader from Yii2 to composer class loader. It's possible for my application, but I'm not sure about Yii2 internal modules. So I will try and then leave feedback for you.

**Comment by lisachenko** [comment]
Ok, could I ask you to write about results if possible, interesting to learn how to make it working for Yii2 too.

**Comment by erickskrauch** [comment]
@lisachenko I finally got the solution for integrating GoAOP framework with Yii2.

Follow next steps to make it work:

1. Ofcource install it via composer:

```bash
composer require goaop/framework
```

2. Next, modify your `composer.json`. You must take care of autoloading to composer:

```json
{
    "name": "yii/project",
    "require": {
        "yiisoft/yii2": "2.0.13",
        "goaop/framework": "^2.1"
    },
    "autoload": {
        "psr-4": {
            "api\\": "api",
            "common\\": "common",
            "console\\": "console"
        }
    }
}
```

3. Then you must dump new autoload:

```bash
composer dumpautoload 
``` 

4. Then you need to create Aspect Kernel (my main application code placed in app directory, so I use it as base):

```php
<?php
namespace api\aspects;

use Go\Core\AspectContainer;
use Go\Core\AspectKernel;

class ApiAspectKernel extends AspectKernel {

    protected function configureAop(AspectContainer $container) {
        $container->registerAspect(new TestAspect()); // For example
    }

}
```

5. Then you need to modify your `{app}/web/index.php` file:

```php
<?php

use api\aspects\ApiAspectKernel;
use common\config\ConfigLoader;
use yii\web\Application;

require __DIR__ . '/../../vendor/autoload.php';

defined('YII_DEBUG') or define('YII_DEBUG', in_array(getenv('YII_DEBUG'), ['true', '1']));
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV'));

// Initialize an application aspect container
ApiAspectKernel::getInstance()->init([
    'debug' => YII_DEBUG,
    'appDir' => __DIR__ . '/../../',
    'cacheDir' => __DIR__ . '/../runtime/aspect',
    'excludePaths' => [
        __DIR__ . '/../runtime/aspect',
        __DIR__ . '/../../vendor',
    ],
]);

require __DIR__ . '/../../vendor/yiisoft/yii2/Yii.php';
spl_autoload_unregister(['Yii', 'autoload']); // This will disable Yii2 autoloader.
require __DIR__ . '/../../common/config/bootstrap.php';
require __DIR__ . '/../config/bootstrap.php';

$config = ConfigLoader::load('api');

$application = new Application($config);
$application->run();
```

The most important thing is just call `spl_autoload_unregister(['Yii', 'autoload']);` to allow Composer take care of autoloading. Yii2 autoloader already removed in 2.1 branch https://github.com/yiisoft/yii2/pull/14761, but when it will be released - no one knows.

------------------

So, this solution worked for me and my application. If I missed something, feel free to ask me more details.

**Comment by lisachenko** [comment]
Thank you, @erickskrauch!

It's very detailed and easy reproducible how-to :) This issue will help other Yii2 developers to start working with AOP framework!

**Comment by lisachenko** [comment]
@TheCelavi it would be nice to have this post as-is in documentation :)

**Comment by TheCelavi** [comment]
Yes, will do.
