### ISSUE TITLE
Proposal: ORM to test

### ISSUE THREAD

**Issue by francescobianco** [goaop/framework#366]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by lisachenko** [comment]
Hi! Why do I need to check your project? It doesn't relate to AOP framework at all and I don't need such functionality in my framework.

Closing as irrelevant.

**Comment by lisachenko** [comment]
Just've given your project one star to support open-source project 👍
