### ISSUE TITLE
[Question] Class annotation

### ISSUE THREAD

**Issue by williamokano** [goaop/framework#367]
Is it possible to annotate a class and propagate it to all methods automatically?

Using a "real" scenario, imagina que `Cacheable` annotation from the demo.

Works fine if I annotate a method with it, as the `CacheAspect` is `@Around`. Fine.

But imagine that I want is that the whole class methods to be `Cacheable`, I will have to go, one by one, annotating all methods with `@Cacheable`.

Is it possible to "propagate" the class annotation (or even using it) or there's a more clever, and probably correct, way to do it?

Thanks in advance

**Comment by TheCelavi** [comment]
Class name matched? Don't use annotations, match all methods of class. There is example in documentation similar to this request.

**Comment by williamokano** [comment]
Not exactly what I want. It's possible to match by class name, but with annotations would be better.

Imagina that I want this behavior across several classes, the aspect would be huge.

**Comment by lisachenko** [comment]
@williamokano what you need is to mark your annotation class for classes (see doctrine @Target option) and after that define the pointcut: `@within(Some\CacheableClass) && execution(* **->*(*))`

This pointcut reads as following: execution of any dynamic method in a class marked with annotation "Some\CacheableClass" in any namespace.

**Comment by TheCelavi** [comment]
Go AOP is in accordance with AspectJ syntax for matching (more or less) and they don't have this implemented. That fact doesn't help you, of course, I am just stating the reason why is not initially implemented.

In general, if there is a way to achieve same result, usual practice for open source project is not to implement requested feature if there is no pressure from the larger number of users. You have to understand that - every new line of code means maintanance and support, which is quite difficult, especially with projects that have small number of maintainers (regardless of the fact of how awesome project is :-) )

I am sorry for not being more of help to you. If you want to implement this feature and send PR, I would advise you to discuss with Alexander about that first, just to check if you are in same page.

**Comment by TheCelavi** [comment]
@lisachenko s*** - didn't know you could do that!

**Comment by lisachenko** [comment]
@TheCelavi 😆 👍

**Comment by lisachenko** [comment]
@TheCelavi liked your long description about how it can be complex and how it could be implemented via PR :) It have made my Friday ) Thank you!

**Comment by williamokano** [comment]
Nice, thanks, I think it solves my problem. About the pull request, it's exactly what I wanted to do if it was not possible to do.

**Comment by lisachenko** [comment]
@williamokano you are welcome! Any contributions are appreciated!

**Comment by TheCelavi** [comment]
@lisachenko Oh, s***ew you! - you make me look bad :P all the info about best features you are keeping for your self :D 

Needs to be documented, though... it is far from obvious that it is possible to target class within annotation. I have read AspectJ specs and as far as I can remember, there were no documented similar possibility there either. 

And it is true - for open source project new features should always be introduced carefully - someone has to take care for that baby afterwards.
