### ISSUE TITLE
can not open the demos

### ISSUE THREAD

**Issue by Akrisllen** [goaop/framework#375]
Hi, I just start program. When I download the source code of go-aop and try to open the demos/index.php, a error pop out
![image](https://user-images.githubusercontent.com/9218811/33884168-9cbdfe50-df79-11e7-9d57-033a1a4cdf10.png)
what should I do......

**Comment by lisachenko** [comment]
HI!

First of all: use composer for installation via `composer require goaop/framework`. I can see strange path in your trace: lisachenko/go-aop-php. How it was created?

Next: be sure that you are installing it as top-level project, otherwise demo classes won’t be loaded (production mode)

**Comment by Akrisllen** [comment]
I created a composer.json requiring for"lisachenko/go-aop-php": "*"under the project and run it. And all the packaged are installed in vendor file... I will try to put it in the top-level..

**Comment by lisachenko** [comment]
Easiest way to do this is to make clean folder and then run in it: `composer create-project goaop/framework`. After that open `demos` folder in your browser (this can require configuring your web server root directory)

**Comment by lisachenko** [comment]
@Akrisllen have you configured working demo?

**Comment by Akrisllen** [comment]
I have successfully run it!!! I put the demo under the root project updated PHP to version 7.1. It ran successfully!! This is such a wonderful PHP AOP library!!! Thanks for all your work!!!

**Comment by lisachenko** [comment]
@Akrisllen Great! Enjoy it!
