### ISSUE TITLE
Can I use absolute path instead using namespace?

### ISSUE THREAD

**Issue by Akrisllen** [goaop/framework#377]
Hi, I notice that in your examples you declare a namespace 'namespace Demo\Example' and use the name space while creating instances of these examples. Is it possible to include the absolute path when I want to create the instances?

When I tried to use include instead of namespace, the demo can not run successfully....
`// use Demo\Example\LoggingDemo;`
`include_once 'D:/eclipsePHP/workplace/goaop/demos/Demo/Example/LoggingDemo.php';`

**Comment by lisachenko** [comment]
Hi, using concrete includes is considered as bad deprecated practice. You should delegate this job to autoloader and switch to PSR-0 or PSR-4 standards and Composer for class loading, otherwise framework won't be able to intercept autoloading process and perform weaving of advices.
