### ISSUE TITLE
[Support] Aspect within PHPUnit Test 

### ISSUE THREAD

**Issue by reinfi** [goaop/framework#386]
Hey,

I need your help, but I'm not sure if it is more a case of the zend module or the aop core.

I have an aspect registered via zend module which have a dependency A.
Now I'm writing a "functional" test for a route and want to replace the dependency A with a mock.

For ZF normally you register your mock in the service manager before executing any of to be tested code. In my case this is not possible as usual because I have a listener which also has dependency A and is instantiated at application init process. For that point I replace a variable within the dependency at a later point before executing my test code.

When I make the first call to set the value within dependency A it works within the aspect. But following calls do not change the value again.

```php
class SecurityAspect implements Aspect
{
    private $a;

    public function __construct($a) 
    {
        $this->a = $a;
    }

    /**
     * @param MethodInvocation $invocation
     * @Around("@execution(SecurityAspectAnnotation)")
     */
    public function checkPermission(MethodInvocation $invocation)
    {
        // do something 
    }
}
```

```php
    /**
     * @test
     */
    public function itTestsSomething()
    {
        $this->setVariable('value');

        $this->dispatch('/test');

        $this->assertResponseStatusCode(Response::STATUS_CODE_200);
    }

    protected function setVariable($user)
    {
        $a =  $this->getApplicationServiceLocator()->get(A::class);

        // This can not be done with prophecy because listeners already load the service.
        $reflClass = new \ReflectionClass($a);
        $userProperty = $reflClass->getProperty('user');
        $userProperty->setAccessible(true);
        $userProperty->setValue($a, $user);
    }
```

Hope this is some how understandable otherwise I need to show more code.
Any idea how to solve this problem, beside running every test in a separate process?

Thanks again for your support.

**Comment by reinfi** [comment]
I found out that the dependency A is always the same object, even though it is a completely new test.

TestClass 1:

Aspect - object hash of A: 00000000007eee0c000000001ef7b297
Service - object hash of A: 00000000007eee0c000000001ef7b297

TestClass 2:

Aspect - object hash of A: 00000000007ee**e0c**000000001ef7b297
Service - object hash of A: 00000000007ed**d67**000000001ef7b297

That is of course the reason why the value never changes, but why is it?

**Comment by reinfi** [comment]
Interesting fact is that the following code shows in the debugger that the variable has the correct value.

```php
$aspect = $this->getApplicationServiceLocator()
            ->get(AspectContainer::class)
            ->getAspect(SecurityAspect::class);
```
So it is set correctly within the aspect but not in the called joinpoint method (or how ever this should be named).

**Comment by lisachenko** [comment]
Hi, @reinfi!

I have not much knowledge with Zend unit-testing, could you elaborate more, what is expected and what was received?

In PHP object hash can be reused if previous object is destroyed, see https://3v4l.org/lBGIY for example.

Your issue looks like very specific edge case for functional testing with enabled AOP. All good AOP practices are advising to test app without enabled aspects and aspects are tested separately.

**Comment by reinfi** [comment]
First: Yes, maybe it is a good way to disable aop for testing purposes. I think I will go that way beside what comes up of this issue.

I try to describe more what would be expected behaviour.

TestCase A:
testMethod 1:
   initialize di container with service C which has a class variable D
  registered aspect E with dependency C 
  begin test
    overwrite class variable D in C with a value X
    aspect E's dependency C has the correct value X
testMethod 2:
   initialize di container with service C which has a class variable D
  registered aspect E with dependency C 
  begin test
    overwrite class variable D in C with a value Y
    aspect E's dependency C has the correct value Y when pulled from aop container
   aspect E invoke of joinpoint has dependency C with previously set value X 

Does this make it clearer?
I have no idea why the first setter changes the value correctly, next call does not change anything in the invoked aspect but has changed the value in the aspect pulled from aop container.

Totally confusing :)

**Comment by lisachenko** [comment]
All aspects are registered globally/statically (each advice in AOP kernel is an instance of `Closure` bound to the concrete instance of aspect in runtime, so it wouldn't update on next calls). Thus you couldn't change aspect dependencies between two separate test cases.

Only possible solution is make you php unit test isolated, so each test case will have it's own kernel with specific aspect.

Another possible solution is to add some setters into aspect class E/ dependency class C to have an ability to adjust their values in runtime.

**Comment by reinfi** [comment]
good, that was the answer I needed so it is just the desired behaviour of the aop engine.

Running each test isolated would be a solution but that increases the runtime to a not acceptable amount.

Setters just for tests sounds a bit weired :-) 

So I gonna go with the disabled aop engine for my tests.
