### ISSUE TITLE
Retrieve private properties in the class via MethodInvocation

### ISSUE THREAD

**Issue by roukmoute** [goaop/framework#390]
I would like to know how to retrieve a private property of my class from the `MethodInvocation` interface.
I've tried via `$reflectionClass = new \ReflectionClass ($invocation->getThis ()); ` but this is the class that has been cached.
So I don't have direct access to these properties.
Do you have any idea how I could do that?

Thank you in advance

**Comment by TheCelavi** [comment]
>  but this is the class that has been cached.

You mean, you get reflection for proxy class, example: `MyClass__AopProxied` ?

Have you tried:

`$reflectionClass = new \ReflectionClass ($invocation->getThis ())->getParentClass();` 

?

**Comment by lisachenko** [comment]
@TheCelavi it's correct solution

This should also work:
```php
$invocation->getStaticPart()->getDeclaringClass()->getProperties();
```

**Comment by roukmoute** [comment]
Thanks for your rapidity!

I have taken the second solution.

I've just discover AOP, thanks for your library, it's so impressive!
