### ISSUE TITLE
Can I use goaop in Bitrix Framework?

### ISSUE THREAD

**Issue by log95** [goaop/framework#392]
Hi, I use bitrix and want to know: may I use goaop in bitrix? I tried to make simple example: add new entry in file before execution of the function, but no effect. No errors, no new entry in file. May be because of Bitrix autoloading or something else.

**Comment by lisachenko** [comment]
Hi!
Unfortunately, I couldn't help you with Bitrix, it's a commercial product, so you should check this yourself.

**Comment by lisachenko** [comment]
BTW, I don't recommend you to use Bitrix + GoAOP in one place )
