### ISSUE TITLE
Integration with Swoole is not working

### ISSUE THREAD

**Issue by wuchuguang** [goaop/framework#399]
use in swoole 1.9 
report  :  服务器进程异常退出 WORKER Error {"worker_id":3,"worker_pid":31023,"exit_code":0,"message":null}

**Comment by lisachenko** [comment]
Hello, could you please describe all steps to reproduce this issue? E.g. config files, list of aspects, version of PHP, etc?

**Comment by lisachenko** [comment]
As I can see, worker was exited with code 0, it's normal termination of process (no errors)

**Comment by foolishnoob** [comment]
hello,i have successfully integrated goaop/framework into swoole 2.x and 4.x . would you like describe your problem details ?

**Comment by lisachenko** [comment]
Ok, I'm closing this issue, because @foolishnoob successfully uses this framework with Swoole.
