### ISSUE TITLE
Update `goaop/parser-reflection` dependency to 2.0+

### ISSUE THREAD

**Issue by ddinchev** [goaop/framework#403]
I'm trying to use a new version of `phpstan` which requires `nikic/php-parser:^4.0`. However, I'm also using AspectMock, that depends on this framework - `goaop/framework:~2.2`, which depends on `goaop/parser-reflection:~1.4`, which uses `nikic/php-parser:^3.0` 🙃 

I saw that you already released `goaop/parser-reflection:2.0.0` which uses the latest `php-parser` (4.0) - would it be relatively painless to let `goaop/framework` use that latest version of `parser-reflection`, hopefully without introducing BC and without need to release a major new version of the framework?

**Comment by lisachenko** [comment]
Hi, @ddinchev 

I will check, if it's possible to do for 2.x version of framework.

**Comment by lisachenko** [comment]
I've pushed 925f01d77b1a8f1859238f5596b8d2e7eccfb452  into the 2.x branch with new version of `goaop/parser-reflection`, could you please try to require `goaop/framework:2.x-dev`? If everything will work for you, I'll prepare a release for that.

**Comment by ddinchev** [comment]
Thanks a lot for this, can confirm that it is working fine for me! 👍

**Comment by lisachenko** [comment]
I'm not sure if it's ok to release it as 2.3.0, because it breaks BC, as PHP>=7.0 will be required for 2.x branch for now. 🤔

**Comment by lisachenko** [comment]
Let's proceed with 2.3.0, but im emergency case, I'll revert this and release 2.3.1 with previous version.

**Comment by lisachenko** [comment]
Resolved in https://github.com/goaop/framework/commit/925f01d77b1a8f1859238f5596b8d2e7eccfb452
