### ISSUE TITLE
Support for cflow and cflowbelow pointcuts

### ISSUE THREAD

**Issue by tonix-tuft** [goaop/framework#405]
I was just wondering if the framework offers the possibility of using `cflowbelow` (couldn't find an example in the docs and in the [Quick Pointcut Reference](http://go.aopphp.com/docs/pointcut-reference/)) and, if supported, `cflow` pointcuts.

Thank you!

**Comment by lisachenko** [comment]
Hi, @tonix-tuft! Framework actually has dynamic pointcuts that can be checked in the runtime, but I can't see real value in them, for PHP it's quite hard to implement real `cflow` and `cflowbelow` that will match any joinpoints (including property access, instance initialization, etc).

You can have a look at [CFlowBelowMethodPointcut.php ](https://github.com/goaop/framework/blob/master/src/Aop/Pointcut/CFlowBelowMethodPointcut.php)

And one more reference for you: [PointcutParserTest.php](https://github.com/goaop/framework/blob/master/tests/Go/Aop/Pointcut/PointcutParserTest.php#L58-L124)

**Comment by lisachenko** [comment]
Could you describe why do you need such pointcuts in PHP, it will be interesting to know your opinion about that.

**Comment by tonix-tuft** [comment]
Thank you for the links @lisachenko!

I was thinking about the possibility of implementing a sort of automatic code quality checker asserting whether a given code obeys to the Law of Demeter or not (e.g. lets call it `LawOfDemeterCheckerAspect`).

I once read some interesting uni papers regarding the topic which can be found on the following links:

[http://www.cs.virginia.edu/~lorenz/papers/aosd2003lod/aosd2003lod.pdf](http://www.cs.virginia.edu/~lorenz/papers/aosd2003lod/aosd2003lod.pdf)
[http://www.iro.umontreal.ca/~dufour/pubs/oopsla04.pdf](http://www.iro.umontreal.ca/~dufour/pubs/oopsla04.pdf)

The papers deal with AspectJ and provides an example of implementation.

I was just thinking if it could be possible to emulate such a behaviour in PHP and create an aspect which analyses call frames and tells if the Law of Demeter has been violated or not for a given join point.
Though the idea is a bit outlandish and I do not know whether it is possible or not yet, the authors also claim that even AspectJ should be extended in order to express some of their ideas letting them implement such a feature, so I guess it is not.

But I don't really know if something is possible or not until I give it a try. It is just my thoughts anyway, I am gonna investigate further and see if I will come up with something someday.

What do you think?

**Comment by lisachenko** [comment]
Hi, @tonix-tuft! I've analysed your idea and can confirm that it's possible to do for methods and functions (where you have a trace). You could try to look at current `cflowbelow` implementation, it can help you with dynamic analysis.

Steps to do: 
  - write your own `Pointcut` Implementation that returns `PointFilter::KIND_DYNAMIC` flag from its `getKind()` method call.
  - add it to the grammar (you can temporary reuse  `cflowbelowPointcut` AST node in the `PointcutGrammar` class and return your class instead)
  - Check the trace in runtime when `matches()` method of pointcut will be called with 3rd and 4th arguments. 
  - profit 😃

**Comment by tonix-tuft** [comment]
Thank you for your insight @lisachenko! It is great to receive your opinion regarding this topic. I will give it a try and let you know if I come up with something! :)

**Comment by lisachenko** [comment]
Ping @tonix-tuft I want to close this issue, because there are no related PRs and discussions for long time.

**Comment by tonix-tuft** [comment]
Yes, no problem. I'll close it.
