### ISSUE TITLE
Release 2.3.0 not available using packagist.

### ISSUE THREAD

**Issue by icanhazstring** [goaop/framework#408]
@lisachenko the current release `2.3.0` is not available through packagist.
There might be a minor hickup.

If you try to require `^2.3` you will get `dev-2.x` which is not a stable channel.
Could you please try to trigger packagist update? 😉

**Comment by lisachenko** [comment]
I can guess that this issue related to the updated GitHub hooks system, let me check this on Packagist side.

**Comment by lisachenko** [comment]
```
Completed at 2019-01-16 18:16:34 UTC, retry hook sync.

10 hooks setup/updated

1 hooks already setup and left unchanged
```

Looks good now )

**Comment by icanhazstring** [comment]
So I can update phpdeal now. Thanks.
Closing it. 😉
