### ISSUE TITLE
Supported PHP Version

### ISSUE THREAD

**Issue by icanhazstring** [goaop/framework#409]
Hi @lisachenko for version `2.3.0` you added a comment:

> Please, be aware that #403 bumps the PHP minimum version for 2.x branch to be >=7.0.0. As minimum supported PHP version now is 7.2, I decided to drop 5.6 for 2.x branch too.

Looking into the `composer.json` tho. The lib is still supporting `php: >=5.6`.
Is intentionally? Or should this be replaced by `7.0` or even `7.2` since support for `7.1` is only security patches and will also end this year.

**Comment by lisachenko** [comment]
Hi, @icanhazstring! Minimum PHP version for the 2.x branch should be bumped to `~7.0`. But I haven't bumped it intentionally to see if someone complain about BC break.

You could send a PR to the `2.x` branch to bump this version.

**Comment by icanhazstring** [comment]
@lisachenko thanks for the info. Will do.

**Comment by lisachenko** [comment]
Fixed in #410
