### ISSUE TITLE
BeforeMethod Not Executing

### ISSUE THREAD

**Issue by kavithlal** [goaop/framework#418]
I am facing this issue where in my logging aspect the construct is executing for every function (Models/Controllers methods) I call but the beforeMethod in the same logging aspect never gets executed. 

I am using Lumen 5.7. 

class LoggingAspect implements Aspect
{
  
    private $logger;
   public function __construct()
    {
      echo 'Calling Before Interceptor for method:';
    }

    
    public function beforeMethod(MethodInvocation $invocation)
    {
         $this->logger->info($invocation, $invocation->getArguments());
         echo 'Calling Before ';
        
     }
}

Whenever I call any method defined in the controller, construct() gets executed while beforeMethod is never executed . Why is this happening ?

**Comment by lisachenko** [comment]
Hi, @kavithlal! Have you registered an aspect? It should be tagged and loaded. Please, check if it's registered correctly.

**Comment by lisachenko** [comment]
Also, I can't see definition of pointcut for your `beforeMethod` method. Could you please provide it too? Maybe you have an error in pointcut definition or just forget to add it at all?

**Comment by lisachenko** [comment]
Ping
