### ISSUE TITLE
[Bug] initialization pointcut makes other advices not bound to target

### ISSUE THREAD

**Issue by l00k** [goaop/framework#425]
```
class MonitorAspect
    implements Aspect
{

    /**
     * @Before("execution(public App\Example->*(*))")
     */
    public function beforeMethodExecution(MethodInvocation $invocation)
    {
        $obj = $invocation->getThis();
        echo 'BEFORE: ',
            is_object($obj) ? get_class($obj) : $obj,
            $invocation->getMethod()->isStatic() ? '::' : '->',
            $invocation->getMethod()->getName(),
            '()',
            ' with arguments: ',
            json_encode($invocation->getArguments()),
            PHP_EOL;
    }

    (... other pointcuts)

    /**
     * @After("initialization(App\Example)")
     */
    public function initialization(ReflectionConstructorInvocation $invocation)
    {
        $obj = $invocation->getThis();
        echo 'INIT: ',
            get_class($invocation->getThis()),
            PHP_EOL;
    }

}
```
If I add `initialization` pointcut to aspect it makes only this one executed.
Also class is changed to `App\Example__AopProxied` (normally in methodInvocation I get `App\Example`).

For `staticinitialization` it works ok - nothing wrong happens. But If I add `initialization` targeting same class as other advices it makes all those advices stop working - only initialization is executed.

**Comment by lisachenko** [comment]
Hello, thank you for reporting this.

Unfortunately, **initialization** joinpoint is one of the most tricky, thus not reliable part of framework and requires to process all files with `new` keywords, because without extension it's impossible to mock an object initialization properly.

**Comment by lisachenko** [comment]
I'll try to have a look into this issue, maybe it isn't so complicated...

**Comment by l00k** [comment]
It could be fixed with some workaround - call to other method in constructor.
However I think it would be nice to have it built in.

BTW. Your framework is awesome, thanks for you time!

**Comment by l00k** [comment]
I have prepared bugfix for that issue. Pull request created.
#427
However I don't have required knowledge about project to know all related parts that may be influenced with that change.
Better just check my solution and wrote your own, maybe based on my one.

I have tested it in my sandbox project.

Also I see that master branch has lot of changes wiht comparsion to 2.x branch. When do you plan make next release?

**Comment by lisachenko** [comment]
I've being checked the code right now. Do you use a construction `$value = new self()` in your source code?
This can be related to the #415, #420 and #397. I have a guess that two code visitors/transformers just override result of each other, thus can produce invalid source code...

**Comment by l00k** [comment]
No, it was used outside of class.
`$obj = new Sample();`
Just simples possibile - do you mean you can't reproduce?

**Comment by lisachenko** [comment]
> Just simples possibile - do you mean you can't reproduce?

I've reproduced this. But things are worse when using `self` keyword with initialization pointcut.

**Comment by lisachenko** [comment]
Please, test 2.x or master branch to confirm that this issue is fixed now.
