### ISSUE TITLE
HI!,Yaf framework Combination of Usage Issues

### ISSUE THREAD

**Issue by ak47f16200** [goaop/framework#432]
Configured by example, it never worked.

` /**
     * Method that advice to clean the teeth before going to sleep
     *
     * @param MethodInvocation $invocation Invocation
     * @Before("execution(public IndexController->*(*))")
     */
    protected function testBeforeIndex(MethodInvocation $invocation)
    {
        echo 'before ----<br />';
    }`

How should annotation rules be written?

**Comment by lisachenko** [comment]
Hi, how you've added Go! AOP initialization into your app? Because, it can affect the integration. You should use composer and not local `include` or `require` keywords.

**Comment by lisachenko** [comment]
Closed by inactivity
