### ISSUE TITLE
New release with the latest goodies

### ISSUE THREAD

**Issue by jakzal** [goaop/framework#433]
I'm especially interested in https://github.com/goaop/framework/pull/412

**Comment by lisachenko** [comment]
Ok, let's proceed with 3.0.0.

Because I'm already developing the [lisachenko/z-engine](https://github.com/lisachenko/z-engine) that should be the a new engine for the goaop v4.0.

**Comment by lisachenko** [comment]
3.0.0-RC1 is ready

**Comment by jakzal** [comment]
Works on my project, thank you! 🍺

**Comment by lisachenko** [comment]
You are welcome! Ping me in one week to release a stable tag if everything will be ok )

PS I’m curious: do you use this framework in big project/enterprise environment? Or it’s your personal project/small app?

**Comment by jakzal** [comment]
I use it in a phpunit extension which i haven't open sourced (yet).

I'd have many more use cases for this project if phpunit used autoloading to load test cases ;)
