### ISSUE TITLE
PHP7.4 compatibility

### ISSUE THREAD

**Issue by ddinchev** [goaop/framework#434]
The framework is not compatible with PHP7.4 as there are some changes of the declarations of PHP classes which this framework extends - for example `ReflectionMethod::getClosure()`. The PHP 7.4 build on Travis has been failing for a while:
https://travis-ci.org/goaop/framework/jobs/608133230

I'm not entirely sure what would be a good solution to the above issue. Maybe, the same class can be defined depending on the PHP version?

**Comment by lisachenko** [comment]
Hi, @ddinchev! There should be some workaround, because otherwise this fail will break everything.

**Comment by lisachenko** [comment]
Changing signature to the `public function getClosure($object = null)` solves this issue for active versions of PHP: https://3v4l.org/vRnFP

This bug should be solved in `goaop/parser-reflection`

**Comment by ddinchev** [comment]
Good point, then the fix is trivial. I didn't realise that `public function getClosure($object = null)` wouldn't raise the same warning (incompatible declaration) for versions pre 7.4

**Comment by lisachenko** [comment]
Merged PR https://github.com/goaop/parser-reflection/pull/98
