### ISSUE TITLE
Pointcut on an interface

### ISSUE THREAD

**Issue by bartvanhoutte** [goaop/framework#435]
I'm wondering if there is a way to add a pointcut on an interface, I can't seem to get it to work.

Fictitious example: `execution(public Psr\Log\LoggerInterface->emergency(*))`.

In this case, a join point would be called every time the function `emergency` is called on a subclass of `Psr\Log\LoggerInterface`.

**Comment by lisachenko** [comment]
Try this one: `execution(public **->emergency(*)) && within(Psr\Log\LoggerInterface+)`

**Comment by bartvanhoutte** [comment]
Works like a charm, thank you for the quick response!

**Comment by bartvanhoutte** [comment]
@lisachenko Might be a good example to put in the [documentation](http://go.aopphp.com/docs/pointcut-reference/).
