### ISSUE TITLE
Symfony 5.0 support

### ISSUE THREAD

**Issue by kix** [goaop/framework#436]
Currently Go AOP cannot be used in a Symfony 5.0 based project, since this:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - goaop/framework 2.3.3 requires symfony/finder ^3.4|^4.2 -> no matching package found.
    - goaop/framework 2.3.2 requires symfony/finder ^3.4|^4.2 -> no matching package found.
    - goaop/framework 2.3.1 requires symfony/finder ^3.4|^4.2 -> no matching package found.
    - goaop/framework 2.3.0 requires symfony/finder ^3.4|^4.2 -> no matching package found.
    - Installation request for goaop/framework ^2.3 -> satisfiable by goaop/framework[2.3.0, 2.3.1, 2.3.2, 2.3.3].
```

Could we probably add `symfony/finder@^5.0` also?

**Comment by lisachenko** [comment]
Hi! I'm afraid that goaop is not compatible with symfony5... Could you please try to update to symfony/finder v5? If it will work for you, then you can send a PR

**Comment by TonySchmitt** [comment]
I have created this PR : https://github.com/goaop/framework/pull/440/

I have no error with symfony 5.

**Comment by lisachenko** [comment]
Resolved with #440

**Comment by lisachenko** [comment]
But still, please remember that Symfony and Go! AOP can not play well together due to complexity of both frameworks. 

#440 allows installation of `symfony/finder` v5 component, which is logical if you have some dependencies on SF component but do not use SF framework itself.

**Comment by kix** [comment]
@lisachenko @TonySchmitt Thanks!
