### ISSUE TITLE
Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by eenchev** [goaop/framework#438]
Running on PHP 7.4, this line throws exception:
https://github.com/goaop/framework/blob/b39293743d69722d9bb557804d29bf1315d73e79/src/Proxy/ClassProxyGenerator.php#L233
We should replace the string casting with the getName() method on ReflectionType, or make sure we use the overloaded ReflectionType from goaop/parser-reflection library

**Comment by lisachenko** [comment]
Yes, it would be nice to move to new method to prevent deprecation errors.
