### ISSUE TITLE
Go AOP and Dependency Injection

### ISSUE THREAD

**Issue by jefferson-lima** [goaop/framework#448]
I would like to know how could I use Dependency Injection with AOP. I want my Aspects to have their dependencies injected through their constructors, as in:

```
class MyAspect implements Aspect {

  private $myDependency;

  public function __construct($myDependency) {
    $this->myDependency = myDependency;
  }
}
```

But I couldn't achieve that as I have to instantiate the Aspect class within the `configureAop` method.

**Comment by lisachenko** [comment]
See how it was done for Laravel DI for example: https://github.com/goaop/goaop-laravel-bridge You can make `configureAop` method empty and instead move initialization to the place, suitable for your framework, eg `boot` or something else, where you will grab all services tagged with aspect and register them.

**Comment by lisachenko** [comment]
Closing this as it is too old.
