### ISSUE TITLE
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] Couldn't find constant execution

### ISSUE THREAD

**Issue by ezimuel** [goaop/framework#449]
I'm trying to write an Aspect for intercepting `curl_exec()` execution in my classes.
I'm using the following code:
```php
use Go\Aop\Aspect;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\Around;

class CurlAspect implements Aspect
{
    /**
     * @Around(execution(**\curl_exec(*)))
     */
    public function aroundCurlExec(MethodInvocation $invocation)
    {
        echo "Before\n";
        $result = $invocation->proceed();
        echo "After\n";

        return $result;
    }
}
```
I receive the following error:
```
PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException:
[Semantical Error] Couldn't find constant execution, method CurlAspect::aroundCurlExec()
```
The error seems to be related with the annotation that I used `@Around(execution(**\curl_exec(*)))`, based on the suggestion by @lisachenko [here](https://github.com/goaop/framework/issues/188#issuecomment-65659430). I would like to apply this Aspect to all the namespaces, since I use `curl_exec()` in different classes.

**Comment by lisachenko** [comment]
@ezimuel You forgot to add quotes inside this pointcut expression :) This is why Doctrine was complaining about missing constant with the name `execution`
