### ISSUE TITLE
CachingTransformer breaking PHP code w/invalid replacements

### ISSUE THREAD

**Issue by benjamw** [goaop/framework#451]
I was trying to use Codeception to test a framework, and kept getting odd errors that I couldn't explain. It was saying there was a `[ParseError] syntax error, unexpected ''C:\Development\api-php-c' (T_CONSTANT_ENCAPSED_STRING), expecting ']'`
but in my code, that string was nowhere to be found.

I finally found it in the cached version of the file, which had the following code...
```php
	/**
	 * Returns an array of client information
	 *
	 * @return string[]
	 */
	private static function getClientInfoArray(): array { if (($__am_res = __amock_before(get_called_class(), __CLASS__, __FUNCTION__, array(), true)) !== __AM_CONTINUE__) return $__am_res; 
		return [
			'_client_type' => self::CLIENT_TYPE,
			'_client_ver' => self::CLIENT_VERSION,
			'_client_script''C:\Development\api-php-client\src\Client.php'=> $_SERVER['PHP_SELF'] ?? __FILE__,
			'_client_hostname' => $_SERVER['HOSTNAME'] ?? '',
			'_client_username' => static::getClientUsername(),
		];
	}
```

It seems the MagicConstantTransformer class tried to replace `__FILE__` with the actual file path, but when it did it, it got the `$node`/`tokenStream` position incorrect. Like it was using an older version of the `$metadata` which had been updated by a previous Transformer class, but didn't have it's token data updated after so the position was wrong.

**Comment by dudapiotr** [comment]
Downgrade to previous version helped:   "goaop/framework": "2.3.2"

**Comment by dudapiotr** [comment]
@lisachenko In newest version there is some bug, which provides  if statement at the beginning.
Came here from `aspect-mock` lib.

class StepStoneCommonBundle extends Bundle
{ if (($__am_res = __amock_before($this, __CLASS__, __FUNCTION__, array($container), false)) !== __AM_CONTINUE__) return $__am_res; 
    public function build(ContainerBuilder $container)
    {

**Comment by lisachenko** [comment]
Bug in general `nikic/php-parser` library, please downgrade it to <4.7.0.

**Comment by lisachenko** [comment]
Released a hotfix version of `goaop/parser-reflection` 2.1.3 that can be installed with `composer update goaop/parser-reflection`

**Comment by benjamw** [comment]
Neither the update of `goaop/parser-reflection` to 2.1.3, nor the downgrade of `goaop/framework` to 2.3.2 seem to be working for me, and the issues are still occurring.

**Comment by lisachenko** [comment]
@benjamw could you please provide your current versions of components from the composer.lock? Interested in php-parser, parser-reflection and framework itself.

Thanks!

**Comment by benjamw** [comment]
I'm running PHP 7.4.9
Composer 1.10.9

From my `composer.json` file:
```
        "codeception/codeception": "~2.5.6",
        "codeception/aspect-mock": "~3.0.2",
```

From my `composer.lock` file:
```
            "name": "goaop/framework",
            "version": "2.3.4",

            "name": "goaop/parser-reflection",
            "version": "2.1.3",

            "name": "nikic/php-parser",
            "version": "v4.6.0",
```

I finally did git it to work by adding 
```
        "nikic/php-parser": "4.2.5",
```
to my `composer.json` file.

I chose that version because it was the first one I found in [that package](https://github.com/nikic/PHP-Parser/releases) not to include PHP 8.0 features.

**Comment by benjamw** [comment]
Any update on this? It's still an issue.

**Comment by lisachenko** [comment]
@benjamw hmm, I’ve checked and can’t reproduce this issue. Is it possible for you to create a small reproducible case to debug it?

**UPD1**: Ideally, failing test case or simple repo to clone with one/two files in it?
