### ISSUE TITLE
Cache generated incorrectly from files when running AOP

### ISSUE THREAD

**Issue by kieronpeters** [goaop/framework#452]
<img width="521" alt="Screenshot_1" src="https://user-images.githubusercontent.com/51761129/90139653-91c67700-dd70-11ea-9fce-338879244091.png">
<img width="1226" alt="Screenshot_2" src="https://user-images.githubusercontent.com/51761129/90139659-925f0d80-dd70-11ea-99f5-89f97be557e2.png">

Above is the issue when it generates the files in the cache, the top one is the initial code, and then the bottom one it's putting the include_once here. If I juggle the functions around and remove them, it places it anywhere it feels like, the line endings might be causing the issue perhaps, but I'm not sure why it suddenly started to behave like this.

Could someone help with what might be going on here please? I am using the latest version and even rolled back to previous versions and still the same thing happens.

**Comment by lisachenko** [comment]
Hi, this is recent failure, need to investigate the root cause. Tests in master branch are failing too now. Probably, something happened in dependencies...

Could you please report versions of goaop/framework, goaop/parser-reflection and nikic/php-parser packages?

**Comment by lisachenko** [comment]
Somehow a class node from the goaop/parser-reflection points to another node, not a class. I’ll check this bug today in the evening as it blocks normal work.

**Comment by kieronpeters** [comment]
Okay thanks, I'll take a look at this as well but if you work anything out, I'll check for an update from you later.

**Comment by lisachenko** [comment]
Ok, as was expected. Problem now with `nikic/php-parser` library > 4.6.0. It reports incorrect token positions, for example, `endTokenPos`. And `goaop` just breaks existing code in a bad way...

@NikiC, probably bug was introduced somewhere in 4.7.0.

**Comment by lisachenko** [comment]
Temporary prepared new 2.1.3 patch release of `goaop/parser-reflection` with restricted version of php-parser. Please update with `composer update goaop/parser-reflection`
