### ISSUE TITLE
Incorrect Cache file 

### ISSUE THREAD

**Issue by moonsn** [goaop/framework#453]
this is my config:
```
$kernel->loadFile(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
```
and i got this file in the cacheDir:
file: `MyCacheDir/vendor/yiisoft/yii2/Yii.php` 
error on line 24

![image](https://user-images.githubusercontent.com/6897588/91158048-b0295c80-e6f8-11ea-8607-85aae69ff17f.png)

yii2 version is `2.0.36`

**Comment by lisachenko** [comment]
This is because of new version of `nikic/php-parser`. Please update `goaop/parser-reflection` to the latest patch version to fix this issue.

**Comment by moonsn** [comment]
> This is because of new version of `nikic/php-parser`. Please update `goaop/parser-reflection` to the latest patch version to fix this issue.

thanks，work for me. @lisachenko
