### ISSUE TITLE
cannot update goaop parser-reflection 

### ISSUE THREAD

**Issue by JeremyWaps** [goaop/framework#465]
Hi, 

We user codeception/aspectMock but we have some problems with goaop/parser-reflection.
When we tried to update goaop-parser-reflection, we have this message : 

> Running composer update goaop/parser-reflection
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - goaop/framework is locked to version 2.3.4 and an update of this package was not requested.
>     - goaop/framework 2.3.4 requires goaop/parser-reflection ~2.0 -> found goaop/parser-reflection[2.0.0, ..., 2.1.3] but it conflicts with your root composer.json require (^3.0).
>   Problem 2
>     - goaop/framework 2.3.4 requires goaop/parser-reflection ~2.0 -> found goaop/parser-reflection[2.0.0, ..., 2.1.3] but it conflicts with your root composer.json require (^3.0).
>     - codeception/aspect-mock 3.1.0 requires goaop/framework ^2.2.0 | ^3.0.0-RC2 -> satisfiable by goaop/framework[2.3.4].
>     - codeception/aspect-mock is locked to version 3.1.0 and an update of this package was not requested.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

How can we resolve this problem ?

**Comment by lisachenko** [comment]
Hello! This issue doesn’t relate to the framework itself.

Also, I want to mention that goaop/parser-reflection will be abandoned soon, so I’m working on migration to the BetterReflection package now to see if I can replace my version with maintained one.

Theoretically, you can still use ^2.0 version of goaop/parser-reflection. And one more check - it can be composer.lock related (try to remove your lock file first to see, if new version can be installed). If no - then wait a little bit when goaop/framework 3.0.0 will be released and update aspectmock dependencies.

**Comment by lisachenko** [comment]
Closing, as this is typical question regarding finding suitable dependencies versions.
