### ISSUE TITLE
Partipate to a benchmark

### ISSUE THREAD

**Issue by waghanza** [goaop/framework#470]
Hi,

Would you guys want to participate to https://github.com/the-benchmarker/web-frameworks ?

This project is about promoting OSS awesomeness through a list (and insight) about various frameworks, in many languages.

Regards,

**Comment by lisachenko** [comment]
I'm ok with this idea ) But my framework is not a web framework, it is very special one for PHP )

**Comment by waghanza** [comment]
What do you mean ?

**Comment by lisachenko** [comment]
I don't see how my framework can be compared with another web frameworks...

**Comment by waghanza** [comment]
You're benchmark fulfill a goal. The approach is, indeed not the same a wide majority of framework, but tho comparison is useful for me.

- Since implementation could be written differently, and could be loved by some techies
- Since there is surely some advantages of using AOP

Disclaimer : Only performances are checked, as for now, but plan to check other metrics
