### ISSUE TITLE
2.3.4 framework exception type with error type

### ISSUE THREAD

**Issue by 137-rick** [goaop/framework#472]
hi sir 
it's old bug

T_T

please publish 2.3.5 version 

 Argument 1 passed to Go\Instrument\ClassLoading\CacheWarmer::Go\Instrument\ClassLoading\{closure}() must be an instance of Exception, instance of Error given, called in / vendor/goaop/framework/src/Instrument/ClassLoading/CacheWarmer.php on line 88

**Comment by 137-rick** [comment]
Expect to release soon T_T

**Comment by 137-rick** [comment]
$displayException = function (\Exception $exception, $path) use (&$errors) {
to
        $displayException = function (\Throwable $exception, $path) use (&$errors) {

**Comment by 137-rick** [comment]
T_T anybody ?

**Comment by lisachenko** [comment]
Merged and released 2.3.5

**Comment by lisachenko** [comment]
Resolved in #473
