### ISSUE TITLE
Is this library alive?

### ISSUE THREAD

**Issue by func0der** [goaop/framework#479]
Hey @lisachenko,

I am just checking to confirm that this library alive and kicking.

I just saw that you deprecated https://github.com/goaop/parser-reflection, but this library still depends on it.
This issue https://github.com/goaop/framework/issues/476 which has been open for half year has not gotten any traction even though it probably concerns a lot of people. This PR also addresses this issue (kinda): https://github.com/goaop/framework/pull/477

I do not want to sound unappreciative about your awesome work for the open source community in this very critical and difficult area of PHP.
On the other hand I have to consider the implications of using a library this complicated without having the proper support of the maintainers.

Could you please elaborate on the current status of the library and maybe its future?
Maybe you could get a co-maintainer on board?

Thank you for your efforts :) I hope to hear from you soon.

**Comment by lisachenko** [comment]
Hello, @func0der! Thank you for reaching me out. Indeed, I'm not investing too much time now to my OSS projects. I had some troubles with my health and also busy at my main work, thus no free time to keep development at previous level.

I really would like to have PHP>=8 support added to my framework and resolve existing issues, but I know that it will take a lot of my time just to migrate to BetterReflection first (it isn't directly compatible with my library - I've checked this already) and then to make framework supporting PHP8 features too.

So, if you can somehow help me with open tickets - it would be awesome. I really would like to have a co-maintainer on this project which can take care about modern development and open tickets/issues. Previously only me, @TheCelavi and @fduch were able able to work on framework's core as it wasn't trivial at all.

I can't promise anything, but want to have PHP8 support added. All core features are stable and don't require too much changes, only code reflection/generation part requires some time to be rewritten.

**Comment by TheCelavi** [comment]
@lisachenko what happened with new engine for AOP?

**Comment by lisachenko** [comment]
@TheCelavi new engine isn’t stable and I don’t want switch framework to something which can not be 100% stable, as this will affect existing users of framework. Thus, better to keep current userland version of AOP

**Comment by jimbonator** [comment]
We use AspectMock for unit testing, and have run into a few problems migrating from PHP 7.4 to PHP 8.1.  I'm trying to piece together what's needed for AOP to work in that later version.

It looks to me the current situation is:

* Ticket #466 is for migrating `goaop/framework` to PHP 8.  [This pull request](https://github.com/goaop/framework/pull/477) appears to be a start for that.
* (That said, I've been able to use `goaop/framework` w/o any changes in our PHP-Unit/AspectMock test suite.  The only thing I had to do was force Composer to ignore the PHP version requirement, see [here](https://github.com/Codeception/AspectMock/issues/202) for more information.)
* `goaop/parser-reflection` needs to be upgraded to work with PHP 8.x.  I can't find a ticket in that repo for it.  There are pull requests for that, but I don't see any progress on them.  I've submitted [my own pull request](https://github.com/goaop/parser-reflection/pull/121) that makes the bare minimum of code changes for the package to run under PHP 8.
* However, the discussion in this ticket and #466 seems to indicate there's a desire to drop `parser-reflection` in favor of BetterReflection, although there's some work required to integrate the switch.

Would it be feasible to update `parser-reflection` for now, and minimally maintain it into the future, until the BR integration can be completed?  It seems like this would be the path of least resistance, and give projects depending on goaop a bridge forward.

**Comment by WalterWoshid** [comment]
I am currently refactoring the library to support PHP 8.0. See https://github.com/WalterWoshid/goaop-framework/issues/1 for progress information

**Comment by WalterWoshid** [comment]
Done https://github.com/goaop/framework/pull/486

**Comment by WalterWoshid** [comment]
Hello everyone,
Hello @lisachenko,

I hope it's okay if I mention it here, but I have released version `1.0.0` of [Okapi/Aop](https://github.com/okapi-web/php-aop), which is a AOP library, heavily inspired from goaop/framework. The minimum PHP version is `8.1` and also supports PHP `8.2`. It uses the new [PHP Attributes](https://stitcher.io/blog/attributes-in-php-8) and aims for easy usage and more functionality in the feature. Currently it only supports `Before`, `Around` and `After` advices, but there will be more!
