### ISSUE TITLE
Go! + ZF2 doesn't works

### ISSUE THREAD

**Issue by DenisSmirnov92** [goaop/framework#48]
I tried to use Go! + ZF2 and received fatal error:

 Cannot redeclare Go\Instrument\ClassLoading\ensureLibraryAutoloaderIsFirst() (previously declared in /home/denis/web/TulaCoFramework/tulaco-php-framework/vendor/lisachenko/go-aop-php/src/Go/Instrument/ClassLoading/composer.php:20) in /home/denis/web/TulaCoFramework/tulaco-php-framework/data/cache/aspect/vendor/lisachenko/go-aop-php/src/Go/Instrument/ClassLoading/composer.php on line 40

Maybe I configured something wrong?

**Comment by lisachenko** [comment]
This can be related to the bad configuration or caching. You can look at my https://github.com/lisachenko/zf2-aspect repository for an example how to use an aspects with ZF2

**Comment by DenisSmirnov92** [comment]
Yep, I actually used zf2-aspect like an example. I tried to set 'cacheDir' to null: exceptions was disappeared, however DemoAspects doesn't works. But your example works in both configurations: with enabled cache and without it. Do you have any guesses where I could make a mistake? Or, perhaps, the problem is related with conflict of your module with other, which I use in my project?

**Comment by lisachenko** [comment]
Can you show me your configuration of aspect kernel? Do you prepare a directory for cache?

**Comment by DenisSmirnov92** [comment]
I'm so sorry - it's my stupid mistake: after I merged the index.php I forgot to remove "include 'init_autoloader.php'". Thank you so much for your quick answers)

**Comment by lisachenko** [comment]
@GRblZLi You are welcome! ) BTW, can you share your experience about using Go! with ZF2. What are the use cases for AOP in you application?

**Comment by DenisSmirnov92** [comment]
I want to compare the performance between currently implemented listeners which realized through the event manager, and aspects which provides a similar functionality. The one simple example: check permissions into my API module. If your approach will be better, I plan to use it in the future.

**Comment by lisachenko** [comment]
@GRblZLi ok, thank you for sharing ) Let me know if you will decide to use AOP instead of listeners and performance will satisfy your needs.
