### ISSUE TITLE
http://go.aopphp.com

### ISSUE THREAD

**Issue by feamsr00** [goaop/framework#488]
Hi There!
Seems like the website is down. http://go.aopphp.com
![image](https://user-images.githubusercontent.com/983484/221899495-3e5c54af-d447-4c29-a9ee-ae1c8f4b1969.png)

Just needs a domain renewal?

**Comment by lisachenko** [comment]
Hello, thank you for reporting! Indeed, domain has been expired, need to renew...

**Comment by feamsr00** [comment]
Site is up! 👍
