### ISSUE TITLE
Resolve relative include paths when using cache

### ISSUE THREAD

**Issue by ghost** [goaop/framework#50]
![goerror](https://f.cloud.github.com/assets/612450/476041/e7b6c638-b7ad-11e2-812f-1cdfb78fa1c9.png)

**Comment by lisachenko** [comment]
Please, can you include a path to the cache dir, application dir and name of the included file? Is included file is present in filesystem? Are there any errors/fatals after warnings?

**Comment by ghost** [comment]
Applicaiton dir: <apachedir>/htdocs/dokuwiki/inc
Cache dir: <apachedir>/htdocs/dokuwiki/inc/cache

Which included file are you referring to?
There are no errors/fatals after warnings.

**Comment by lisachenko** [comment]
@gouthamcumar Oh, sorry. Included file is `..\dokuwiki\lib\tpl\dokuwiki\main.php` according to the trace. But it is not under the application directory `/htdocs/dokuwiki/inc`. I can suggest you to change the application directory in the aspect kernel to the `/htdocs/dokuwiki/` instead of `/htdocs/dokuwiki/inc`.

**Comment by ghost** [comment]
Will change it and let you know tomorrow... thnx

**Comment by ghost** [comment]
Does not help :( 

I modified the application directory as you suggested... but the warnings persist...

**Comment by lisachenko** [comment]
Hmm..What version of PHP and Go! library do you use? Is APC or similar cacher is used?
Can you add a line `if (!$cacheUri) var_dump($originalUri, $metadata);` before `file_put_contents()` in the `CachingTransformer` class to collect some debug information.

**Comment by ghost** [comment]
PHP version: 5.4.14
Go version: How do I get Go version?

"Is APC or similar cacher used?": I don't know the answer for this. I am working with an application that I downloaded from internet. It is called DokuWiki.

Here is the screenshot after putting your code in CachingTrasnformer.......

![goerror_vardump](https://f.cloud.github.com/assets/612450/481817/e24355a4-b875-11e2-9f86-d7ea4b736869.png)

**Comment by ghost** [comment]
![goerror_vardump1](https://f.cloud.github.com/assets/612450/481840/7a7c5f86-b877-11e2-985c-72492104f75e.png)

**Comment by lisachenko** [comment]
Thank you for a quick feedback )
So, there are problems with `tpl_header.php` and `tpl_footer.php`. Path is relative, but Go! executes this files from the cache and `stream_resolve_include_path` returns `false`. I understood the reason for this problem.

**Comment by ghost** [comment]
:) I should thank you for your quick responses.

Great that you have understood the root cause. What would be the solution for this?

**Comment by lisachenko** [comment]
Need some time to find the way to fix this issue, I'll make a patch for this.

**Comment by ghost** [comment]
Cool. Thanks.

**Comment by lisachenko** [comment]
Fixed in the master branch. But be aware, that there can be minor changes in the configuration comparing to the old version of library.
