### ISSUE TITLE
Receive the annotation on a Annotation pointcut

### ISSUE THREAD

**Issue by mpoiriert** [goaop/framework#66]
I would like to be able to configure annotation so behavior of the aspect is change base on the annotation parameters. To give a simple example with your Cacheable annotation:

@Cacheable(ttl=60)

From the invocation call I could access the annotation (how need to be determine) and I would be able to use the ttl value (time to live) to put a expiration on the cache.

**Comment by pravednik** [comment]
$container->registerAspect(new SomeAspect($container->get('aspect.annotation.reader')));

class SomeAspect {
    public function __construct(Reader $annotationReader)
    {
        $this->annotationReader = $annotationReader;
    }
}

**Comment by lisachenko** [comment]
Oh, cool ) Community for framework is the best source for FAQ and support )
@pravednik has already asked me earlier about this issue by email, so he has an answer:

AOP internally uses annotation reader from Doctrine that is available in the container. So you can pass it to an aspect constructor in the following way:

``` php
// SomeAspectKernel.php
public function configureAop($container)
{
    //...
    $container->registerAspect(new SomeAspect($container->get('aspect.annotation.reader')));
}
```

Then, in the concrete aspect just store this dependency in the class field:

``` php
class SomeAspect
{
    /**
     * Instance of annotation reader
     * @var Reader
     */ 
    protected $annotationReader = null;

    public function __construct(Reader $annotationReader)
    {
        $this->annotationReader = $annotationReader;
    }
}
```

Next step is to use [Doctrine Annotations API](http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html) to access a meta-information from reflection points:

``` php
// SomeAspect.php

/**
 * @Around("@annotation(Annotation\Cacheable)")
 * @param MethodInvocation $invocation Current joinpoint
 */
public function aroundCacheableAnnotattion(MethodInvocation $invocation)
{
    $cacheable = $this->annotationReader->getMethodAnnotation($invocation->getMethod(), 'Annotation\Cacheable');
    echo "Cached for {$cacheable->ttl}", PHP_EOL, "<br/>"
    // .. logic here
}
```

**Comment by mpoiriert** [comment]
The solution is kind of working but I have some issues...
1. It does complicate the code if we consider that it have been parse earlier, having the Annotation as a parameter or accessible via the method annotation will make it smaller and easier to develop.
2. Aspect/Annotation are already heavier on the load so being sure that we don't need to parse twice something is better.
3. What happen if you have 2 of the same annotations for the same method ? A simple (but not perfect) exemple would be

@NeededPermission("admin")
@NeededPermission("user")

Obviously this is not the best exemple but this is impossible to treat easily with the code mention above...

Would is be really hard to add the Annotation like I suggest ?

Thanks !

**Comment by lisachenko** [comment]
Just added an experimental support (in the separate branch) for reading an annotations from MethodInvocation:

``` php
use Demo\Annotation\Cacheable;
use Go\Aop\Aspect;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\Around;

class CacheAspect implements Aspect
{
    /**
     * Cacheable methods
     *
     * @param MethodInvocation $invocation Invocation
     *
     * @Around("@annotation(Demo\Annotation\Cacheable)")
     */
    public function aroundCacheable(MethodInvocation $invocation)
    {
        /** @var Cacheable $cacheable */
        $cacheable = $invocation->getMethod()->getAnnotation(Cacheable::class);
        echo $cacheable->time;
        return $invocation->proceed();
    }
}
```

Original class:

``` php
use Demo\Annotation\Cacheable;

class General
{
    /**
     * Test cacheable by annotation
     *
     * @Cacheable(time=10)
     * @param float $timeToSleep Amount of time to sleep
     *
     * @return string
     */
    public function cacheMe($timeToSleep)
    {
        usleep($timeToSleep * 1e6);
        return 'Yeah';
    }
}
```

However, be aware, that annotation reader is not using cache now, so parsing is expensive and slow.
