### ISSUE TITLE
Go\Instrument\ClassLoading\AopComposerLoader problem

### ISSUE THREAD

**Issue by pravednik** [goaop/framework#67]
Собственно.
Выкачал последнюю версию библиотеки, специально переписал приложение на использование автозагрузчика Composer'а, заинклюдил AopComposerLoader после его (Composer'а) инциализации. Ждал чуда. Чудо пришло :)
1. Всего до момента инклюда зарегистрировано 2 функции автозагрузки:
   \Zend_Loader_Autoloader
   Composer\Autoload\ClassLoader
2. После инклюда и собственно выполнения (автоматическое) остаётся лишь \Zend_Loader_Autoloader

Если слегка модифицировать код AopComposerLoader до состояния http://www.everfall.com/paste/id.php?u2zsb6z4f4o6 , то и \Zend_Loader_Autoloader, и Go\Instrument\ClassLoading\AopComposerLoader остаются в числе зарегистрированных. И всё прелестно работает. Иначе - неа, ибо зендовский автозагрузчик и неймспейсы дружат не сильно :)

**Comment by lisachenko** [comment]
Спасибо за репорт )

Вам не нужно самостоятельно подключать AopComposerLoader если используется только Composer, он подключится автоматически, у меня для ZF2 все работает корректно. Надеюсь, у вас ZF2? 
В любом случае, есть резервный вариант без использования Composer-а, но он не описан пока нигде, так как разработка 0.4.0 еще в процессе.

**Comment by pravednik** [comment]
Спасибо за оперативность.
Composer используется на уровне автозагрузчика, вбитого молотком. Т.е. он не сам его (автозагрузчик) генерировал. Я лишь сэмитировал все шаги. И уткнулся в такой вот момент

На счёт версии зенда, у меня нет возможности использовать второй
