### ISSUE TITLE
Use "doctrine/annotations" instead of "doctrine/common"

### ISSUE THREAD

**Issue by mpoiriert** [goaop/framework#69]
I saw that your are using doctrine/common but I think that you are just using the annotations library.

It would be cleaner to use the specific dependency and might solve future problem since composer will not be able to manage dependency properly (in fact doctrine should change how he made is hierarcy so common have a depency on annotation instead of having the library directly in it...)

**Comment by lisachenko** [comment]
Hi )
There is a reason for `doctrine/common` dependency: it can be used simpler without composer. For example, when using my library in the application that uses submodules. In that case `doctrine/common` < 2.4 is only single dependency and can be installed by adding only one submodule. `doctrine/annotations` depends on `doctrine/lexer` so installing by hand requires more work.

However, official way for my library is to use a composer and I'll update this dependency soon.
