### ISSUE TITLE
Error with class/file that have specific instruction at the end (ex: Propel1 model classes)

### ISSUE THREAD

**Issue by mpoiriert** [goaop/framework#71]
I'm using propel 1 in a project and I get a issue with the generated file.

At the end of the file propel call a static method on the current declared class. Since the class with the good name is appended to the class it cannot be found.

Here is a exemple of before and after:

```
//Before
class BaseFilePeer
{
}

BaseFilePeer::buildTableMap();


//After
class BaseFilePeer__AopProxied
{
}

BaseFilePeer::buildTableMap();

abstract class BaseFilePeer extends BaseItemPeer__AopProxied implements \Go\Aop\Proxy
{
}
```

I've tried modifying the WeavingTransformer to append the child class just after the first class but the ReflectionElement just give access to the last line of the class and not the 'char' position in the file (it's probably why you don't support 2 namespaces in files).

Do you have any suggestion because this is a big issue for my project...

**Comment by lisachenko** [comment]
Hi, it seems that the Propel violates PSR-1. My framework currently doesn't support such files. Can you add this directory to the ignore list for AOP? Or you need to use AOP for Propel models?

**Comment by mpoiriert** [comment]
I might use aop for the propel model but other thant that:
1. Many folders contain propel model, and external libraries might too
2. Folders also contain class that are not propel model...

Does make it harder to do a clean exclusion...

**Comment by lisachenko** [comment]
Yeap...Houston, we have a problem...

**Comment by lisachenko** [comment]
Nice bug report ) Thank you very much! 
BTW, how can I easily reproduce this issue? I'll try to found a way to solve it.

**Comment by mpoiriert** [comment]
From what I see juste creating a class with a static method that is call at the end of the file should trigger this issue.

**Comment by mpoiriert** [comment]
FYI, I'm doing my masters project by creating a framework that I can be use within other framework by creating bridge. I'm using your AOP implentation in the core of the framework. Other than regular usage of AOP, I'll be using it to create bridge for the other framework to be the less intrusive possible. I'm using it on a concreate project at my job... I'll probably open real use case issue often, I'll try to do patch when I can but at least I'll document the issues as much as possible...

**Comment by lisachenko** [comment]
Very interesting project! I'm sure that it will be awesome. Thank you one more time for so documented issues, I will try to fix them asap.
Unfortunately, I haven't much time for my project (it's just a hobbie) and can work only at weekends, so excuse me for any delays.

**Comment by worried-networking** [comment]
@mpoiriert can you retest the issue with latest dev version?

**Comment by mpoiriert** [comment]
@zvirusz I have a weird bug now... I see the file is generated properly (meaning that the aop proxied class is just bellow the child class. But I'm getting this error:

```
Fatal error: Class 'UgroupMedia\Pnp\Store\BundlePeer' not found in .\vendor\lisachenko\go-aop-php\src\Go\Proxy\ClassProxy.php on line 124
```

The way propel work is that we load a class child 

```
UgroupMedia\Pnp\Store\BundlePeer
```

that extends from 

```
UgroupMedia\Pnp\Store\om\BaseBundlePeer
```

That was the class (the _\om\Base_ one) causing problem since a static method call was at the end of the file.

Now the ReflectionProperty->setValue(**) call is causing this fatal error, but the class mention **UgroupMedia\Pnp\Store\BundlePeer** is not the one currently loaded having a aspect **UgroupMedia\Pnp\Store\om\BaseBundlePeer**

I don't know exactly whe the class **UgroupMedia\Pnp\Store\BundlePeer** is needed at the point and obviously it's not existing yet because we need to finish loadind the base call for php to register it in the **system**

Is this enough information ?

Here is the information of the php -v output 

```
PHP 5.4.11 (cli) (built: Feb 12 2013 14:09:16)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
    with Xdebug v2.2.2, Copyright (c) 2002-2013, by Derick Rethans
    with Zend Extension Manager v6.0.0, Copyright (c) 2003-2013, by Zend Technologies
    - with Zend Job Queue v6.0.0, Copyright (c) 2004-2013, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Session Clustering v6.0.0, Copyright (c) 2004-2013, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Utils v6.0.0, Copyright (c) 2004-2013, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Page Cache v6.0.0, Copyright (c) 2004-2013, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Monitor UI v6.0.0, Copyright (c) 2004-2013, by Zend Technologies [loaded] [licensed] [enabled]
```

**Comment by lisachenko** [comment]
@mpoiriert Please, disable ZendExtensions to test raw PHP code. There can be an conflict. Or just disable the debug mode for AOP kernel and clean the cache folder.

**Comment by mpoiriert** [comment]
After a lot of test I've found the problme.

When the ReflectionProperty->setValue() is call it does initialize all the static attribute of the class, Propel is using a constant on is child class (meaning BaseBundlePeer use BundlePeer to initialize is static property) since the class is not available yet it crash. Samething if you assign a value to a public static proterty.

The only way I see is by having a Registry responsable of the call that will be call instead. So the class with not hold the __joinPoints within itself. I didn't test this solution but I think it should work... but it may increase the processing time on the system...

It should be easy to develop and test but since it's a "major" change you should be the one who take the call on this... Let me know if you want me to the the solution just to know if it's working...

**Comment by lisachenko** [comment]
@mpoiriert Could you add an examples with source code to show the issue more detailed because from your previous comment I didn't understand what is wrong with current approach.

**Comment by lisachenko** [comment]
@mpoiriert any news here? Can I close this issue?

**Comment by mpoiriert** [comment]
Nop sorry, i ll try to give a example this week-end...
Le 2013-09-19 14:40, "Alexander Lisachenko" notifications@github.com a
écrit :

**Comment by lisachenko** [comment]
@mpoiriert If you will be able to reproduce a bug or weird behaviour, please, could you report it in the separate issue. I'm closing this issue as completed.
