### ISSUE TITLE
Cannot declare a method abstract if the method is already in a inerface (php 5.3.3)

### ISSUE THREAD

**Issue by mpoiriert** [goaop/framework#75]
The class Go\Aop\Framework\AbstractMethodInvocation declare the method 

```
abstract public function proceed();
```

That is already declare in the interface 

Go\Aop\Intercept\Joinpoint

You can see the travis build who failed hier

https://travis-ci.org/mpoiriert/nucleus/jobs/9138395

```
PHPUnit_Framework_Exception: PHP Fatal error:  Can't inherit abstract function Go\Aop\Intercept\Joinpoint::proceed() (previously declared abstract in Go\Aop\Framework\AbstractMethodInvocation) in /home/travis/build/mpoiriert/nucleus/vendor/lisachenko/go-aop-php/src/Go/Aop/Framework/AbstractMethodInvocation.php on line 22
```

**Comment by lisachenko** [comment]
Thank you for the bug report. It's quite interesting, but this bug is appearing only in the old versions of PHP: 5.3.0-5.3.8 http://3v4l.org/rILB2
