### ISSUE TITLE
Proper settings for production (bug with apc)

### ISSUE THREAD

**Issue by mpoiriert** [goaop/framework#76]
I'm doing test for our comming soon realease using your aop library.

I did enable apc, on  a small project it's working fine but with my bigger project (a lot more classes) I get a error in the TokenReflection library (I know it's not yours but you may have run into this problem). The error message I get is

"The parameter class is expected to be either a string or an object"

vendor\andrewsville\php-token-reflection\TokenReflection\Php\ReflectionMethod.php [ 59 ]
54   \* @param string $methodName Method name
55   \* @param \TokenReflection\Broker $broker Reflection broker
56   _/
57  public function __construct($class, $methodName, Broker $broker)
58  {
59      parent::__construct($class, $methodName);
60      $this->broker = $broker;
61  }
62 
63  /_*
64   \* Returns the declaring class reflection.

I have a html stacktrace (with environment) generated by the framework (kohana), I cannot attach it to the ticket since it's a html file.

Also what are the production settings that you recommended and know do/don't so I can prepare properly ?

**Comment by lisachenko** [comment]
Hello!

Unfortunately, I have never seen this exception before. Could you attach the trace for this exception? And value of the `class` parameter. 
I also need the version of PHP and APC. Probably, this issue is related to a bug in a version of software that you use.

**Comment by lisachenko** [comment]
For production settings I recommend to use `apc.stat=off` and kernel `debug=false`. This should be enough to have a nice performance. My settings for APC are following:

```
apc.enabled=1
apc.shm_size=512M
apc.num_files_hint=10000
apc.user_entries_hint=10000
apc.max_file_size=5M
apc.stat=0
apc.optimization=0
apc.shm_segments=1
apc.enable_cli=1
apc.cache_by_default=1
```

**Comment by lisachenko** [comment]
Is this issue still actual?

**Comment by mpoiriert** [comment]
Sorry, we just released last tursday, not with exact settings you metion but wit apc enabled and apc.stat=0.

Everything seams to work fine.

Did you think about having a warmup system ? I think this could be usefull and easy with the composer dump-autoload --optimize...

**Comment by lisachenko** [comment]
> Everything seams to work fine.

Very nice )

I have already thought about warmuper for cache, but have not time to implement this feature now. I will create an separate issue for this.

Thank you very much! Your feedback is always very constructive and helpful for me )

**Comment by lisachenko** [comment]
Cache warmer: #84
