### ISSUE TITLE
Warning: include(php://filter/read=go.source.transforming.loader/resource)

### ISSUE THREAD

**Issue by cxbyte** [goaop/framework#77]
Hello
install your library using composer
and make test script from documentation like this

``` php
error_reporting(E_ALL);
ini_set("display_errors", 1);

include __DIR__ . '/vendor/autoload.php'; // use composer
```

``` php
use Go\Aop\Aspect;
use Go\Aop\Intercept\FieldAccess;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\After;
use Go\Lang\Annotation\Before;
use Go\Lang\Annotation\Around;
use Go\Lang\Annotation\Pointcut;
use Go\Core\AspectKernel;
use Go\Core\AspectContainer;

/**
 * Monitor aspect
 */
class MonitorAspect implements Aspect
{

    /**
     * Method that will be called before real method
     *
     * @param MethodInvocation $invocation Invocation
     * @Before("execution(public Example->*(*))")
     */
    public function beforeMethodExecution(MethodInvocation $invocation)
    {
        $obj = $invocation->getThis();
        echo 'Calling Before Interceptor for method: ',
             is_object($obj) ? get_class($obj) : $obj,
             $invocation->getMethod()->isStatic() ? '::' : '->',
             $invocation->getMethod()->getName(),
             '()',
             ' with arguments: ',
             json_encode($invocation->getArguments()),
             "<br>\n";
    }
}
```

``` php
/**
 * Application Aspect Kernel
 */
class ApplicationAspectKernel extends AspectKernel
{

    /**
     * Configure an AspectContainer with advisors, aspects and pointcuts
     *
     * @param AspectContainer $container
     *
     * @return void
     */
    protected function configureAop(AspectContainer $container)
    {
        $container->registerAspect(new MonitorAspect());
    }
}
```

``` php
// Initialize an application aspect container
$applicationAspectKernel = ApplicationAspectKernel::getInstance();
$applicationAspectKernel->init(array(
        'debug' => true, // use 'false' for production mode
        // Cache directory
        'cacheDir'  => __DIR__ . '/cache',
        // Include paths restricts the directories where aspects should be applied, or empty for all source files
        'includePaths' => array('')
));


//var_dump($applicationAspectKernel);
```

``` php
Class Example
{

    public function test()
    {
        echo 'test';
    }

}
```

``` php
$example = new Example();
$example->test();
```

But have this warning 

Warning: include(php://filter/read=go.source.transforming.loader/resource=/var/www/my-site.ru): failed to open stream: operation failed in /var/www/my-site.ru/vendor/lisachenko/go-aop-php/src/Go/Instrument/ClassLoading/SourceTransformingLoader.php on line 144 Warning: include(): Failed opening 'php://filter/read=go.source.transforming.loader/resource=/var/www/my-site.ru' for inclusion (include_path='.:/usr/local/php-fpm/lib/php') in /var/www/my-site.ru/vendor/lisachenko/go-aop-php/src/Go/Instrument/ClassLoading/SourceTransformingLoader.php on line 144

what am I doing wrong? maybe 'includePaths' => array('') wrong set?

**Comment by lisachenko** [comment]
Hello, try to remove `includePaths` option and leave it default. One more question: do you define `Example` class in the same file with the source code that use it?

**Comment by cxbyte** [comment]
I have removed includePaths
// Initialize an application aspect container
$applicationAspectKernel = ApplicationAspectKernel::getInstance();
$applicationAspectKernel->init(array(
        'debug' => true, // use 'false' for production mode
        // Cache directory
        'cacheDir'  => **DIR** . '/cache'
));

all warnings remain the same.

Warning: include(php://filter/read=go.source.transforming.loader/resource=/var/www/my-site.ru): failed to open stream: operation failed in /var/www/my-site.ru/vendor/lisachenko/go-aop-php/src/Go/Instrument/ClassLoading/SourceTransformingLoader.php on line 144 Warning: include(): Failed opening 'php://filter/read=go.source.transforming.loader/resource=/var/www/my-site.ru' for inclusion (include_path='.:/usr/local/php-fpm/lib/php') in /var/www/my-site.ru/vendor/lisachenko/go-aop-php/src/Go/Instrument/ClassLoading/SourceTransformingLoader.php on line 144

Yeah, all classes defined in one file.

**Comment by lisachenko** [comment]
> Yeah, all classes defined in one file.

Go! AOP isn't able to rewrite a classes that are already loaded into memory. So if you want to use AOP then you should use PSR-0 standard to put each class into the separate file and then just use composer autoloader to load it.

**Comment by cxbyte** [comment]
Thanks for the quick reply. Now it works great :-)
