### ISSUE TITLE
I must be missing something, it doesn't work for me... 

### ISSUE THREAD

**Issue by kampernet** [goaop/framework#82]
Hi I've tried to get this running but it just won't work, at first I thought it was due to Laravel 4 caching but then I just made the most simple example and it still would not work.  I checked that eAccelerator and ZendOptimizer+ are not on my php install.  I'm running PHP 5.4.16 on a Centos VM.

here's my code, maybe you can help?

in one file I have the class Example

```
class Example {

    public function testingAll($testing) {

        echo "this is a test $testing";
    }

    public function lskdjflskd() {

        echo "lsdkfjlskdjf";
    }
}
```

then my code is just this: 

```
include "../vendor/autoload.php";
include "../app/services/Example.php";
include "../app/services/ApplicationAspectKernel.php";
include "../app/services/MonitorAspect.php";

// Initialize an application aspect container
$applicationAspectKernel = ApplicationAspectKernel::getInstance();
$applicationAspectKernel->init(array(
    'debug' => true, // use 'false' for production mode
    // Cache directory
    'cacheDir' => '/tmp',
    // Include paths restricts the directories where aspects should be applied, or empty for all source files
    'includePaths' => array()
));

$e = new Example();
$e->testingAll('lskdfjlskdf');
$e->lskdjflskd();
```

Where MonitorAspect is from your example and my ApplicationAspectKernel makes the call to register it... 

any thoughts?  I seem to be the only one who can't get this working, the framework looks amazingly cool and I would LOVE to get it working.  I hope it's just something very obvious I'm missing.  I think what I'm missing is what you mention in step 4: 

_"Adjust the front controller of your application for proxying autoloading requests to the aspect kernel"_

can you elaborate on that?

also: I don't get any errors, I just get the expected ( un aspect advised ) output _"this is a test lskdfjlskdflsdkfjlskdjf"_

also: I did modify MonitorAspect's annotations, I tried all kinds of combinations:

```
use Go\Aop\Aspect;
use Go\Aop\Intercept\FieldAccess;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\After;
use Go\Lang\Annotation\Before;
use Go\Lang\Annotation\Around;
use Go\Lang\Annotation\Pointcut;
use Whoops\Example\Exception;

class MonitorAspect implements Aspect {

    public function __construct() {

        ob_start();
    }

    public function __destruct() {

        ob_end_flush();
    }

    /**
     * Method that will be called before real method
     *
     * @param MethodInvocation $invocation Invocation
     * @Before("within(Example)")
     */
    public function beforeMethodExecution(MethodInvocation $invocation) {

        $obj = $invocation->getThis();

        echo 'Calling Before Interceptor for method: ',
        is_object($obj) ? get_class($obj) : $obj,
        $invocation->getMethod()->isStatic() ? '::' : '->',
        $invocation->getMethod()->getName(),
        '()',
        ' with arguments: ',
        json_encode($invocation->getArguments()),
        "<br>\n";
    }

}
```

Joel

**Comment by lisachenko** [comment]
Hello, Joel

AOP is tricky thing and userland implementation of it can not change the already loaded class. So, in your case you are loading `Example.php` explicitly with `include "../app/services/Example.php";` and this means that AOP will not be able to change the class without extensions, so please, delegate this autoloading job to the composer library. 

BTW, you can have a look at `demos/` folder (just open it in the browser to execute) to find out the way to configure the working environment.

**Comment by kampernet** [comment]
Thanks for the reply, it also doesn't work with me using it with Laravel.  ie: the following code in App::before in filters.php 

```
    // Initialize an application aspect container
    $applicationAspectKernel = ApplicationAspectKernel::getInstance();
    $applicationAspectKernel->init(array(
        'debug' => true, // use 'false' for production mode
        // Cache directory
        'cacheDir' => storage_path().'/cache/',
        // Include paths restricts the directories where aspects should be applied, or empty for all source files
        'includePaths' => array()
    ));
```

and then this route: 

```
Route::get('/', function() {

    $e = new Example();
    $e->testingAll('lskdfjlskdf');
    $e->lskdjflskd();

    return '';
});
```

In this case all of the autoloading is done with composer no?

**Comment by lisachenko** [comment]
So, you loading `Example` class with composer now? And it is defined in the top-level (global) namespace? If yes, then everything should be correct.

I can give you one more link to the pre-configured version of Laravel+AOP: https://github.com/lisachenko/laravel-aspect. It has a bug in Symfony2 component (fatal is expected), but if you change pointcut or fix that bug, then you will get something like this: http://laravel.aopphp.com/?aspect

**Comment by kampernet** [comment]
hi lisachenko.  

I made a VirtualHost entry for your demos and had to change a couple lines, eg: my server **DIR** has the trailing slash, and I added a 

```
} elseif (file_exists('../../../autoload.php')) {
    $loader = include '../../../autoload.php';
}
```

at line 17 of your demos/autoload.php and it WORKED!  so it's obviously my code, and not my server implementation.  that's good!  thanks for your help, I'll keep debugging.  I think I was right in assuming it was in step 4 where I tripped up: 

_"Adjust the front controller of your application for proxying autoloading requests to the aspect kernel"_ 

if you could provide more info about what this entails in your documentation, I think it'd go a long way.  I still don't see where I went wrong in my code before where it wasn't working, but your demo code works so I'll start from there.

thanks again for the great code library!

Joel

**Comment by kampernet** [comment]
also, the clone of the laravel-aspect worked ( with the Symfony bug as you mentioned )... looking at it looks like all you've done is modify public/index.php to get the AspectKernel and call it's init method... did you have to do anything else to laravel to get it to work?  it just seems to me that's what I did and it didn't work... 

edit: actually... I think I put that code in the App::before filter and in the Route... but not before the call to bootstrap/start.php   do you think that's it?

**Comment by lisachenko** [comment]
@kampernet yes, it's just few lines to modify to make it running ) Probably, your issue is related to autoloading. Do not use explicit `include` to load classes, because AOP won't handle such cases without extension

**Comment by lisachenko** [comment]
Thank you for feedback! Have a nice experiments! )

**Comment by kampernet** [comment]
yes, looking at the /laravel-aspect project further, it was the autoload hijacking I was missing.  thanks again, I will definitely start playing around now :)
