### ISSUE TITLE
Codeception unit tests fail with latest commit - df96f1c

### ISSUE THREAD

**Issue by mohangk** [goaop/framework#88]
The latest commit df96f1c has  broken codeception within my Laravel app. When I lock my version of go-aop-php to "dev-master#98641c8", things work fine. But now when I try to run the same tests I get the following error:

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"syntax error, unexpected ';'","file":"\/vagrant\/bootstrap\/start.php","line":46}}

That error happens to be the following line in the start.php this line https://github.com/mohangk/laravel_sample_app/blob/master/bootstrap/start.php#L46

Any help is appreciated

**Comment by lisachenko** [comment]
@zvirusz This issue was introduced by PR #85 Can you have a look?
@mohangk Can you help us by submitting a small PR with broken test for this?

**Comment by worried-networking** [comment]
Ooops, sorry guys, fixed in #89.

**Comment by mohangk** [comment]
@zvirusz is too fast :+1:  Will try this fix later in the day.

I would like to write a failing spec, is there some place where I can read on how to setup and run the test suite for go-php ?

**Comment by lisachenko** [comment]
@mohangk Running tests is pretty easy: just install the framework and run `phpunit` in it. You can also use an IDE for this such as phpStorm.
