### ISSUE TITLE
GO! AOP breaks composer autoloader

### ISSUE THREAD

**Issue by worried-networking** [goaop/framework#91]
I'm trying to work with `PHPExcel` and at some point autoloading fallbacks to Yii's built-in and then fails. At this point I don't need GO! Aop features so I've commented out `AopComposerLoader.php` in composer's `autoload_files.php` - and everything works ok.

@lisachenko, if you don't have any ideas 'why?' - I'll create sample failing app in next few days.

**Comment by lisachenko** [comment]
@zvirusz I haven't any ideas, everything should be correct. Could you attach a trace for this error or extract wrong behavior to the broken test?

**Comment by worried-networking** [comment]
@lisachenko I couldn't reproduce it on empty project, so I just fixed this issue with #92 :)
