### ISSUE TITLE
When proxy classes trick everyone

### ISSUE THREAD

**Issue by DavertMik** [goaop/framework#94]
I have a code:

``` php
<?php
UserService::activateUser(User $user) { }
?>
```

and 

``` php
<?php
class User {
    function register() {
        UserService::activateUser($this);
     }

}
?>
```

`User::activateUser` receives `User_AopProxied` instead of `User`, thus code fails.

Do you have any ideas or workarounds for this?

**Comment by lisachenko** [comment]
If you intercept methods in the  `User` class then `$this` should point to the proxy class with `User` name and typehint should work correctly. But this issue is typically happen with expressions such as `new self()` when a source code doesn't aware of possible children classes.

**Comment by lisachenko** [comment]
This issue is related to https://github.com/symfony/symfony/pull/8367
