### ISSUE TITLE
Intergrate with PHPSpec and CodeIgnier

### ISSUE THREAD

**Issue by cyansilver** [goaop/framework#96]
Hi,

I used the framework with PHPSpec but PHPSpec raises an error relative to "stream_filter_register" function.
Additionally, I tried to use it with CodeIgniter but it doesn't work.

Can anyone please help me with those and explain how the framework works? Thank you.

**Comment by lisachenko** [comment]
Hello, can you attach a trace with an error for PHPSpec? I will be able to try to reproduce this issue on weekend. If you could create a test repository with configured Codeigniter and Go! framework, I will be grateful you as this can reduce the time for investigating the root cause of this issue.

**Comment by cyansilver** [comment]
Hi lisachenko,

I created the repository with configured CodeIgniter and Go! framework here: https://github.com/Cyansilver/ci_goaop
I'm not sure how to get a trace with the error for PHPSpec but the error is shown as below:
"exception [exc: RuntimeException ("Stream filter already registered") ]" has been throw.

**Comment by cyansilver** [comment]
Sorry, I closed it accidentally, need reopen

**Comment by lisachenko** [comment]
Thank you very much for the pre-configured repo ) Unfortunately, I'm too busy now and can not investigate this issue. However, I have looked into the code in your repository and have an idea, that your configuration of AOP is not correct.
AOP should be configured only once at early stage of running the code (ideally, index.php or autoload.php). So, it will be better to extract the AOP configuration from the class and put it in the separate file.

For PHPSpec configuration of AOP is harder, but there is a possible way to add an extension for PHPSpec that will be registered automatically by PHPSpec kernel. To add an extension for AOP you can try to specify extension class in yml file for PHPSpec

**Comment by cyansilver** [comment]
Hi lisachenko,

I knew the reason why I used CodeIgniter with Go! framework didn't work.
The reason is I didn't auto load the files using the composer. Now everything works fine.

**Comment by lisachenko** [comment]
Great news ) Thank you for feedback! I know, that installation of AOP without composer is not clear enough, so sorry for this fact. I will continue development of my library in new year.
