### ISSUE TITLE
Composer package - unnecessary files

### ISSUE THREAD

**Issue by meetmatt** [goaop/framework#98]
Please, remove Demo namespace autoloader and "src/Go/Instrument/ClassLoading/AopComposerLoader.php" file autoloader from composer.json.
Those are totally unnecessary for production use, though quite useful as examples.
You could even separate Demo files from the project to another project on github with go-aop-php as dependency just to keep things clean. What do you think?

**Comment by lisachenko** [comment]
Hello! I have the same thoughts that the `Demo` namespace shouldn't be in composer.json. So, I will remove this namespace from the composer and want to add it to the `autoload.php` instead.

However, AopComposerLoader is an important part of library that enables AOP with composer. It can not be removed. 

I'm not decided on demos files yet. On the one hand this is very useful for initial tests and playing with framework, on the other hand we do not need them for production.

**Comment by lisachenko** [comment]
For the moment, demos files will be in the project for easy use.

**Comment by meetmatt** [comment]
Thanks! Keep up with great projects!
