### ISSUE TITLE
Parse error: syntax error, unexpected '$', expecting '&' or T_VARIABLE in

### ISSUE THREAD

**Issue by TheRatG** [goaop/framework#99]
Hello
I have this problem, when i try to run example PHP 5.3.27

Parse error: syntax error, unexpected '$', expecting '&' or T_VARIABLE in <path>/vendor/lisachenko/go-aop-php/demos/cache/_functions/Demo/Example.php  on line 4740

``` php
function http_build_url($, $, $, &$)
{
...
```

**Comment by TheRatG** [comment]
When I disable **cacheDir** or **interceptFunctions** option, example work correctly.

**Comment by lisachenko** [comment]
This bug is related to the wrong information for this function for reflection inside PHP extension. Please, could you attach an output of `php --rf http_build_url`?

**Comment by lisachenko** [comment]
You can also exclude this functions from the function pointcut at https://github.com/lisachenko/go-aop-php/blob/master/demos/Demo/Aspect/DebugAspect.php#L143. For example, change to the `@Around("execution(Demo\Example\array_*(*))")` to intercept only array functions inside `Demo\Example` namespace.

**Comment by lisachenko** [comment]
Ping. Waiting for information about `http_build_url` function.

**Comment by lisachenko** [comment]
No details here, closing. Feel free to reopen if needed.
